/* Auto-generated by scripts/build-bauleitung-projektsteuerung-legacy.mjs – do not edit by hand. */
/* eslint-disable react/no-danger */

export const bauleitungProjektsteuerungLegacySections = [
  {
    id: 'sanierung-koordiniert-durchfuehren',
    title: "Sanierung koordiniert durchführen",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="intro-section">
  <div class="intro-text">
    <div class="section-label">Sanierung koordiniert durchführen</div>
    <p style="font-size:17px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine Sanierung ist selten nur eine handwerkliche Einzelleistung. Sobald mehrere Gewerke beteiligt sind, entscheidet nicht allein die Qualität einzelner Arbeiten über das Ergebnis, sondern vor allem die Koordination. Rückbau, Heizung, Sanitär, Elektrokoordination, Trockenbau, Fliesen, Böden, Malerarbeiten, Innenausbau, Schadstoffprüfung, Materialentscheidungen, Zeitplan und Übergabe müssen in einer sinnvollen Reihenfolge zusammengeführt werden.</p>
    <p style="font-size:17px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Genau hier setzt die Bauleitung und Projektsteuerung der Radex Objektmanagement GmbH an. Radex begleitet Sanierungen im Rhein-Main-Gebiet mit klarer Struktur, fester Kommunikation und koordinierter Ausführung. Für Eigentümer, Käufer, Eigennutzer, Vermieter, Hausverwaltungen und Gewerbekunden bedeutet das: ein zentraler Ansprechpartner, ein nachvollziehbarer Ablauf und eine Sanierung, bei der die beteiligten Fachgewerke nicht nebeneinander, sondern miteinander arbeiten.</p>
    <p style="font-size:17px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Gerade bei Sanierungen im Bestand ist Bauleitung besonders wichtig. Anders als beim Neubau ist nicht immer sofort sichtbar, was sich hinter Fliesen, unter Böden, in Wänden, an Leitungen oder in älteren Bauteilen befindet. Während der Arbeiten können alte Installationen, Feuchtigkeit, Schimmel, unklare Wandaufbauten, Schadstoffverdacht, nicht dokumentierte Umbauten oder technische Abweichungen sichtbar werden. Dann braucht es jemanden, der solche Befunde einordnet, die nächsten Schritte abstimmt und den Ablauf sinnvoll weiterführt.</p>
    <p style="font-size:17px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex übernimmt diese Rolle als koordinierender Sanierungspartner. Im Bereich Heizung, Sanitär und Gebäudetechnik ist Radex SHK-meistergeführt durch Bernd Knoop, SHK-Meister und Betriebsleiter. Sanitärinstallation, Wasserleitungen, Abwasser, Heizungsmodernisierung, Warmwasserbereitung, Heizkörper und Gebäudetechnik werden dadurch fachlich verantwortet. Weitere Gewerke wie Elektrotechnik, Trockenbau, Fliesen, Bodenverlegung, Malerarbeiten, Innenausbau, Dämmung oder Schadstoffsanierung werden durch qualifizierte Fachpartner ausgeführt und von Radex koordiniert.</p>
    <p style="font-size:17px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bauleitung bedeutet dabei nicht nur, Termine zu kontrollieren. Eine gute Projektsteuerung beginnt deutlich früher: bei der Zielklärung, Bestandsaufnahme, Reihenfolgeplanung, Gewerkeabstimmung, Materialentscheidung, Schnittstellenprüfung und Vorbereitung der Ausführung. Wer diese Punkte erst auf der Baustelle klärt, riskiert Verzögerungen, unnötige Rückfragen, Nacharbeiten und steigende Kosten.</p>
    <p style="font-size:17px;color:var(--text-light);line-height:1.75">Radex unterstützt Kunden bei <a href="/badsanierung-rhein-main">Badsanierung</a>, Wohnungssanierung, Haussanierung, <a href="/komplettsanierung-rhein-main">Komplettsanierung</a>, <a href="/kernsanierung-rhein-main">Kernsanierung</a>, <a href="/teilsanierung-rhein-main">Teilsanierung</a>, Altbausanierung, Innenausbau, Heizungsmodernisierung, Sanitärinstallation, energetischer Sanierung, Schadstoffsanierung, Gewerbesanierung, Büroumbau und Mieterausbau. Entscheidend ist immer ein Ablauf, der zum Objekt, zur Nutzung und zum gewünschten Ergebnis passt.</p>
    <p style="font-size:17px;color:var(--text-light);line-height:1.75;margin-top:20px">Planen Sie eine Sanierung im Rhein-Main-Gebiet und möchten die Koordination nicht selbst übernehmen? Rufen Sie Radex unter <a href="tel:+496074960620">06074 960620</a> an oder senden Sie eine unverbindliche Anfrage über den <a href="/kontakt">Kontaktbogen</a>. Mit Bildern, Grundrissen oder vorhandenen Unterlagen können wir Ihr Projekt vorab besser einschätzen.</p>
    <div class="link-list" style="margin-top:24px">
      <a href="/generalunternehmer-rhein-main" class="link-pill">Generalunternehmer</a>
      <a href="/komplettsanierung-rhein-main" class="link-pill">Komplettsanierung</a>
      <a href="/kernsanierung-rhein-main" class="link-pill">Kernsanierung</a>
      <a href="/badsanierung-rhein-main" class="link-pill">Badsanierung</a>
      <a href="/heizung-sanitaer-rhein-main" class="link-pill">Heizung &amp; Sanitär</a>
      <a href="/kontakt" class="link-pill">Kontakt</a>
    </div>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'warum-bauleitung-bei-sanierungen-entscheidend-ist',
    title: "Warum Bauleitung bei Sanierungen entscheidend ist",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Koordination als Kernaufgabe</div>
  <h2>Warum Bauleitung bei Sanierungen entscheidend ist</h2>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bei einer Sanierung greifen viele Arbeiten ineinander. Ein Bad kann nicht sauber fertiggestellt werden, wenn Sanitär, Abdichtung, Elektrokoordination, Trockenbau, Fliesen und Endmontage nicht zusammenpassen. Eine Wohnungssanierung wird unübersichtlich, wenn Bad, Küche, Böden, Wände, Türen, Heizkörper und Elektroanschlüsse getrennt voneinander geplant werden. Eine Haussanierung braucht noch mehr Abstimmung, weil Heizung, Sanitär, Keller, Energie, Innenausbau, Raumaufteilung und mögliche Schadstoffthemen zusammenhängen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Ohne Bauleitung entstehen häufig Probleme an den Übergängen zwischen den Gewerken. Ein Boden wird verlegt, bevor staubintensive Arbeiten abgeschlossen sind. Eine Wand wird geschlossen, obwohl Elektro- oder Sanitärleitungen noch nicht final geprüft wurden. Ein Bad wird gestaltet, bevor Abdichtung und Leitungsführung sauber geklärt sind. Eine Heizung wird erneuert, ohne Heizflächen, Warmwasserbedarf und Gebäudezustand ausreichend zu berücksichtigen. Solche Schnittstellen entscheiden darüber, ob eine Sanierung ruhig läuft oder später korrigiert werden muss.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex übernimmt die Koordination dieser Schnittstellen. Das ist besonders wertvoll bei mehrgewerklichen Sanierungen, bei denen Eigentümer nicht jeden Arbeitsschritt selbst überwachen können oder möchten. Die meisten Kunden haben berufliche Verpflichtungen, Familie, eigene Projekte oder mehrere Immobilien. Sie benötigen einen Partner, der den Überblick behält, Entscheidungen vorbereitet und die beteiligten Fachpartner sinnvoll abstimmt.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bauleitung bei Radex bedeutet: Der Sanierungsumfang wird geklärt, der Bestand wird geprüft, die Reihenfolge der Gewerke wird vorbereitet, SHK-Arbeiten werden fachlich geführt und weitere Fachbetriebe werden in den Ablauf eingebunden. Dazu kommen Kommunikation mit Eigentümern, Hausverwaltungen, Mietern oder Gewerbekunden, Reaktion auf Befunde im Bestand und Begleitung bis zur Übergabe.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Gerade bei Sanierungen im Bestand ist diese Steuerung entscheidend. Viele wichtige Themen sind erst sichtbar, wenn Bauteile geöffnet werden. Eine gute Bauleitung erkennt, welche Entscheidungen dann notwendig sind, welche Fachpartner eingebunden werden müssen und wie der weitere Ablauf angepasst werden sollte.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Wenn Sie eine Sanierung planen, bei der mehrere Gewerke beteiligt sind, lohnt sich eine frühe Abstimmung. Radex ist unter <a href="tel:+496074960620">06074 960620</a> erreichbar.</p>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Kostenlos beraten lassen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'projektsteuerung-beginnt-vor-dem-baustart',
    title: "Projektsteuerung beginnt vor dem Baustart",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="section-label">Planung vor der Ausführung</div>
  <h2>Projektsteuerung beginnt vor dem Baustart</h2>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Viele Schwierigkeiten auf Baustellen entstehen nicht während der Ausführung, sondern durch fehlende Vorbereitung. Wenn vor Baustart nicht klar ist, welche Arbeiten wann erfolgen, welche Materialien ausgewählt sind, welche Fachpartner benötigt werden und welche Schnittstellen bestehen, muss später improvisiert werden. Das kostet Zeit, verursacht Rückfragen und kann das Ergebnis belasten.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex setzt deshalb früh an. Vor Beginn der Arbeiten wird geklärt, welches Ziel die Sanierung hat. Soll eine Wohnung vor dem Einzug bezugsfertig gemacht werden? Wird ein Bad in einer bewohnten Immobilie saniert? Geht es um eine Haussanierung nach Kauf? Soll eine Gewerbefläche für einen neuen Mieter vorbereitet werden? Muss eine <a href="/komplettsanierung-rhein-main">Komplettsanierung</a> oder <a href="/kernsanierung-rhein-main">Kernsanierung</a> geplant werden? Oder reicht eine gezielte <a href="/teilsanierung-rhein-main">Teilsanierung</a>?</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Je nach Projekt werden unterschiedliche Fragen wichtig. Ist die Immobilie leer, bewohnt, vermietet oder gewerblich genutzt? Welche Gewerke sind beteiligt? Welche Arbeiten müssen zuerst erfolgen? Gibt es Grundrisse, Fotos oder Bestandsunterlagen? Müssen Hausverwaltung, Eigentümergemeinschaft, Mieter oder Gewerbekunden eingebunden werden? Besteht Feuchtigkeit, Schimmel oder Asbestverdacht? Welche Materialien haben Lieferzeiten? Wie werden Zugang, Schutzmaßnahmen, Entsorgung und Baustellenlogistik organisiert?</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Diese Vorbereitung macht die Sanierung planbarer. Ein Bad kann nur dann zügig umgesetzt werden, wenn Sanitärobjekte, Fliesen, Armaturen, Abdichtung, Trockenbau, Elektrokoordination und Heizkörper rechtzeitig abgestimmt sind. Eine Wohnungssanierung läuft ruhiger, wenn Rückbau, Böden, Wände, Türen, Küche, Bad und Heizkörper in der richtigen Reihenfolge geplant werden. Eine Haussanierung braucht noch mehr Vorarbeit, weil mehrere Bereiche gleichzeitig betroffen sein können.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Projektsteuerung schützt Kunden vor typischen Fehlern. Sie sorgt dafür, dass wichtige Entscheidungen nicht erst dann auftauchen, wenn der Fachbetrieb bereits auf der Baustelle steht. Radex bereitet diese Entscheidungen vor und stimmt sie mit dem Kunden ab.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Planen Sie eine Sanierung und möchten vorab wissen, welche Reihenfolge sinnvoll ist? Rufen Sie Radex unter <a href="tel:+496074960620">06074 960620</a> an oder senden Sie eine unverbindliche Anfrage über den <a href="/kontakt">Kontaktbogen</a>.</p>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Badplanung starten</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'bauleitung-bei-badsanierung-kleine-flaeche-viele-schnittstellen',
    title: "Bauleitung bei Badsanierung – kleine Fläche, viele Schnittstellen",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Badsanierung</div>
  <h2>Bauleitung bei Badsanierung – kleine Fläche, viele Schnittstellen</h2>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine <a href="/badsanierung-rhein-main">Badsanierung</a> ist ein gutes Beispiel dafür, warum Bauleitung auch bei einem einzelnen Raum wichtig sein kann. Ein Bad ist zwar räumlich begrenzt, aber technisch anspruchsvoll. Wasserleitungen, Abwasser, Abdichtung, Heizkörper, Lüftung, Elektrokoordination, Trockenbau, Fliesen und Endmontage müssen exakt zusammenpassen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bei einer Badsanierung koordiniert Radex Rückbau, Leitungsprüfung, Sanitärinstallation, Abdichtung, Vorwandinstallation, Trockenbau, Duschlösung, WC, Waschtisch, Armaturen, Badmöbel, Heizkörper, Beleuchtung, Lüfter, Fliesenarbeiten und Endmontage. Im Bereich Heizung und Sanitär bringt Radex die eigene SHK-Meisterkompetenz ein. Elektroarbeiten werden durch qualifizierte Elektrofachpartner ausgeführt und von Radex in den Sanierungsablauf eingebunden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Wenn diese Schritte nicht sauber koordiniert sind, entstehen schnell Probleme. Anschlüsse passen nicht, Abdichtungen müssen erneut geöffnet werden, fertige Oberflächen werden beschädigt oder Termine verschieben sich, weil Material- oder Detailentscheidungen zu spät getroffen wurden. Gerade im Bad sind solche Fehler besonders ärgerlich, weil Feuchtigkeit, Abdichtung und Technik dauerhaft zuverlässig funktionieren müssen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bauleitung sorgt dafür, dass Gestaltung und Technik nicht getrennt voneinander entschieden werden. Eine bodengleiche Dusche, eine neue Vorwand, ein Handtuchheizkörper, zusätzliche Steckdosen, eine bessere Beleuchtung oder ein Lüfter müssen früh in die Planung einbezogen werden. Erst wenn diese Punkte abgestimmt sind, lässt sich das Bad sauber umsetzen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Planen Sie eine Badsanierung im Rhein-Main-Gebiet? Rufen Sie Radex unter <a href="tel:+496074960620">06074 960620</a> an. Bilder vom vorhandenen Bad oder ein einfacher Grundriss helfen bei der ersten Einschätzung.</p>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Unverbindlich anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'bauleitung-bei-wohnungssanierung-planbar-modernisieren-im-mehrfamilienhaus',
    title: "Bauleitung bei Wohnungssanierung – planbar modernisieren im Mehrfamilienhaus",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="section-label">Wohnungssanierung</div>
  <h2>Bauleitung bei Wohnungssanierung – planbar modernisieren im Mehrfamilienhaus</h2>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine Wohnungssanierung braucht eine andere Organisation als eine Sanierung im freistehenden Haus. Häufig befinden sich die Arbeiten in einem Mehrfamilienhaus. Treppenhaus, Aufzug, Nachbarn, Hausordnung, Materialtransport, Entsorgung, Bauzeiten und Abstimmung mit der Hausverwaltung müssen berücksichtigt werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex koordiniert Wohnungssanierungen nach Kauf, Erbschaft, Mieterwechsel oder langer Nutzung. Dabei können Rückbau, Badsanierung, Küchenanschlüsse, Elektrokoordination, Heizkörper, Bodenbeläge, Wandflächen, Türen, Zargen, Sockelleisten, Trockenbau, Malerarbeiten und Übergabe zusammengeführt werden. Ziel ist eine Wohnung, die nicht nur frisch aussieht, sondern zur geplanten Nutzung passt.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Für Eigennutzer ist Bauleitung besonders wichtig, wenn die Wohnung vor dem Einzug saniert werden soll. Dann müssen Arbeiten in kurzer Zeit sinnvoll aufeinander folgen. Bad, Küche, Böden, Wände und Elektro dürfen nicht getrennt voneinander geplant werden. Wer hier früh koordiniert, vermeidet spätere Nacharbeiten im bereits eingerichteten Zuhause.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Für Vermieter und Hausverwaltungen steht häufig die Planbarkeit im Vordergrund. Eine Wohnung soll nach Mieterwechsel schnell, sauber und wirtschaftlich wieder nutzbar werden. Dabei muss nicht jede Wohnung komplett saniert werden. Manchmal reicht eine gezielte <a href="/teilsanierung-rhein-main">Teilsanierung</a>. In anderen Fällen ist eine umfassendere Modernisierung sinnvoll, weil sonst immer wieder neue Reparaturen entstehen. Radex hilft, den Umfang realistisch einzuordnen und die Fachgewerke entsprechend zu steuern.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Gerade bei Wohnungen ist Kommunikation wichtig. Eigentümer, Hausverwaltung, Nachbarn, Mieter und Fachpartner müssen je nach Projekt einbezogen werden. Radex übernimmt diese Abstimmung projektbezogen und sorgt dafür, dass die Sanierung nicht aus unverbundenen Einzelterminen besteht.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Wenn Sie eine Wohnung sanieren lassen möchten, erreichen Sie Radex unter <a href="tel:+496074960620">06074 960620</a> oder über den <a href="/kontakt">Kontaktbogen</a>. Fotos, Grundriss und Angaben zu Bad, Böden oder Küche helfen bei der Vorbereitung.</p>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Angebot anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'bauleitung-bei-haussanierung-technik-raeume-und-bestand-zusammenfuehren',
    title: "Bauleitung bei Haussanierung – Technik, Räume und Bestand zusammenführen",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Haussanierung</div>
  <h2>Bauleitung bei Haussanierung – Technik, Räume und Bestand zusammenführen</h2>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine Haussanierung ist meist komplexer als eine einzelne Bad- oder Wohnungssanierung. Hier können Bad, Gäste-WC, Heizung, Sanitär, Elektrokoordination, Küche, Keller, Innenausbau, Böden, Wände, Decken, Türen, energetische Maßnahmen, Feuchtigkeit, Schimmel, Schadstoffprüfung und Raumaufteilung zusammenkommen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex prüft zunächst, welche Sanierungstiefe passend ist. Reicht eine <a href="/teilsanierung-rhein-main">Teilsanierung</a>? Ist eine <a href="/komplettsanierung-rhein-main">Komplettsanierung</a> sinnvoll? Muss eine <a href="/kernsanierung-rhein-main">Kernsanierung</a> geprüft werden? Diese Entscheidung sollte nicht aus dem Bauch heraus getroffen werden, sondern auf Basis des Bestands, der Nutzung und des gewünschten Ergebnisses.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bei einer Haussanierung übernimmt Radex die Bestandsaufnahme, ordnet den Sanierungsumfang, plant die Reihenfolge der Fachgewerke und koordiniert die Ausführung. SHK-Arbeiten werden unter Meisterverantwortung geführt. Elektroarbeiten, Trockenbau, Innenausbau, Fliesen, Böden, Malerarbeiten und weitere Fachleistungen werden durch qualifizierte Fachpartner umgesetzt und von Radex in den Ablauf eingebunden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bei bewohnten Häusern ist Bauleitung besonders wichtig. Dann müssen Bauabschnitte, Staubschutz, Sanitärnutzung, Zugänge, Alltag und Zeitplan so geplant werden, dass die Belastung überschaubar bleibt. Nicht jede Maßnahme kann gleichzeitig umgesetzt werden. Manchmal ist eine Sanierung in Etappen sinnvoller als ein großer Eingriff.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bei leerstehenden Häusern, etwa nach Kauf oder vor Einzug, kann die Bauleitung anders planen. Rückbau, Leitungen, Elektrokoordination, Bad, Heizung, Böden und Innenausbau lassen sich dann oft effizienter bündeln. Auch hier bleibt die Reihenfolge entscheidend: zuerst technische Grundlagen, dann Aufbau und Oberflächen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Planen Sie eine Haussanierung im Rhein-Main-Gebiet? Rufen Sie Radex unter <a href="tel:+496074960620">06074 960620</a> an oder senden Sie eine unverbindliche Anfrage über den <a href="/kontakt">Kontaktbogen</a>. Mit Bildern, Grundrissen oder vorhandenen Unterlagen können wir Ihr Projekt vorab besser einschätzen.</p>

  <div style="text-align:center;margin-top:40px;">
    <a href="https://wa.me/491744684189" class="btn-primary gold" target="_blank" rel="noopener">Angebot anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'projektsteuerung-bei-komplettsanierung-und-kernsanierung',
    title: "Projektsteuerung bei Komplettsanierung und Kernsanierung",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="section-label">Komplett- &amp; Kernsanierung</div>
  <h2>Projektsteuerung bei Komplettsanierung und Kernsanierung</h2>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bei <a href="/komplettsanierung-rhein-main">Komplettsanierung</a> und <a href="/kernsanierung-rhein-main">Kernsanierung</a> ist Bauleitung besonders wichtig. Je tiefer der Eingriff, desto mehr Entscheidungen müssen vorbereitet und desto mehr Schnittstellen müssen kontrolliert werden. Rückbau, Leitungen, Heizung, Sanitär, Elektrokoordination, Innenausbau, Böden, Wände, Decken, Bad, Küche, energetische Maßnahmen und Schadstoffthemen greifen eng ineinander.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine Komplettsanierung umfasst viele zentrale Bereiche einer Immobilie. Sie kann ein Haus, eine Wohnung oder eine Gewerbefläche betreffen und muss nicht immer bis auf die Rohstruktur gehen. Eine Kernsanierung ist tiefer. Sie betrifft häufig stärkeren Rückbau, technische Installationen, Boden- und Wandaufbau, Innenstruktur und teilweise energetische Bauteile.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex koordiniert bei umfangreichen Sanierungen die Bestandsaufnahme, Prüfung der Sanierungstiefe, Rückbauplanung, Schadstoffthemen, SHK-Arbeiten, Elektrokoordination, Innenausbau, Raumaufteilung, Boden-, Wand- und Deckenaufbau, Materialentscheidungen, Fachpartnertermine, Qualitätssicherung und Übergabe.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bei Kernsanierungen kommt dem Rückbau eine besondere Rolle zu. Alte Bodenbeläge, Kleber, Rohrisolierungen, Dämmstoffe, Wand- oder Deckenmaterialien können Schadstoffverdacht auslösen. Radex ist zertifiziert für Schimmel- und Asbestsanierung und verfügt über Sachkunde nach TRGS 519. Verdächtige Materialien sollten nicht eigenständig gebrochen, geschliffen, gebohrt oder entfernt werden. Erst prüfen, dann handeln.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine gute Bauleitung sorgt dafür, dass Rückbau und Prüfung nicht unkontrolliert stattfinden. Erst wenn die Grundlage geklärt ist, werden Technik und Ausbau aufgebaut. Das schafft Sicherheit und reduziert das Risiko, fertige Arbeiten später wieder öffnen zu müssen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Wenn Sie eine Komplettsanierung oder Kernsanierung planen, klärt Radex mit Ihnen die passende Vorgehensweise. Telefon: <a href="tel:+496074960620">06074 960620</a>.</p>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Sanierungsprojekt besprechen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'bauleitung-fuer-vermieter-hausverwaltungen-und-immobilienbestand',
    title: "Bauleitung für Vermieter, Hausverwaltungen und Immobilienbestand",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Vermieter &amp; Hausverwaltungen</div>
  <h2>Bauleitung für Vermieter, Hausverwaltungen und Immobilienbestand</h2>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Vermieter, Hausverwaltungen und Eigentümergemeinschaften benötigen bei Sanierungen häufig besonders planbare Abläufe. Eine Wohnung nach Mieterwechsel soll zügig wieder nutzbar werden. Ein Bad in einer vermieteten Wohnung muss sauber organisiert werden. Eine Sanierung im Mehrfamilienhaus darf Gemeinschaftsbereiche nicht unnötig belasten. Eine Gewerbefläche soll zu einem bestimmten Termin übergeben werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex unterstützt bei Sanierungen im Immobilienbestand mit klarer Projektsteuerung. Dabei geht es nicht nur um die Ausführung, sondern auch um Organisation, Abstimmung und Kommunikation. Typische Projekte sind Wohnungssanierung nach Mieterwechsel, Badmodernisierung in Mietwohnungen, Teilsanierung einzelner Einheiten, Komplettsanierung leerstehender Wohnungen, Instandsetzung nach Feuchtigkeitsschaden, Schimmelsanierung mit Ursachenprüfung, Gewerbeflächen für neue Nutzer oder Mieterausbau.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Für Vermieter ist wichtig, dass Sanierungen wirtschaftlich sinnvoll bleiben. Nicht jede Einheit braucht die gleiche Sanierungstiefe. Manchmal reicht eine <a href="/teilsanierung-rhein-main">Teilsanierung</a> mit Bad, Böden, Wänden und technischen Anpassungen. In anderen Fällen ist eine umfassendere Modernisierung sinnvoll, weil sonst immer wieder neue Reparaturen entstehen. Radex hilft, diese Entscheidung objektbezogen zu treffen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Für Hausverwaltungen ist wichtig, dass Abstimmung, Zugang, Hausordnung, Treppenhaus, Mieterinformation und Zeitfenster klar geplant werden. Bauleitung reduziert den Kommunikationsaufwand und sorgt dafür, dass nicht jedes Gewerk einzeln koordiniert werden muss.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex bleibt während des Projekts zentraler Ansprechpartner. Das erleichtert Entscheidungen und sorgt für einen nachvollziehbaren Ablauf.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Wenn Sie mehrere Einheiten, eine vermietete Wohnung oder ein Objekt im Bestand sanieren möchten, sprechen Sie mit Radex unter <a href="tel:+496074960620">06074 960620</a>.</p>

  <div style="text-align:center;margin-top:40px;">
    <a href="https://wa.me/491744684189" class="btn-primary gold" target="_blank" rel="noopener">Jetzt per WhatsApp anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'projektsteuerung-bei-gewerbesanierung-bueroumbau-und-mieterausbau',
    title: "Projektsteuerung bei Gewerbesanierung, Büroumbau und Mieterausbau",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="section-label">Gewerbe &amp; Büro</div>
  <h2>Projektsteuerung bei Gewerbesanierung, Büroumbau und Mieterausbau</h2>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Gewerbliche Sanierungen stellen besondere Anforderungen an Zeitplan, Nutzung und Übergabe. Eine Bürofläche soll modernisiert werden. Eine Praxis braucht neue Räume und Sanitärbereiche. Eine Ladenfläche wird für einen neuen Mieter vorbereitet. Ein Mieterausbau muss zu einem festen Termin abgeschlossen sein. In solchen Fällen ist Projektsteuerung besonders wichtig.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex koordiniert <a href="/gewerbe-objektsanierung-rhein-main">Gewerbesanierungen</a>, Büroumbauten und Mieterausbauten im Rhein-Main-Gebiet. Dazu gehören je nach Projekt Rückbau alter Einbauten, Trockenbau, neue Raumaufteilung, Sanitärbereiche, Bodenbeläge, Malerarbeiten, Elektrokoordination, Datentechnik, Beleuchtung, Nutzungsanforderungen, Übergabevorbereitung und Abstimmung mit Eigentümer, Mieter oder Hausverwaltung.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bei Gewerbeprojekten ist der Zeitplan oft besonders kritisch. Eine Fläche soll vermietet werden, ein Unternehmen möchte einziehen oder ein Betrieb soll während der Sanierung möglichst wenig beeinträchtigt werden. Projektsteuerung bedeutet hier, Entscheidungen früh einzuholen, Fachpartner rechtzeitig einzubinden und Arbeiten so zu koordinieren, dass die Fläche planbar nutzbar wird.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Auch bei Gewerbeflächen können Schadstoffthemen auftreten. Alte Bodenbeläge, Kleber, Deckenplatten, Rohrisolierungen oder frühere Einbauten sollten vor Rückbauarbeiten bewertet werden, wenn ein Verdacht besteht. Radex kann solche Themen in die Projektsteuerung integrieren.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Für Eigentümer und Gewerbekunden bedeutet das weniger Abstimmungsaufwand und eine klarere Verantwortung. Wer eine Gewerbefläche sanieren, umbauen oder für einen neuen Nutzer vorbereiten möchte, sollte Radex früh einbinden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Planen Sie einen Büroumbau, Mieterausbau oder eine Gewerbesanierung? Rufen Sie Radex unter <a href="tel:+496074960620">06074 960620</a> an oder senden Sie eine unverbindliche Anfrage über den <a href="/kontakt">Kontaktbogen</a>.</p>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Unverbindlich anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'schnittstellenkoordination-dort-entscheidet-sich-die-qualitaet',
    title: "Schnittstellenkoordination – dort entscheidet sich die Qualität",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Schnittstellen &amp; Qualität</div>
  <h2>Schnittstellenkoordination – dort entscheidet sich die Qualität</h2>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Die wichtigste Aufgabe der Bauleitung ist die Koordination der Schnittstellen. Sanierungsqualität entsteht nicht nur durch gute Einzelgewerke, sondern vor allem an den Übergängen zwischen ihnen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Typische Schnittstellen entstehen zwischen Sanitär und Fliesen, Heizung und Innenausbau, Elektro und Trockenbau, Boden und Rückbau, Bad und Elektrokoordination, energetischer Sanierung und Heiztechnik sowie Schadstoffprüfung und Rückbau. Jede dieser Verbindungen muss rechtzeitig berücksichtigt werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Sanitär und Fliesen müssen bei Leitungen, Abdichtung, Duschbereich, Vorwand und Wandaufbau zusammenpassen. <a href="/heizung-sanitaer-rhein-main">Heizung und Innenausbau</a> beeinflussen sich über Heizkörper, Leitungen, Nischen, Wandflächen und Fußbodenaufbau. Elektro und Trockenbau müssen geplant sein, bevor Wände geschlossen werden. Bodenbeläge sollten erst verlegt werden, wenn staubintensive Arbeiten abgeschlossen sind und der Untergrund geeignet ist. Verdächtige Materialien dürfen nicht unkoordiniert bearbeitet werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex sorgt dafür, dass diese Schnittstellen früh besprochen und im Ablauf berücksichtigt werden. Das reduziert Nacharbeiten und macht den Bauablauf ruhiger. Kunden profitieren von weniger Rückfragen, weniger widersprüchlichen Aussagen und klareren Entscheidungen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Gerade bei Sanierungen im Bestand ist diese Koordination entscheidend. Viele Bauteile sind erst sichtbar, wenn die Arbeiten begonnen haben. Eine gute Bauleitung reagiert dann nicht hektisch, sondern ordnet Befunde ein und stimmt die nächsten Schritte ab.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Wenn Ihre Sanierung mehrere Gewerke verbindet, ist eine klare Schnittstellenkoordination entscheidend. Radex erreichen Sie unter <a href="tel:+496074960620">06074 960620</a>.</p>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Beratungsgespräch vereinbaren</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'qualitaetssicherung-waehrend-der-sanierung',
    title: "Qualitätssicherung während der Sanierung",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="section-label">Qualitätssicherung</div>
  <h2>Qualitätssicherung während der Sanierung</h2>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bauleitung bedeutet auch Qualitätssicherung. Dabei geht es nicht darum, jede Kleinigkeit unnötig zu verkomplizieren, sondern relevante Punkte im richtigen Moment zu prüfen. Viele Fehler lassen sich vermeiden, wenn sie erkannt werden, bevor das nächste Gewerk startet.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Besonders wichtig sind verdeckte Arbeiten. Was später nicht mehr sichtbar ist, muss vorher stimmen. Dazu gehören Leitungen, Abdichtung, Untergründe, Dämmung, Wandaufbauten, Elektroführung und technische Anschlüsse. Wenn hier sauber gearbeitet und rechtzeitig geprüft wird, sinkt das Risiko späterer Nacharbeiten deutlich.</p>

    <ul class="trust-list">
      <li>
        <div class="tl-icon"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--gold)" stroke-width="2.5" aria-hidden="true"><polyline points="20 6 9 17 4 12"/></svg></div>
        <div><strong>Leitungen vor Wandschluss prüfen</strong>Sind Leitungen geprüft, bevor Wände geschlossen werden?</div>
      </li>
      <li>
        <div class="tl-icon"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--gold)" stroke-width="2.5" aria-hidden="true"><polyline points="20 6 9 17 4 12"/></svg></div>
        <div><strong>Abdichtung im Bad</strong>Ist die Abdichtung im Bad korrekt vorbereitet?</div>
      </li>
      <li>
        <div class="tl-icon"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--gold)" stroke-width="2.5" aria-hidden="true"><polyline points="20 6 9 17 4 12"/></svg></div>
        <div><strong>Elektroanschlüsse vor Trockenbau</strong>Sind Elektroanschlüsse vor Trockenbau und Fliesen geklärt?</div>
      </li>
      <li>
        <div class="tl-icon"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--gold)" stroke-width="2.5" aria-hidden="true"><polyline points="20 6 9 17 4 12"/></svg></div>
        <div><strong>Untergrund für Bodenbeläge</strong>Ist der Untergrund für Bodenbeläge geeignet?</div>
      </li>
      <li>
        <div class="tl-icon"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--gold)" stroke-width="2.5" aria-hidden="true"><polyline points="20 6 9 17 4 12"/></svg></div>
        <div><strong>Feuchtigkeit und Schadstoffe eingeordnet</strong>Sind Feuchtigkeit oder Schadstoffverdacht eingeordnet?</div>
      </li>
      <li>
        <div class="tl-icon"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--gold)" stroke-width="2.5" aria-hidden="true"><polyline points="20 6 9 17 4 12"/></svg></div>
        <div><strong>Maße für Einbauten abstimmen</strong>Stimmen Maße für Sanitärobjekte, Türen, Einbauten oder Küche?</div>
      </li>
      <li>
        <div class="tl-icon"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--gold)" stroke-width="2.5" aria-hidden="true"><polyline points="20 6 9 17 4 12"/></svg></div>
        <div><strong>Fachpartner über Änderungen informieren</strong>Sind Fachpartner über Änderungen informiert?</div>
      </li>
    </ul>

    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-top:24px;margin-bottom:20px">Bei SHK-Themen kommt die Meisterverantwortung im Bereich Heizung, Sanitär und Gebäudetechnik hinzu. Bei weiteren Gewerken koordiniert Radex qualifizierte Fachpartner und achtet darauf, dass die Arbeiten sinnvoll ineinandergreifen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine gute Bauleitung erkennt außerdem, wann eine Entscheidung getroffen werden muss. Viele Verzögerungen entstehen, weil Material, Ausstattung oder Detailfragen zu spät entschieden werden. Radex bereitet solche Punkte vor und stimmt sie mit dem Kunden ab.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Für eine Sanierung mit klarer Qualitätssicherung können Sie Radex unter <a href="tel:+496074960620">06074 960620</a> anrufen.</p>

  <div style="text-align:center;margin-top:40px;">
    <a href="https://wa.me/491744684189" class="btn-primary gold" target="_blank" rel="noopener">Angebot anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'ablauf-der-bauleitung-und-projektsteuerung-mit-radex',
    title: "Ablauf der Bauleitung und Projektsteuerung mit Radex",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">So läuft es ab</div>
  <h2>Ablauf der Bauleitung und Projektsteuerung mit Radex</h2>
  <p style="font-size:16px;color:var(--text-light);line-height:1.75;max-width:720px;margin-bottom:8px">Radex führt Bauleitung und Projektsteuerung in klaren Schritten. Der Ablauf wird je nach Projektgröße angepasst, bleibt aber grundsätzlich strukturiert.</p>

  <ol class="phase-list" style="max-width:800px">
    <li>
      <div>
        <strong>Ziel- und Projektklärung</strong>
        Am Anfang wird besprochen, was saniert werden soll: Bad, Wohnung, Haus, Altbau, Gewerbefläche, Teilsanierung, Komplettsanierung oder Kernsanierung. Auch Nutzung, Zeitrahmen, Budgetrahmen und Ziel der Sanierung werden eingeordnet.
      </div>
    </li>
    <li>
      <div>
        <strong>Bestandsaufnahme und Analyse</strong>
        Anschließend prüft Radex den betroffenen Bereich oder die gesamte Immobilie. Dabei werden Heizung, Sanitär, Leitungen, Innenausbau, Böden, Wände, Decken, Feuchtigkeit, mögliche Schadstoffe, Elektrokoordination und Raumaufteilung betrachtet. Aus dieser Bestandsaufnahme ergibt sich, welche Arbeiten notwendig sind, welche sinnvoll sind und welche optional bleiben können.
      </div>
    </li>
    <li>
      <div>
        <strong>Ablaufplanung und Reihenfolge der Gewerke</strong>
        Danach wird der Ablauf geplant. Die beteiligten Gewerke werden in eine sinnvolle Reihenfolge gebracht. Rückbau, Schadstoffprüfung, SHK, Elektrokoordination, Trockenbau, Abdichtung, Fliesen, Boden, Malerarbeiten und Endmontage werden aufeinander abgestimmt.
      </div>
    </li>
    <li>
      <div>
        <strong>Koordination während der Ausführung</strong>
        Während der Ausführung bleibt Radex Ansprechpartner, koordiniert Abläufe, klärt Rückfragen und reagiert auf Befunde im Bestand.
      </div>
    </li>
    <li>
      <div>
        <strong>Abnahme und Übergabe</strong>
        Am Ende wird geprüft, ob die vereinbarten Arbeiten abgeschlossen sind und ob offene Punkte dokumentiert werden müssen. Ziel ist eine saubere, nachvollziehbare Übergabe.
      </div>
    </li>
  </ol>

  <div class="info-box" style="margin-top:32px">
    Planen Sie eine Sanierung mit Bauleitung im Rhein-Main-Gebiet? Rufen Sie Radex unter <a href="tel:+496074960620">06074 960620</a> an oder senden Sie eine unverbindliche Anfrage über den <a href="/kontakt">Kontaktbogen</a>.
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="https://wa.me/491744684189" class="btn-primary gold" target="_blank" rel="noopener">Ablauf besprechen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'bauleitung-im-rhein-main-gebiet-regional-koordiniert-aus-roedermark',
    title: "Bauleitung im Rhein-Main-Gebiet – regional koordiniert aus Rödermark",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="section-label">Einsatzgebiet</div>
  <h2>Bauleitung im Rhein-Main-Gebiet – regional koordiniert aus Rödermark</h2>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex sitzt in Rödermark und begleitet Sanierungen im Rhein-Main-Gebiet. Die Region ist vielfältig: Eigentumswohnungen in städtischen Lagen, Häuser in gewachsenen Wohngebieten, hochwertige Bestandsimmobilien im Taunus, Gewerbeflächen in wirtschaftlich starken Standorten und modernisierungsbedürftige Wohnungen nach Kauf oder Mieterwechsel.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Diese Vielfalt macht Bauleitung besonders wichtig. Jede Immobilie bringt andere Anforderungen mit. Eine Wohnung in einem Mehrfamilienhaus braucht andere Logistik als ein freistehendes Haus. Eine Gewerbefläche braucht andere Zeitfenster als eine Badsanierung. Eine hochwertige Bestandsimmobilie braucht eine andere Material- und Detailabstimmung als eine wirtschaftliche Sanierung nach Mieterwechsel.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex plant nicht nach starren Paketen, sondern nach Objekt, Nutzung und Zustand. Trotzdem bleibt die Grundlogik gleich: Bestand verstehen, Umfang klären, Schnittstellen prüfen, Fachgewerke koordinieren und Qualität sichern.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex ist in über 60 Städten im Rhein-Main-Gebiet im Einsatz, darunter Frankfurt am Main, Offenbach, Darmstadt, Hanau, Rodgau, Heusenstamm, Obertshausen und Mühlheim am Main.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Wenn Sie eine Sanierung im Rhein-Main-Gebiet koordinieren lassen möchten, erreichen Sie Radex unter <a href="tel:+496074960620">06074 960620</a>.</p>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Beratung anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'warum-radex-fuer-bauleitung-und-projektsteuerung',
    title: "Warum Radex für Bauleitung und Projektsteuerung?",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Warum Radex</div>
  <h2>Warum Radex für Bauleitung und Projektsteuerung?</h2>
  <ul class="trust-list">
    <li>
      <div class="tl-icon"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--gold)" stroke-width="2.5" aria-hidden="true"><polyline points="20 6 9 17 4 12"/></svg></div>
      <div><strong>Fester Ansprechpartner statt Koordinationschaos</strong>Eine Sanierung braucht jemanden, der nicht nur einzelne Leistungen sieht, sondern das ganze Projekt versteht. Statt jedes Gewerk einzeln zu koordinieren, läuft die Abstimmung gebündelt über Radex.</div>
    </li>
    <li>
      <div class="tl-icon"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--gold)" stroke-width="2.5" aria-hidden="true"><polyline points="20 6 9 17 4 12"/></svg></div>
      <div><strong>SHK-Meisterkompetenz im Kernbereich</strong>Radex verbindet regionale Nähe, SHK-Meisterkompetenz, Erfahrung mit Bestandsimmobilien, koordinierte Fachpartner und klare Kommunikation. Heizung, Sanitär und Gebäudetechnik werden unter SHK-Meisterverantwortung geführt.</div>
    </li>
    <li>
      <div class="tl-icon"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--gold)" stroke-width="2.5" aria-hidden="true"><polyline points="20 6 9 17 4 12"/></svg></div>
      <div><strong>Erfahrung mit Bestand und seinen Besonderheiten</strong>Alte Leitungen, Feuchtigkeit, Schadstoffe, unklare Wandaufbauten, frühere Umbauten und technische Schnittstellen können den Ablauf beeinflussen. Radex kennt solche Situationen und kann sie in die Projektsteuerung integrieren.</div>
    </li>
    <li>
      <div class="tl-icon"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--gold)" stroke-width="2.5" aria-hidden="true"><polyline points="20 6 9 17 4 12"/></svg></div>
      <div><strong>Zertifiziert für Schimmel- und Asbestsanierung</strong>Radex ist zertifiziert für Schimmel- und Asbestsanierung und verfügt über Sachkunde nach TRGS 519. Das ist besonders wichtig, wenn vor oder während Rückbauarbeiten Verdachtsfälle auftreten.</div>
    </li>
    <li>
      <div class="tl-icon"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--gold)" stroke-width="2.5" aria-hidden="true"><polyline points="20 6 9 17 4 12"/></svg></div>
      <div><strong>Für alle Projektgrößen und Nutzungsarten</strong>Ob Badsanierung, Wohnungssanierung, Haussanierung, Komplettsanierung oder Gewerbesanierung – Radex passt den Leistungsumfang an Objekt, Nutzung und Zustand an. Rufen Sie unter <a href="tel:+496074960620">06074 960620</a> an oder senden Sie eine unverbindliche Anfrage über den <a href="/kontakt">Kontaktbogen</a>.</div>
    </li>
  </ul>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Unverbindlich anfragen</a>
  </div>
</div>` }}
      />
    ),
  }
];
