/* Auto-generated by scripts/build-elektroinstallation-legacy.mjs – do not edit by hand. */
/* eslint-disable react/no-danger */

export const elektroinstallationLegacySections = [
  {
    id: 'elektrokoordination-bei-sanierungen',
    title: "Elektrokoordination bei Sanierungen",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="intro-section">
  <div class="intro-text">
    <div class="section-label">Elektrokoordination bei Sanierungen</div>
    <p style="font-size:17px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine moderne Elektroinstallation ist ein zentraler Bestandteil jeder Sanierung. Sie entscheidet darüber, ob ein Haus, eine Wohnung, ein Bad, eine Küche, ein Büro oder eine Gewerbefläche im Alltag wirklich funktioniert. Licht, Steckdosen, Sicherungskasten, Stromkreise, Netzwerk, Küche, Badtechnik, Lüftung, Smart-Home-Vorbereitung, Homeoffice, Außenbereiche, Ladeinfrastruktur und Gebäudetechnik müssen früh geplant werden. Wer Elektro erst dann berücksichtigt, wenn Wände geschlossen, Fliesen gesetzt oder Böden verlegt sind, riskiert unnötige Nacharbeiten.</p>
    <p style="font-size:17px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Die Radex Objektmanagement GmbH aus Rödermark begleitet Sanierungen im Rhein-Main-Gebiet mit gewerkeübergreifender Koordination. Elektroarbeiten werden dabei durch qualifizierte Elektrofachbetriebe ausgeführt und von Radex in den Sanierungsablauf eingebunden. Radex selbst ist im Bereich Heizung, Sanitär und Gebäudetechnik SHK-meistergeführt durch Bernd Knoop, SHK-Meister und Betriebsleiter. Weitere Gewerke wie Elektrotechnik, Trockenbau, Fliesen, Bodenverlegung, Malerarbeiten, Innenausbau, Dämmung oder Schadstoffsanierung werden durch qualifizierte Fachpartner umgesetzt und von Radex koordiniert.</p>
    <p style="font-size:17px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Gerade bei Sanierungen im Bestand ist Elektrokoordination besonders wichtig. Viele Immobilien wurden zu einer Zeit geplant, in der der elektrische Bedarf deutlich geringer war. Heute brauchen Eigentümer mehr Steckdosen, mehr Lichtpunkte, bessere Küchenanschlüsse, sichere Badtechnik, Netzwerk für Homeoffice, Ladevorbereitung, moderne Geräte, Lüfter, Spiegelbeleuchtung, Außenstrom, Rollladensteuerung und teilweise smarte Gebäudefunktionen. Eine alte Elektrostruktur passt oft nicht mehr zu dieser Nutzung.</p>

    <!-- INTERNE LINKS -->
    <div class="link-list">
      <a href="/altbau-elektrik-erneuern-rhein-main" class="link-pill">Altbau Elektrik erneuern</a>
      <a href="/sicherungskasten-erneuern-rhein-main" class="link-pill">Sicherungskasten erneuern</a>
      <a href="/badsanierung-rhein-main" class="link-pill">Badsanierung Rhein-Main</a>
      <a href="/wohnungssanierung-rhein-main" class="link-pill">Wohnungssanierung</a>
      <a href="/haussanierung-rhein-main" class="link-pill">Haussanierung</a>
      <a href="/komplettsanierung-rhein-main" class="link-pill">Komplettsanierung</a>
      <a href="/kernsanierung-rhein-main" class="link-pill">Kernsanierung</a>
      <a href="/generalunternehmer-rhein-main" class="link-pill">Generalunternehmer</a>
      <a href="/heizung-sanitaer-rhein-main" class="link-pill">Heizung &amp; Sanitär</a>
      <a href="/heizungsmodernisierung-rhein-main" class="link-pill">Heizungsmodernisierung</a>
      <a href="/waermepumpe-rhein-main" class="link-pill">Wärmepumpe Rhein-Main</a>
      <a href="/sanitaerinstallation-rhein-main" class="link-pill">Sanitärinstallation</a>
      <a href="/energetische-sanierung-rhein-main" class="link-pill">Energetische Sanierung</a>
      <a href="/schadstoffsanierung-rhein-main" class="link-pill">Schadstoffsanierung</a>
      <a href="/gewerbesanierung-rhein-main" class="link-pill">Gewerbesanierung</a>
      <a href="/bueroumbau-rhein-main" class="link-pill">Büroumbau</a>
      <a href="/mieterausbau-rhein-main" class="link-pill">Mieterausbau</a>
      <a href="/kontakt" class="link-pill">Kontakt</a>
      <a href="/einsatzgebiete-rhein-main" class="link-pill">Einsatzgebiete</a>
    </div>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'warum-elektroinstallation-bei-sanierungen-frueh-geplant-werden-muss',
    title: "Warum Elektroinstallation bei Sanierungen früh geplant werden muss",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <h2>Warum Elektroinstallation bei Sanierungen früh geplant werden muss</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Elektroinstallation gehört zu den Gewerken, die später oft nicht sichtbar sind, aber täglich genutzt werden. Leitungen liegen in Wänden, Decken oder Böden. Stromkreise werden im Sicherungskasten geführt. Steckdosen, Schalter, Lichtanschlüsse, Netzwerkdosen, Küchenanschlüsse und Badtechnik müssen an den richtigen Stellen sitzen. Wenn diese Planung zu spät erfolgt, wird eine Sanierung unnötig kompliziert.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bei einer Sanierung müssen viele Entscheidungen aufeinander abgestimmt werden. Eine neue Küche braucht eigene Stromkreise für Kochfeld, Backofen, Spülmaschine, Kühlschrank, Dunstabzug, Arbeitsflächensteckdosen und Beleuchtung. Ein Bad braucht geschützte Elektrobereiche, Spiegelanschlüsse, Lüfter, Beleuchtung, Steckdosen und eventuell elektrische Zusatzfunktionen. Ein Homeoffice braucht Netzwerk, ausreichend Steckdosen und gute Beleuchtung. Eine neue Raumaufteilung braucht neue Lichtpunkte, Schalter und Leitungsführung. Eine Wärmepumpe, Wallbox oder moderne Gebäudetechnik kann zusätzliche elektrische Anforderungen stellen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:16px">Typische Fragen vor einer Sanierung sind:</p>
    <ul style="font-size:16px;color:var(--text-light);line-height:1.75;margin:0 0 20px;padding-left:20px">
      <li>Reicht der vorhandene Sicherungskasten noch aus?</li>
      <li>Sind genügend Stromkreise vorhanden?</li>
      <li>Gibt es ausreichend Steckdosen in den richtigen Bereichen?</li>
      <li>Sind Küche, Bad und Homeoffice technisch passend vorbereitet?</li>
      <li>Müssen Leitungen erneuert oder ergänzt werden?</li>
      <li>Sind Badbereiche sicher und fachgerecht planbar?</li>
      <li>Soll Netzwerk oder Smart-Home-Vorbereitung eingebunden werden?</li>
      <li>Gibt es Ladevorbereitung für E-Mobilität?</li>
      <li>Müssen Rollläden, Außenbereiche oder Beleuchtung ergänzt werden?</li>
      <li>Sind alte Elektroinstallationen noch zeitgemäß?</li>
    </ul>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex bindet Elektrofachpartner früh in den Ablauf ein. Das ist besonders wichtig, weil Elektroarbeiten vor Trockenbau, Fliesen, Spachtelarbeiten, Malerarbeiten und Bodenverlegung abgeschlossen oder zumindest vorbereitet sein müssen. Wenn Steckdosen oder Lichtanschlüsse erst nachträglich ergänzt werden, müssen fertige Oberflächen wieder geöffnet werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine gute Elektroplanung bedeutet nicht, wahllos überall Steckdosen zu setzen. Sie bedeutet, den späteren Alltag zu verstehen. Wo wird gearbeitet? Wo stehen Möbel? Wo kommt die Küche hin? Wie wird das Bad genutzt? Wo werden Geräte geladen? Welche Räume brauchen Netzwerk? Welche Beleuchtung soll entstehen? Welche Technik ist heute nötig und welche Vorbereitung ist für später sinnvoll?</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Radex koordiniert diese Fragen im Rahmen der Sanierung. Die Elektroarbeiten selbst werden durch qualifizierte Elektrofachbetriebe ausgeführt.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="https://wa.me/491744684189" class="btn-primary gold" target="_blank" rel="noopener">Jetzt per WhatsApp anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'elektroinstallation-bei-badsanierung',
    title: "Elektroinstallation bei Badsanierung",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <h2>Elektroinstallation bei Badsanierung</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Das Badezimmer stellt besonders hohe Anforderungen an Elektroplanung. Wasser, Feuchtigkeit, Abdichtung, Sanitärinstallation, Lüftung, Heizung, Fliesen, Spiegel, Beleuchtung und Steckdosen müssen sicher und fachgerecht aufeinander abgestimmt werden. Gerade im Bad darf Elektro nicht improvisiert werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:16px">Bei einer <a href="/badsanierung-rhein-main">Badsanierung</a> sind typische Elektrothemen:</p>
    <ul style="font-size:16px;color:var(--text-light);line-height:1.75;margin:0 0 20px;padding-left:20px">
      <li>Lichtplanung für Decke, Spiegel und Dusche</li>
      <li>Steckdosen am Waschtisch</li>
      <li>Anschluss für Spiegelschrank oder Lichtspiegel</li>
      <li>Lüfter oder Abluftsteuerung</li>
      <li>elektrische Zusatzheizung oder Handtuchwärmer, falls geplant</li>
      <li>Anschluss für Dusch-WC oder Komforttechnik</li>
      <li>sichere Elektrobereiche im Nassraum</li>
      <li>Abstimmung mit Vorwandinstallation</li>
      <li>Elektrokoordination vor Fliesenarbeiten</li>
      <li>Schalterpositionen und Bedienkomfort</li>
    </ul>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine Badsanierung beginnt oft mit der Frage nach Dusche, WC, Waschtisch, Badewanne, Fliesen und Badmöbeln. Doch die Elektroplanung muss früh dazukommen. Der Spiegel braucht Strom. Der Lüfter muss richtig eingebunden werden. Steckdosen sollen praktisch erreichbar sein. Licht muss blendfrei, funktional und angenehm sein. Wenn eine bodengleiche Dusche geplant wird, müssen alle Gewerke exakt zusammenarbeiten.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex koordiniert Badsanierungen so, dass Elektrofachpartner, SHK-Leistungen, Trockenbau, Fliesen und Innenausbau zusammenpassen. Im Bereich Sanitär und Heizung bringt Radex eigene SHK-Meisterkompetenz ein. Elektroarbeiten werden durch qualifizierte Fachpartner ausgeführt. Dadurch entsteht ein Bad, das nicht nur optisch modern ist, sondern technisch sinnvoll funktioniert.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Besonders bei kleinen Bädern ist die Planung wichtig. Dort gibt es wenig Platz, aber viele Anforderungen. Waschtisch, Spiegel, Schalter, Steckdose, Lüfter, Tür, Dusche und Heizkörper dürfen sich nicht gegenseitig stören. Bei barrierearmen Bädern kommen Erreichbarkeit, Sicherheit, Beleuchtung und langfristige Nutzung hinzu.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Wer ein Bad im Rhein-Main-Gebiet saniert, sollte Elektrokoordination früh einplanen. So werden Licht, Steckdosen, Spiegel, Lüfter und Badtechnik nicht zum Nachtrag, sondern zum festen Bestandteil der Badplanung.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Unverbindlich anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'elektroinstallation-bei-kuechenmodernisierung',
    title: "Elektroinstallation bei Küchenmodernisierung",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <h2>Elektroinstallation bei Küchenmodernisierung</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Die Küche ist einer der elektrotechnisch anspruchsvollsten Räume in einer Immobilie. Moderne Küchen benötigen viele Anschlüsse, mehrere Stromkreise, gut platzierte Steckdosen, leistungsfähige Geräteanschlüsse, Beleuchtung und oft Netzwerk- oder Steuerungselemente. Wenn die Elektroinstallation nicht zur Küchenplanung passt, wird die Montage schwierig oder es entstehen Kompromisse.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:16px">Typische Elektrothemen in der Küche:</p>
    <ul style="font-size:16px;color:var(--text-light);line-height:1.75;margin:0 0 20px;padding-left:20px">
      <li>Kochfeldanschluss</li>
      <li>Backofenanschluss</li>
      <li>Dampfgarer oder Mikrowelle</li>
      <li>Spülmaschine</li>
      <li>Kühlschrank und Gefriergerät</li>
      <li>Dunstabzug oder Umluftsystem</li>
      <li>Steckdosen an der Arbeitsfläche</li>
      <li>Licht unter Oberschränken</li>
      <li>Beleuchtung von Kücheninsel oder Essbereich</li>
      <li>Anschlüsse für smarte Geräte</li>
      <li>separate Stromkreise für leistungsstarke Geräte</li>
      <li>Abstimmung mit Wasser- und Abwasseranschlüssen</li>
    </ul>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bei einer Küchenmodernisierung müssen Elektro und Sanitär gemeinsam geplant werden. Spüle, Geschirrspüler, Kochfeld, Backofen, Kühlschrank, Steckdosen, Licht, Arbeitsfläche und Küchenmöbel hängen eng zusammen. Wenn Wasseranschlüsse, Steckdosen und Gerätepositionen nicht abgestimmt sind, muss später nachgearbeitet werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex koordiniert Küchenvorbereitung im Rahmen von <a href="/wohnungssanierung-rhein-main">Wohnungssanierungen</a>, <a href="/haussanierung-rhein-main">Haussanierungen</a> und <a href="/komplettsanierung-rhein-main">Komplettsanierungen</a>. Sanitäranschlüsse werden unter SHK-Meisterverantwortung betrachtet, Elektroarbeiten über qualifizierte Fachpartner eingebunden. Dadurch entstehen weniger Schnittstellenprobleme zwischen Küchenplanung, Sanitär, Elektro, Innenausbau und Oberflächen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Gerade vor dem Einzug ist die Küche ein entscheidender Bereich. Käufer möchten nach der Sanierung nicht feststellen, dass Steckdosen fehlen, Lichtanschlüsse falsch sitzen oder der Geräteanschluss nicht zur geplanten Küche passt. Deshalb sollte die Küchenplanung möglichst früh mit der Elektrokoordination verbunden werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Eine gute Elektroinstallation in der Küche bedeutet Alltagstauglichkeit. Geräte funktionieren zuverlässig, Arbeitsflächen sind gut beleuchtet, Steckdosen sitzen dort, wo sie gebraucht werden, und die Küche wirkt nicht durch sichtbare Kabel oder provisorische Lösungen beeinträchtigt.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Beratungsgespräch vereinbaren</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'elektroinstallation-bei-wohnungssanierung',
    title: "Elektroinstallation bei Wohnungssanierung",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <h2>Elektroinstallation bei Wohnungssanierung</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bei einer Wohnungssanierung sollte die Elektroinstallation früh geprüft werden. Viele Wohnungen haben zu wenige Steckdosen, ungünstige Lichtpunkte, alte Leitungen, unzureichende Küchenanschlüsse oder keine passende Vorbereitung für Homeoffice, Netzwerk oder moderne Geräte. Gerade wenn eine Wohnung vor dem Einzug, nach Kauf oder nach Mieterwechsel saniert wird, ist der richtige Zeitpunkt, diese Themen zu klären.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:16px">Typische Elektrothemen bei Wohnungssanierung:</p>
    <ul style="font-size:16px;color:var(--text-light);line-height:1.75;margin:0 0 20px;padding-left:20px">
      <li>Steckdosen in Wohnräumen ergänzen</li>
      <li>Lichtschalter und Lichtpunkte neu planen</li>
      <li>Küche elektrotechnisch vorbereiten</li>
      <li>Badtechnik mit Elektrofachpartner abstimmen</li>
      <li>Netzwerkanschlüsse für Homeoffice</li>
      <li>Sicherungskasten prüfen</li>
      <li>alte Leitungen bewerten</li>
      <li>Stromkreise an moderne Nutzung anpassen</li>
      <li>Waschmaschine, Trockner oder Hauswirtschaftsbereich einplanen</li>
      <li>elektrische Rollläden oder Steuerungen vorbereiten</li>
      <li>Beleuchtung für Flur, Küche, Bad und Wohnbereich abstimmen</li>
    </ul>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">In Mehrfamilienhäusern kommen organisatorische Punkte hinzu. Hausverwaltung, Eigentümergemeinschaft, gemeinschaftliche Leitungen, Bauzeiten, Treppenhaus, Nachbarn und Zugänge können relevant sein. Elektroarbeiten müssen so geplant werden, dass sie in den Ablauf der Wohnungssanierung passen und nicht nach fertigen Oberflächen stattfinden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Für Eigennutzer ist die Elektroplanung besonders wichtig, weil sie direkt den Alltag betrifft. Wo steht der Schreibtisch? Wo wird geladen? Wo kommt der Fernseher hin? Wo sollen Lampen sitzen? Welche Geräte brauchen eigene Anschlüsse? Wie soll das Bad beleuchtet werden? Wo wird die Küche geplant?</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Für Vermieter und Hausverwaltungen zählt zusätzlich die Wirtschaftlichkeit. Eine Wohnung soll modern, sicher und gut nutzbar sein, aber die Ausstattung muss zum Objekt und zur Zielgruppe passen. Radex hilft, den Umfang objektbezogen einzuordnen und die Elektrofachpartner passend einzubinden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Eine Wohnungssanierung ohne Elektroprüfung kann später ärgerlich werden. Neue Böden, glatte Wände und ein modernes Bad nützen wenig, wenn Steckdosen fehlen oder die Küche technisch nicht vorbereitet ist.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="https://wa.me/491744684189" class="btn-primary gold" target="_blank" rel="noopener">Angebot anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'elektroinstallation-bei-haussanierung',
    title: "Elektroinstallation bei Haussanierung",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <h2>Elektroinstallation bei Haussanierung</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bei einer Haussanierung ist Elektroinstallation ein besonders wichtiger Bestandteil. Ein Haus hat mehr Räume, mehr Nutzungssituationen und mehr technische Anforderungen als eine einzelne Wohnung. Küche, Bad, Gäste-WC, Wohnzimmer, Schlafzimmer, Kinderzimmer, Homeoffice, Keller, Dachgeschoss, Außenbereich, Garage, Garten, Heizung, Wärmepumpe, Netzwerk, Beleuchtung und Ladeinfrastruktur müssen zusammen betrachtet werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:16px">Typische Elektrothemen bei Haussanierung:</p>
    <ul style="font-size:16px;color:var(--text-light);line-height:1.75;margin:0 0 20px;padding-left:20px">
      <li>Sicherungskasten prüfen oder erneuern</li>
      <li>Stromkreise neu planen</li>
      <li>Steckdosen in allen Wohnbereichen ergänzen</li>
      <li>Küche und Bad vorbereiten</li>
      <li>Netzwerk für Homeoffice und Medien</li>
      <li>Außensteckdosen und Gartenbereiche</li>
      <li>Beleuchtung innen und außen</li>
      <li>Rollladensteuerung oder Smart-Home-Vorbereitung</li>
      <li>Anschlüsse für Wärmepumpe oder Heiztechnik</li>
      <li>Wallbox-Vorbereitung</li>
      <li>Keller, Hauswirtschaftsraum und Technikraum</li>
      <li>Elektrokoordination mit Innenausbau und Trockenbau</li>
    </ul>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bei Häusern im Bestand ist die Elektrostruktur oft über Jahrzehnte gewachsen. Einzelne Räume wurden ergänzt, aber das Gesamtsystem wurde nicht neu gedacht. Es gibt zu wenige Steckdosen, alte Leitungen, unübersichtliche Stromkreise oder einen Sicherungskasten, der nicht mehr zum heutigen Bedarf passt. Bei einer <a href="/haussanierung-rhein-main">Haussanierung</a> sollte deshalb geprüft werden, ob punktuelle Ergänzungen reichen oder ob eine umfassendere Erneuerung sinnvoll ist.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex koordiniert die Elektrofachpartner im Rahmen der Haussanierung. Dabei wird Elektro mit Heizung, Sanitär, Innenausbau, Böden, Wänden, Decken und energetischen Maßnahmen abgestimmt. Wenn ein Haus vor dem Einzug saniert wird, lassen sich Elektroarbeiten besonders gut umsetzen. Wenn das Haus bewohnt bleibt, muss in Abschnitten geplant werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Eine gute Elektroplanung verbessert nicht nur Sicherheit und Funktion, sondern auch Wohnqualität. Gut platzierte Steckdosen, sinnvolle Lichtschaltungen, ausreichend Netzwerk, vorbereitete Technik und saubere Leitungsführung machen den Alltag deutlich angenehmer.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Kostenlos beraten lassen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'altbau-elektrik-erneuern-besondere-anforderungen-im-bestand',
    title: "Altbau Elektrik erneuern – besondere Anforderungen im Bestand",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <h2><a href="/altbau-elektrik-erneuern-rhein-main">Altbau Elektrik erneuern</a> – besondere Anforderungen im Bestand</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">In älteren Immobilien ist Elektroinstallation ein besonders sensibles Thema. Alte Leitungen, veraltete Sicherungen, fehlende Schutzschalter, zu wenige Stromkreise oder improvisierte Ergänzungen können bei einer Sanierung sichtbar werden. Eine Altbauwohnung oder ein älteres Haus muss deshalb nicht schlecht sein. Viele Bestandsimmobilien haben gute Substanz und gewachsene Qualität. Aber die Elektrostruktur sollte fachlich geprüft werden, bevor neue Oberflächen aufgebaut werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:16px">Typische Hinweise, dass eine Prüfung sinnvoll ist:</p>
    <ul style="font-size:16px;color:var(--text-light);line-height:1.75;margin:0 0 20px;padding-left:20px">
      <li>sehr wenige Steckdosen</li>
      <li>alte Schalter und Sicherungen</li>
      <li>unklare Leitungsführung</li>
      <li>häufig auslösende Sicherungen</li>
      <li>Küche nicht für moderne Geräte vorbereitet</li>
      <li>Bad ohne zeitgemäße Elektroplanung</li>
      <li>kein ausreichendes Netzwerk oder Homeoffice-Anschluss</li>
      <li>alte Unterverteilung</li>
      <li>frühere Umbauten ohne klare Dokumentation</li>
      <li>Sanierung nach Kauf oder Erbschaft</li>
    </ul>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex koordiniert bei Altbausanierungen die erforderlichen Elektrofachpartner und bindet die Elektroarbeiten in den Gesamtprozess ein. Wenn Wände, Böden oder Decken ohnehin geöffnet werden, ist der richtige Zeitpunkt, Leitungen, Stromkreise und Sicherungskasten fachlich zu prüfen. Später werden Änderungen deutlich aufwendiger.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bei Altbauten können zusätzlich Schadstoffthemen relevant sein. Alte Bodenbeläge, Kleber, Rohrisolierungen oder Deckenmaterialien sollten bei Verdacht fachlich eingeordnet werden. Radex ist zertifiziert für Schimmel- und Asbestsanierung und verfügt über Sachkunde nach TRGS 519. Dadurch können solche Themen in den Sanierungsablauf integriert werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Elektroarbeiten im Altbau sollten nicht isoliert geplant werden. Sie hängen mit Trockenbau, Innenausbau, Malerarbeiten, Böden, Küche, Bad, Heizung und Sanitär zusammen. Radex sorgt dafür, dass diese Schnittstellen früh geklärt werden.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="https://wa.me/491744684189" class="btn-primary gold" target="_blank" rel="noopener">Jetzt per WhatsApp anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'sicherungskasten-und-unterverteilung-pruefen',
    title: "Sicherungskasten und Unterverteilung prüfen",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <h2><a href="/sicherungskasten-erneuern-rhein-main">Sicherungskasten und Unterverteilung prüfen</a></h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Der Sicherungskasten ist die zentrale Stelle der Elektroinstallation. Bei vielen Sanierungen sollte geprüft werden, ob die vorhandene Unterverteilung noch zu den heutigen Anforderungen passt. Moderne Küchen, Bäder, Wärmepumpen, Wallboxen, Homeoffice, Netzwerktechnik und zusätzliche Stromkreise können eine ältere Elektrostruktur schnell an Grenzen bringen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:16px">Typische Gründe für eine Prüfung:</p>
    <ul style="font-size:16px;color:var(--text-light);line-height:1.75;margin:0 0 20px;padding-left:20px">
      <li>Sanierung einer älteren Wohnung</li>
      <li>Haussanierung oder <a href="/kernsanierung-rhein-main">Kernsanierung</a></li>
      <li>neue Küche mit leistungsstarken Geräten</li>
      <li>Badsanierung mit moderner Technik</li>
      <li>Wärmepumpe oder Heizungsmodernisierung</li>
      <li>Wallbox-Vorbereitung</li>
      <li>häufig auslösende Sicherungen</li>
      <li>unübersichtliche Stromkreise</li>
      <li>fehlende Reserve für Erweiterungen</li>
      <li>alte Unterverteilung</li>
    </ul>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Ob ein Sicherungskasten erneuert, erweitert oder angepasst werden muss, entscheiden qualifizierte Elektrofachbetriebe. Radex koordiniert diese Prüfung im Rahmen der Sanierung. Wichtig ist, dass diese Frage früh geklärt wird. Wenn neue Leitungen, Steckdosen oder Geräte geplant werden, muss die Verteilung dazu passen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bei Wohnungen in Mehrfamilienhäusern müssen manchmal Hausanschluss, Zählerplatz, Gemeinschaftsbereiche oder Hausverwaltung berücksichtigt werden. Bei Häusern können zusätzlich Technikraum, Wärmepumpe, Außenbereich, Garage oder Wallbox relevant sein. Radex sorgt dafür, dass diese Punkte in der Projektsteuerung berücksichtigt werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Eine moderne Unterverteilung schafft nicht nur technische Sicherheit, sondern auch bessere Erweiterbarkeit. Wer heute saniert, sollte nicht nur den aktuellen Bedarf sehen, sondern auch mögliche spätere Anforderungen einplanen.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Unverbindlich anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'netzwerk-homeoffice-und-moderne-mediennutzung',
    title: "Netzwerk, Homeoffice und moderne Mediennutzung",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <h2>Netzwerk, Homeoffice und moderne Mediennutzung</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Homeoffice, Streaming, Smart-TV, Netzwerkspeicher, WLAN, Videokonferenzen, Drucker, Sicherheitstechnik und smarte Geräte haben die Anforderungen an Wohn- und Gewerberäume verändert. Eine moderne Sanierung sollte deshalb nicht nur Strom, sondern auch Daten und Netzwerk berücksichtigen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Viele Eigentümer verlassen sich ausschließlich auf WLAN. Das kann funktionieren, ist aber nicht immer stabil genug. Gerade bei größeren Häusern, mehreren Etagen, dicken Wänden oder Homeoffice-Arbeitsplätzen kann eine feste Netzwerkstruktur sinnvoll sein. Sie bietet Stabilität, bessere Geschwindigkeit und mehr Flexibilität.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:16px">Typische Themen:</p>
    <ul style="font-size:16px;color:var(--text-light);line-height:1.75;margin:0 0 20px;padding-left:20px">
      <li>Netzwerkanschlüsse für Homeoffice</li>
      <li>Medienanschlüsse im Wohnzimmer</li>
      <li>stabile Verbindung in mehreren Etagen</li>
      <li>Access-Point-Vorbereitung</li>
      <li>Technikstandort oder Netzwerkschrank</li>
      <li>Leitungsführung bei Sanierung</li>
      <li>Kombination mit Elektroinstallation</li>
      <li>Vorbereitung für Smart-Home-Funktionen</li>
      <li>Netzwerk in Büro- oder Gewerbeflächen</li>
    </ul>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bei einer Wohnungssanierung kann schon eine gute Planung einzelner Netzwerkpunkte viel verbessern. Bei einer Haussanierung lassen sich Leitungen in mehreren Etagen besser vorbereiten, wenn Wände oder Decken ohnehin bearbeitet werden. Bei Gewerbeflächen sind Netzwerk und Datentechnik oft entscheidend für die spätere Nutzung.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Radex koordiniert solche Anforderungen mit Elektrofachpartnern und Innenausbau. Dadurch werden Datenleitungen, Steckdosen, Licht, Möbelpositionen und Nutzung gemeinsam geplant.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Beratungsgespräch vereinbaren</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'smart-home-beleuchtung-und-komfortfunktionen',
    title: "Smart Home, Beleuchtung und Komfortfunktionen",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <h2>Smart Home, Beleuchtung und Komfortfunktionen</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Smart Home ist bei Sanierungen kein Muss, aber für viele Eigentümer interessant. Dabei geht es nicht nur um Technikspielerei, sondern um Komfort, Steuerung und Vorbereitung. Licht, Rollläden, Heizung, Lüftung, Sicherheit, Beschattung und einzelne Geräte können je nach System sinnvoll miteinander verbunden werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Wichtig ist, Smart Home früh zu planen. Spätere Nachrüstung ist möglich, aber oft aufwendiger. Bei einer Sanierung können Leitungen, Schalter, Steuerungen und Technikstandorte besser vorbereitet werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:16px">Typische Komfortthemen:</p>
    <ul style="font-size:16px;color:var(--text-light);line-height:1.75;margin:0 0 20px;padding-left:20px">
      <li>Lichtsteuerung</li>
      <li>Rollladen- oder Jalousiesteuerung</li>
      <li>Heizungs- und Raumtemperatursteuerung</li>
      <li>Bewegungsmelder</li>
      <li>Außenbeleuchtung</li>
      <li>Sicherheitsfunktionen</li>
      <li>smarte Steckdosen oder Szenen</li>
      <li>Vorbereitung für spätere Erweiterungen</li>
    </ul>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Auch klassische Beleuchtung sollte sorgfältig geplant werden. Gute Lichtplanung verbessert Räume deutlich. Küche, Bad, Flur, Wohnbereich, Treppe, Homeoffice, Schlafzimmer, Keller und Außenbereich brauchen unterschiedliche Lichtlösungen. Ein einzelner Deckenanschluss reicht oft nicht aus, um moderne Räume gut zu beleuchten.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Radex koordiniert Beleuchtung, Schalterpositionen und Smart-Home-Vorbereitung mit Elektrofachpartnern im Rahmen der Sanierung. Dabei geht es nicht darum, unnötig komplizierte Technik einzubauen. Ziel ist eine Lösung, die zum Alltag passt und später nutzbar bleibt.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="https://wa.me/491744684189" class="btn-primary gold" target="_blank" rel="noopener">Angebot anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'elektroinstallation-bei-waermepumpe-und-heizungsmodernisierung',
    title: "Elektroinstallation bei Wärmepumpe und Heizungsmodernisierung",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <h2>Elektroinstallation bei Wärmepumpe und Heizungsmodernisierung</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine Heizungsmodernisierung kann Elektroarbeiten erforderlich machen. Besonders bei Wärmepumpen, Steuerungen, Pumpen, Regeltechnik, Außeneinheiten oder zusätzlichen Komponenten muss die Elektroinstallation früh abgestimmt werden. Auch wenn Radex im Bereich <a href="/heizung-sanitaer-rhein-main">Heizung und Sanitär</a> SHK-meistergeführt arbeitet, werden Elektroarbeiten durch qualifizierte Elektrofachpartner ausgeführt und koordiniert.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:16px">Typische Schnittstellen zwischen Heizung und Elektro:</p>
    <ul style="font-size:16px;color:var(--text-light);line-height:1.75;margin:0 0 20px;padding-left:20px">
      <li>Stromversorgung für Wärmepumpe</li>
      <li>Steuerung und Regeltechnik</li>
      <li>Außeneinheit und Inneneinheit</li>
      <li>Heizungsraum oder Technikraum</li>
      <li>Sicherungskasten und Stromkreise</li>
      <li>mögliche Zähler- oder Anschlussfragen</li>
      <li>Leitungsführung</li>
      <li>Abstimmung mit <a href="/heizungsmodernisierung-rhein-main">Heizungsmodernisierung</a></li>
      <li>Elektrokoordination bei energetischer Sanierung</li>
    </ul>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine <a href="/waermepumpe-rhein-main">Wärmepumpe</a> sollte nicht geplant werden, ohne Elektroanschluss, Aufstellort und technische Voraussetzungen zu berücksichtigen. Bei einer Haussanierung oder <a href="/komplettsanierung-rhein-main">Komplettsanierung</a> lassen sich diese Punkte besonders gut vorbereiten, weil Räume, Wände oder Technikbereiche ohnehin bearbeitet werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Radex sorgt dafür, dass SHK-Planung und Elektrofachpartner zusammenarbeiten. Dadurch wird die Heizungsmodernisierung nicht isoliert betrachtet, sondern mit der elektrischen Infrastruktur abgestimmt.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Kostenlos beraten lassen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'elektroinstallation-bei-gewerbe-buero-praxis-und-mieterausbau',
    title: "Elektroinstallation bei Gewerbe, Büro, Praxis und Mieterausbau",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <h2>Elektroinstallation bei Gewerbe, Büro, Praxis und Mieterausbau</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Gewerbliche Elektroinstallation muss zur Nutzung passen. Ein Büro braucht andere Anforderungen als eine Praxis, eine Ladenfläche, ein Mieterausbau oder eine Dienstleistungsfläche. Arbeitsplätze, Besprechungsräume, Empfang, Teeküche, Sanitärbereiche, Datentechnik, Beleuchtung, Sicherheit, Beschilderung, Geräte und Kundenbereiche müssen sinnvoll geplant werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex koordiniert Elektrofachpartner bei <a href="/gewerbesanierung-rhein-main">Gewerbesanierungen</a>, <a href="/bueroumbau-rhein-main">Büroumbau</a>, Praxismodernisierung, Ladenumbau und <a href="/mieterausbau-rhein-main">Mieterausbau</a>. Dabei wird Elektro mit Trockenbau, Innenausbau, Sanitärbereichen, Bodenbelägen, Malerarbeiten und Übergabe abgestimmt.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:16px">Typische Themen:</p>
    <ul style="font-size:16px;color:var(--text-light);line-height:1.75;margin:0 0 20px;padding-left:20px">
      <li>Steckdosen für Arbeitsplätze</li>
      <li>Datentechnik und Netzwerk</li>
      <li>Beleuchtung für Büro, Praxis oder Laden</li>
      <li>Teeküche und Geräteanschlüsse</li>
      <li>Sanitärbereiche</li>
      <li>Empfang und Kundenbereiche</li>
      <li>Besprechungsräume</li>
      <li>Trockenbau und neue Raumaufteilung</li>
      <li>Zeitplan und Übergabe</li>
      <li>Abstimmung mit Mieter oder Eigentümer</li>
    </ul>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bei Gewerbeprojekten ist der Zeitplan oft besonders wichtig. Eine Fläche soll übergeben werden, ein neuer Mieter möchte einziehen oder ein Betrieb soll möglichst wenig gestört werden. Deshalb müssen Elektroarbeiten früh eingeplant werden. Wenn Trockenbau, Malerarbeiten oder Bodenbeläge fertig sind, ist eine nachträgliche Elektroänderung unnötig aufwendig.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Radex übernimmt die Projektsteuerung und sorgt dafür, dass Elektrofachpartner rechtzeitig eingebunden werden.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="https://wa.me/491744684189" class="btn-primary gold" target="_blank" rel="noopener">Jetzt per WhatsApp anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'elektroinstallation-bei-komplettsanierung-und-kernsanierung',
    title: "Elektroinstallation bei Komplettsanierung und Kernsanierung",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <h2>Elektroinstallation bei Komplettsanierung und Kernsanierung</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bei <a href="/komplettsanierung-rhein-main">Komplettsanierung</a> und <a href="/kernsanierung-rhein-main">Kernsanierung</a> ist Elektroinstallation einer der wichtigsten technischen Bereiche. Wenn eine Immobilie umfassend modernisiert oder tiefgreifend zurückgebaut wird, sollte die Elektrostruktur grundsätzlich geprüft werden. Gerade bei älteren Gebäuden ist es häufig sinnvoll, Leitungen, Sicherungskasten, Stromkreise, Steckdosen, Licht, Küche, Bad und Netzwerk neu zu planen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:16px">Bei einer Komplettsanierung können viele Bereiche betroffen sein:</p>
    <ul style="font-size:16px;color:var(--text-light);line-height:1.75;margin:0 0 20px;padding-left:20px">
      <li>Bad und Küche</li>
      <li>Wohnräume und Schlafräume</li>
      <li>Flur und Treppenhaus</li>
      <li>Keller und Technikraum</li>
      <li>Heizungsraum</li>
      <li>Außenbereich</li>
      <li>Homeoffice</li>
      <li>Netzwerk und Medien</li>
      <li>Sicherungskasten</li>
      <li>Smart-Home-Vorbereitung</li>
    </ul>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bei einer Kernsanierung geht der Eingriff tiefer. Wände, Böden und Decken werden häufig geöffnet. Das ist eine gute Gelegenheit, Elektroinstallation umfassend neu zu denken. Wenn später alles fertig ist, sind Änderungen deutlich schwieriger.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex koordiniert Elektrofachpartner innerhalb des Gesamtprojekts. Rückbau, Schadstoffprüfung, SHK-Arbeiten, Innenausbau, Trockenbau, Fliesen, Boden und Malerarbeiten werden in eine sinnvolle Reihenfolge gebracht. Elektro gehört dabei in die frühe technische Phase.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Gerade bei Kernsanierungen können Schadstoffthemen auftreten. Wenn alte Bodenbeläge, Kleber, Deckenmaterialien oder Dämmstoffe sichtbar werden, sollte bei Verdacht fachlich geprüft werden. Radex ist zertifiziert für Schimmel- und Asbestsanierung und kann solche Themen in den Sanierungsablauf integrieren.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Unverbindlich anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'ablauf-der-elektrokoordination-mit-radex',
    title: "Ablauf der Elektrokoordination mit Radex",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <h2>Ablauf der Elektrokoordination mit Radex</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex koordiniert Elektroinstallation als Teil der Sanierung in einem klaren Ablauf. Die Elektroarbeiten selbst werden durch qualifizierte Elektrofachbetriebe ausgeführt.</p>

    <h3 style="color:var(--navy);font-size:17px;margin:24px 0 8px">Erstes Gespräch</h3>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Am Anfang wird geklärt, worum es geht: Badsanierung, Wohnungssanierung, Haussanierung, Küche, Altbau, Sicherungskasten, Wärmepumpe, Gewerbeumbau oder Komplettsanierung.</p>

    <h3 style="color:var(--navy);font-size:17px;margin:0 0 8px">Bestandsaufnahme</h3>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex prüft mit Blick auf den Sanierungsumfang, welche Elektrothemen relevant sind. Dazu gehören Steckdosen, Licht, Küche, Bad, Sicherungskasten, Netzwerk, Heiztechnik, Außenbereich und mögliche Erweiterungen.</p>

    <h3 style="color:var(--navy);font-size:17px;margin:0 0 8px">Fachpartner einbinden</h3>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Qualifizierte Elektrofachpartner werden rechtzeitig eingebunden, damit technische Anforderungen fachgerecht bewertet werden.</p>

    <h3 style="color:var(--navy);font-size:17px;margin:0 0 8px">Schnittstellen planen</h3>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Elektro wird mit SHK, Trockenbau, Fliesen, Innenausbau, Küche, Böden, Malerarbeiten und energetischen Maßnahmen abgestimmt.</p>

    <h3 style="color:var(--navy);font-size:17px;margin:0 0 8px">Ausführung koordinieren</h3>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Elektroarbeiten erfolgen in der passenden Reihenfolge, bevor Wände geschlossen, Fliesen gesetzt oder Oberflächen fertiggestellt werden.</p>

    <h3 style="color:var(--navy);font-size:17px;margin:0 0 8px">Übergabe</h3>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Zum Abschluss werden die Sanierungsleistungen geordnet übergeben. Ziel ist eine Elektroinstallation, die fachgerecht ausgeführt, nutzbar und in den gesamten Sanierungsablauf eingebunden ist.</p>

    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Wer Elektroinstallation im Rahmen einer Sanierung im Rhein-Main-Gebiet planen möchte, kann Radex unter <a href="tel:+496074960620">06074 960620</a> erreichen.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Beratungsgespräch vereinbaren</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'elektroinstallation-im-rhein-main-gebiet',
    title: "Elektroinstallation im Rhein-Main-Gebiet",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <h2>Elektroinstallation im Rhein-Main-Gebiet</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex sitzt in Rödermark und begleitet Sanierungen mit Elektrokoordination im Rhein-Main-Gebiet. Die Region ist vielseitig: Eigentumswohnungen in Frankfurt und Offenbach, Häuser in Rödermark, Rodgau, Langen, Dreieich oder Neu-Isenburg, Bestandsimmobilien in Darmstadt und Hanau, hochwertige Wohnlagen in Bad Homburg, Kronberg, Königstein oder Bad Soden sowie Gewerbeflächen in Eschborn, Hofheim, Groß-Gerau, Rüsselsheim oder Maintal.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Die Anforderungen unterscheiden sich je nach Objekt. Eine Wohnung in einem Mehrfamilienhaus braucht andere Abstimmungen als ein freistehendes Haus. Ein Altbau braucht andere Elektroprüfung als ein jüngeres Haus. Eine Badsanierung stellt andere Anforderungen als eine Küche. Eine Wärmepumpe braucht andere technische Voraussetzungen als ein reiner Innenausbau. Eine Gewerbefläche hat andere Anforderungen als ein Einfamilienhaus.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Radex koordiniert Elektrofachpartner deshalb objektbezogen. Entscheidend ist, welche Lösung zur Immobilie, zur Nutzung und zum Sanierungsziel passt.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="https://wa.me/491744684189" class="btn-primary gold" target="_blank" rel="noopener">Angebot anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'warum-radex-fuer-elektrokoordination-bei-sanierungen',
    title: "Warum Radex für Elektrokoordination bei Sanierungen?",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <h2>Warum Radex für Elektrokoordination bei Sanierungen?</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Elektroinstallation ist ein sicherheitsrelevantes Fachgewerk und muss durch qualifizierte Elektrofachbetriebe ausgeführt werden. Radex übernimmt die gewerkeübergreifende Koordination im Rahmen der Sanierung und sorgt dafür, dass Elektro rechtzeitig mit Bad, Küche, Heizung, Sanitär, Innenausbau und Oberflächen abgestimmt wird.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:16px">Die wichtigsten Vorteile:</p>
    <ul style="font-size:16px;color:var(--text-light);line-height:1.75;margin:0 0 20px;padding-left:20px">
      <li><strong style="color:var(--navy)">Frühe Elektrokoordination:</strong> Elektro wird nicht erst nachträglich geplant, sondern früh in den Sanierungsablauf eingebunden.</li>
      <li><strong style="color:var(--navy)">Qualifizierte Fachpartner:</strong> Elektroarbeiten werden durch Elektrofachbetriebe umgesetzt.</li>
      <li><strong style="color:var(--navy)">Ein Ansprechpartner:</strong> Kunden müssen nicht jedes Gewerk einzeln abstimmen.</li>
      <li><strong style="color:var(--navy)">SHK-Meisterkompetenz:</strong> Heizung, Sanitär und Gebäudetechnik werden bei Radex unter Meisterverantwortung geführt.</li>
      <li><strong style="color:var(--navy)">Schnittstellenkompetenz:</strong> Bad, Küche, Wärmepumpe, Innenausbau, Netzwerk und Sicherungskasten werden im Gesamtprojekt betrachtet.</li>
      <li><strong style="color:var(--navy)">Erfahrung im Bestand:</strong> Alte Leitungen, Sicherungskästen, Schadstoffverdacht, Feuchtigkeit und gewachsene Strukturen werden berücksichtigt.</li>
      <li><strong style="color:var(--navy)">Regionale Nähe:</strong> Radex sitzt in Rödermark und arbeitet im Rhein-Main-Gebiet.</li>
    </ul>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Wer eine Sanierung mit Elektrokoordination plant, kann Radex unter <a href="tel:+496074960620">06074 960620</a> anrufen oder das Projekt über den <a href="/kontakt">Kontaktbogen</a> anfragen.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Kostenlos beraten lassen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'warum-radex',
    title: "Warum Radex?",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Ihre Vorteile</div>
  <h2>Warum Radex?</h2>
  <div class="warum-grid" style="grid-template-columns:repeat(3,1fr)">
    <div class="warum-card"><div class="warum-card-num">01</div><h4>Klare Planung</h4><p>Transparente Abläufe von Anfang an.</p></div>
    <div class="warum-card"><div class="warum-card-num">02</div><h4>HSK Meisterbetrieb</h4><p>Fachgerechte Ausführung nach höchsten Standards.</p></div>
    <div class="warum-card"><div class="warum-card-num">03</div><h4>Alles aus einer Hand</h4><p>Koordination aller Arbeiten durch Radex.</p></div>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'so-laeuft-ihr-projekt-ab',
    title: "So läuft Ihr Projekt ab",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="section-label">Ablauf</div>
  <h2>So läuft Ihr Projekt ab</h2>
  <div class="process-grid">
    <div class="process-card">
      <div class="process-card-num">01</div>
      <h4>Beratung</h4>
      <p>Wir besprechen Ihre Wünsche in einem kostenlosen Erstgespräch.</p>
    </div>
    <div class="process-card">
      <div class="process-card-num">02</div>
      <h4>Planung</h4>
      <p>Radex erstellt ein klares Konzept mit Kosten und Zeitrahmen.</p>
    </div>
    <div class="process-card">
      <div class="process-card-num">03</div>
      <h4>Umsetzung</h4>
      <p>Die Umsetzung erfolgt sauber, termintreu und in höchster Qualität.</p>
    </div>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'elektroinstallation-anfragen',
    title: "Elektroinstallation anfragen",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <h2>Elektroinstallation anfragen</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Sie planen eine Badsanierung, Wohnungssanierung, Haussanierung, Altbausanierung, Komplettsanierung, Kernsanierung, Küchenmodernisierung, Heizungsmodernisierung, Wärmepumpe, Gewerbesanierung oder einen Mieterausbau im Rhein-Main-Gebiet? Dann sollte Elektroinstallation früh in den Sanierungsablauf eingebunden werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex koordiniert qualifizierte Elektrofachpartner und stimmt Elektroarbeiten mit Heizung, Sanitär, Innenausbau, Trockenbau, Fliesen, Böden, Malerarbeiten, Bad, Küche und weiteren Gewerken ab. So entsteht eine Sanierung, die technisch sinnvoll vorbereitet ist und im Alltag funktioniert.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Rufen Sie Radex direkt unter <a href="tel:+496074960620">06074 960620</a> an oder stellen Sie Ihre Anfrage über den <a href="/kontakt">Kontaktbogen</a>. Eine frühe Einschätzung hilft, Umfang, Reihenfolge, Kostenrahmen und technische Schnittstellen besser zu planen.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Unverbindlich anfragen</a>
  </div>
</div>` }}
      />
    ),
  }
];
