/* Auto-generated by scripts/build-energetische-sanierung-legacy.mjs – do not edit by hand. */
/* eslint-disable react/no-danger */

export const energetischeSanierungLegacySections = [
  {
    id: 'was-bedeutet-energetische-sanierung',
    title: "Was bedeutet energetische Sanierung?",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Was bedeutet energetische Sanierung?</div>
  <h2>Was bedeutet energetische Sanierung?</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Energetische Sanierung bedeutet, ein bestehendes Gebäude so zu modernisieren, dass Energieverluste reduziert, Heizsysteme verbessert, Wärme besser genutzt und der Wohnkomfort erhöht werden. Es geht nicht nur darum, weniger zu heizen. Es geht darum, Gebäudehülle, Heizung, Warmwasser, Lüftung, Feuchtigkeitsschutz und Innenausbau sinnvoll zusammenzubringen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Typische Maßnahmen sind Heizungsmodernisierung, Wärmepumpe, Dämmung von Dach, Fassade oder Kellerdecke, neue Fenster, Optimierung der Heizflächen, bessere Regelung, Lüftungslösungen, energetische Verbesserung von Bad, Küche oder Wohnräumen und die Beseitigung von Feuchtigkeits- oder Schimmelursachen. Auch Sanierungsplanung, Förderprüfung und Baubegleitung können Teil des Prozesses sein.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Wichtig ist: Energetische Sanierung ist nicht automatisch eine Komplettsanierung. Manchmal reichen einzelne, gut geplante Maßnahmen. In anderen Fällen ist eine umfassendere Sanierung sinnvoll, weil mehrere Bauteile und Gewerke zusammenhängen. Ein altes Haus kann zum Beispiel zuerst eine Heizungsmodernisierung brauchen, während Dämmung und Fenster später folgen. Bei einer Sanierung nach Kauf kann es sinnvoll sein, Bad, Heizung, Elektrokoordination, Innenausbau und Energieeffizienz gemeinsam zu planen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex betrachtet energetische Sanierung deshalb nicht isoliert. Entscheidend ist, welche Maßnahme im konkreten Objekt wirklich Nutzen bringt und in welcher Reihenfolge sie umgesetzt werden sollte.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Energetische Sanierung besprechen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'warum-energetische-sanierung-im-bestand-besonders-sorgfaeltig-geplant-werden-mus',
    title: "Warum energetische Sanierung im Bestand besonders sorgfältig geplant werden muss",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="section-label">Warum energetische Sanierung im Bestand besonders sorgfältig geplant werden muss</div>
  <h2>Warum energetische Sanierung im Bestand besonders sorgfältig geplant werden muss</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bestandsgebäude sind keine Neubauten. Sie haben vorhandene Bauteile, alte Leitungen, gewachsene Grundrisse, unterschiedliche Modernisierungsstände und oft mehrere Renovierungsschichten. Deshalb sollte eine energetische Sanierung nicht nur aus einer einzelnen Empfehlung bestehen. Wer zum Beispiel nur die Heizung austauscht, ohne Dämmung, Heizflächen, Vorlauftemperatur und Warmwasser zu prüfen, verschenkt möglicherweise Potenzial. Wer nur neue Fenster einbaut, aber Lüftung und Feuchtigkeit nicht mitdenkt, kann neue Probleme schaffen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine energetische Sanierung sollte immer zum Gebäude passen. Ein freistehendes Einfamilienhaus braucht eine andere Betrachtung als eine Eigentumswohnung. Ein Altbau mit hohen Decken hat andere Anforderungen als ein Reihenhaus aus den 1970er-Jahren. Ein vermietetes Objekt wird anders geplant als ein selbst genutztes Haus. Ein Haus nach Erbschaft braucht oft eine andere Reihenfolge als ein Objekt, das bereits bewohnt ist.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Deshalb beginnt gute energetische Sanierung mit einer Bestandsaufnahme: Wie alt ist die Heizung? Wie wird Warmwasser erzeugt? Welche Bauteile sind gedämmt? Gibt es Feuchtigkeit oder Schimmel? Sind Fenster und Türen dicht? Wie sind Heizkörper dimensioniert? Welche Räume werden schlecht warm? Welche Sanierungen sind ohnehin geplant? Welche Fördermöglichkeiten könnten relevant sein?</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Wenn Sie Interesse an einer energetischen Sanierung haben, ist der erste sinnvolle Schritt ein Gespräch über Ihr Objekt. Rufen Sie Radex unter <a href="tel:+496074960620">06074 960620</a> an oder senden Sie Ihre Anfrage über den <a href="/kontakt">Kontaktbogen</a>. So lässt sich klären, ob zuerst Heizung, Dämmung, Lüftung, Bad, Innenausbau oder Förderprüfung im Mittelpunkt stehen sollte.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Energetische Sanierung besprechen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'wann-ist-eine-energetische-sanierung-sinnvoll',
    title: "Wann ist eine energetische Sanierung sinnvoll?",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Wann ist eine energetische Sanierung sinnvoll?</div>
  <h2>Wann ist eine energetische Sanierung sinnvoll?</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine energetische Sanierung ist besonders sinnvoll, wenn ein Gebäude hohe Heizkosten verursacht, einzelne Räume schlecht warm werden, die Heizung alt ist, Heizkörper nicht mehr zur Nutzung passen, Fenster und Türen Zugluft erzeugen, Dach oder Kellerdecke ungedämmt sind oder Feuchtigkeit und Schimmel auftreten. Auch bei einem Hauskauf, einer Erbschaft oder einer geplanten Komplettsanierung lohnt sich eine energetische Betrachtung.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Viele Eigentümer beginnen mit einer einzelnen Beobachtung: Das Wohnzimmer wird nicht richtig warm. Das Bad bleibt kühl. Im Schlafzimmer entsteht Schimmel an der Außenwand. Die Heizkosten sind deutlich gestiegen. Die Heizung ist alt. Fenster beschlagen. Im Dachgeschoss ist es im Sommer zu heiß und im Winter zu kalt. Solche Hinweise zeigen, dass Gebäudehülle, Heizung, Lüftung oder Nutzung nicht optimal zusammenspielen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Auch vor größeren Sanierungen ist energetische Planung wichtig. Wer ein Bad saniert, sollte Heizkörper, Warmwasser und Lüftung mitdenken. Wer Böden und Wände erneuert, sollte prüfen, ob Heizleitungen, Dämmung oder Feuchtigkeit eine Rolle spielen. Wer eine Wohnung nach Kauf saniert, sollte Elektrokoordination, Heizung, Fensteranschlüsse und Raumklima vor dem Einzug klären. Wer ein Haus modernisiert, sollte überlegen, ob die Heizungsanlage zur langfristigen Nutzung passt.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Energetische Sanierung lohnt sich nicht nur aus Kostensicht. Sie kann Wohnkomfort verbessern, Schimmelrisiken reduzieren, den Wert einer Immobilie stärken und zukünftige Modernisierungsschritte besser vorbereiten.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Energetische Sanierung besprechen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'energetische-sanierung-beginnt-mit-der-bestandsaufnahme',
    title: "Energetische Sanierung beginnt mit der Bestandsaufnahme",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="section-label">Energetische Sanierung beginnt mit der Bestandsaufnahme</div>
  <h2>Energetische Sanierung beginnt mit der Bestandsaufnahme</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bevor Maßnahmen geplant werden, sollte der Bestand verstanden werden. Dazu gehören Baujahr, Gebäudetyp, Nutzung, Wohnfläche, Heizsystem, Warmwasser, Fenster, Dach, Fassade, Keller, Lüftung, Feuchtigkeit, Schimmel, bisherige Sanierungen und geplante Umbauten. Auch vorhandene Unterlagen sind hilfreich: Energieausweis, Heizkostenabrechnungen, Rechnungen früherer Modernisierungen, Grundrisse, Fotos, Schornsteinfegerunterlagen oder technische Daten der Heizung.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine gute Bestandsaufnahme beantwortet nicht nur die Frage, was alt ist. Sie zeigt auch, was noch gut funktioniert. Nicht jedes Bauteil muss sofort erneuert werden. Manche Maßnahmen sind dringend, andere können später folgen. Manche Gebäude brauchen zuerst Feuchtigkeitsklärung, bevor gedämmt wird. Andere brauchen zuerst eine Heizungsprüfung, bevor Fenster oder Dämmung geplant werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex kann im Rahmen einer Sanierungsanfrage die handwerklich-praktischen Schnittstellen einordnen. Für energetische Nachweise, Förderanträge oder detaillierte Berechnungen kann je nach Projekt eine Energieberatung erforderlich sein. Wichtig ist, diese Rollen sauber zu trennen: Radex koordiniert Sanierung und Ausführung; Förderfähigkeit, technische Mindestanforderungen und Energieberatung müssen projektbezogen aktuell geprüft werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Wenn Sie bereits Unterlagen haben, senden Sie diese über den <a href="/kontakt">Kontaktbogen</a> mit. Bilder vom Heizraum, Heizkörpern, Dachboden, Kellerdecke, Fenstern, Bad, Außenwänden oder Feuchtigkeitsspuren helfen bei der ersten Einschätzung.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Energetische Sanierung besprechen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'heizung-modernisieren-als-teil-der-energetischen-sanierung',
    title: "Heizung modernisieren als Teil der energetischen Sanierung",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Heizung modernisieren als Teil der energetischen Sanierung</div>
  <h2>Heizung modernisieren als Teil der energetischen Sanierung</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Die Heizung ist oft der sichtbarste Ausgangspunkt einer energetischen Sanierung. Wenn die Anlage alt ist, häufig repariert werden muss, hohe Verbrauchswerte verursacht oder nicht mehr zur langfristigen Planung passt, sollte eine Modernisierung geprüft werden. Dabei geht es nicht nur um den Austausch eines Geräts. Entscheidend ist, ob Heizsystem, Heizflächen, Warmwasser, Gebäudehülle und Nutzung zusammenpassen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine neue Heizung arbeitet nur dann gut, wenn das Gebäude und die Wärmeverteilung dazu passen. Alte Heizkörper, hohe Vorlauftemperaturen, ungedämmte Bauteile oder schlecht eingestellte Regelung können den Nutzen einer modernen Anlage begrenzen. Besonders bei Wärmepumpen ist es wichtig, Vorlauftemperatur, Heizkörper, Dämmstandard und Warmwasserbedarf zu prüfen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Die KfW beschreibt die Heizungsförderung für Privatpersonen im Wohngebäude als Zuschuss für Eigentümerinnen und Eigentümer bestehender Wohngebäude beim Kauf und Einbau einer neuen klimafreundlichen Heizung; genannt wird ein Zuschuss von bis zu 70 Prozent der förderfähigen Kosten, vorbehaltlich verfügbarer Haushaltsmittel und ohne grundsätzlichen Rechtsanspruch.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex ist im Bereich Heizung, Sanitär und Gebäudetechnik SHK-meistergeführt. Wenn Sie prüfen möchten, ob eine Heizungsmodernisierung im Rahmen Ihrer energetischen Sanierung sinnvoll ist, rufen Sie Radex unter <a href="tel:+496074960620">06074 960620</a> an oder senden Sie eine Anfrage über den <a href="/kontakt">Kontaktbogen</a>.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Heizungsberatung anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'waermepumpe-im-bestand-nicht-nur-geraetetausch-sondern-systempruefung',
    title: "Wärmepumpe im Bestand: Nicht nur Gerätetausch, sondern Systemprüfung",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="section-label">Wärmepumpe im Bestand: Nicht nur Gerätetausch, sondern Systemprüfung</div>
  <h2>Wärmepumpe im Bestand: Nicht nur Gerätetausch, sondern Systemprüfung</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Viele Eigentümer interessieren sich für eine Wärmepumpe im Bestand. Das kann sinnvoll sein, muss aber gut geprüft werden. Eine Wärmepumpe ist kein einfacher Austausch „alt gegen neu", sondern Teil eines Systems. Gebäudehülle, Heizflächen, Vorlauftemperatur, Warmwasser, Aufstellort, Schallschutz, Elektroanschluss, Platzbedarf und Förderfähigkeit müssen zusammen betrachtet werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Ein gut gedämmtes Gebäude mit niedrigen Vorlauftemperaturen ist meist einfacher für eine Wärmepumpe geeignet als ein ungedämmtes Gebäude mit kleinen Heizkörpern und hohem Wärmebedarf. Das bedeutet aber nicht, dass Bestandsgebäude grundsätzlich ungeeignet sind. Häufig lassen sich durch größere Heizkörper, bessere Regelung, Dämmmaßnahmen, hydraulische Abstimmung oder Kombinationen gute Voraussetzungen schaffen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Auch der Aufstellort ist wichtig. Eine Luft-Wasser-Wärmepumpe braucht Platz, geeignete Luftführung und Schallschutz. Technikraum, Warmwasserspeicher und Leitungswege müssen geplant werden. Elektroarbeiten werden durch qualifizierte Elektrofachpartner ausgeführt und von Radex koordiniert.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine Wärmepumpe sollte deshalb nicht isoliert entschieden werden. Sie gehört in eine energetische Gesamtbetrachtung. Radex kann SHK, Innenausbau, Elektrokoordination und Sanierungsablauf verbinden, damit die Heizungsmodernisierung nicht an Schnittstellen scheitert.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Kostenlos beraten lassen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'daemmung-dach-fassade-kellerdecke-und-innenbereiche-richtig-einordnen',
    title: "Dämmung: Dach, Fassade, Kellerdecke und Innenbereiche richtig einordnen",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Dämmung: Dach, Fassade, Kellerdecke und Innenbereiche richtig einordnen</div>
  <h2>Dämmung: Dach, Fassade, Kellerdecke und Innenbereiche richtig einordnen</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Dämmung kann Energieverluste deutlich reduzieren, muss aber zum Gebäude passen. Typische Bereiche sind Dach, oberste Geschossdecke, Fassade, Kellerdecke, Bodenflächen, Heizungsleitungen und manchmal Innenbereiche. Welche Maßnahme sinnvoll ist, hängt vom Bestand ab.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Die BAFA nennt bei Einzelmaßnahmen an der Gebäudehülle für Wohngebäude unter anderem, dass Bestandsgebäude förderfähig sein können, wenn Bauantrag oder Bauanzeige zum Zeitpunkt der Antragstellung mindestens fünf Jahre zurückliegen; für Gebäudehüllenmaßnahmen nennt das BAFA außerdem ein förderfähiges Mindestinvestitionsvolumen von 300 Euro brutto und einen Grundfördersatz von 15 Prozent der förderfähigen Ausgaben.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Dämmung sollte nicht nach dem Motto „mehr ist immer besser" geplant werden. Wichtig sind Anschlüsse, Feuchtigkeit, Wärmebrücken, Lüftung und Nutzung. Eine schlecht geplante Dämmung kann Probleme verursachen, wenn Feuchtigkeit eingeschlossen wird oder Anschlüsse nicht sauber ausgeführt sind. Besonders im Altbau, Keller und Dach ist bauphysikalische Sorgfalt wichtig.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex kann Dämmmaßnahmen im Zusammenhang mit Innenausbau, Heizung, Feuchtigkeit, Schimmel und Sanierungsablauf koordinieren. Wenn eine Energieberatung oder Fachplanung erforderlich ist, sollte diese früh eingebunden werden.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="https://wa.me/491744684189" class="btn-primary gold" target="_blank" rel="noopener">Jetzt per WhatsApp anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'fenster-erneuern-und-lueftung-mitdenken',
    title: "Fenster erneuern und Lüftung mitdenken",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="section-label">Fenster erneuern und Lüftung mitdenken</div>
  <h2>Fenster erneuern und Lüftung mitdenken</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Neue Fenster können Wärmeverluste reduzieren und den Wohnkomfort verbessern. Gleichzeitig verändern sie den Luftaustausch. Alte undichte Fenster haben oft ungewollt für Luftwechsel gesorgt. Neue dichte Fenster reduzieren Zugluft, können aber bei falscher Nutzung oder fehlender Lüftung zu Feuchtigkeitsproblemen führen. Deshalb sollten Fenster und Lüftung immer gemeinsam betrachtet werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Besonders wichtig ist das in Bädern, Schlafzimmern, Küchen und Räumen mit Außenwänden. Wenn neue Fenster eingebaut werden, aber kalte Wandbereiche bestehen bleiben, kann Feuchtigkeit an ungünstigen Stellen kondensieren. Dann entstehen Schimmelrisiken, obwohl energetisch eigentlich verbessert wurde.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bei Fenstern geht es außerdem um Anschlüsse. Fensterlaibungen, Rollladenkästen, Abdichtung, Innenputz, Malerarbeiten und eventuell Fassadendämmung müssen zusammenpassen. Ein Fensterwechsel kann deshalb Innenausbau und Oberflächen betreffen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Wenn Sie neue Fenster, bessere Dämmung oder eine energetische Sanierung planen, sollte die Lüftungsfrage früh geklärt werden. Radex kann die handwerklichen Schnittstellen rund um Fensteranschlüsse, Innenausbau, Feuchtigkeit und Sanierungsablauf koordinieren.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Unverbindlich anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'lueftung-und-feuchtigkeitsschutz-bei-energetischer-sanierung',
    title: "Lüftung und Feuchtigkeitsschutz bei energetischer Sanierung",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Lüftung und Feuchtigkeitsschutz bei energetischer Sanierung</div>
  <h2>Lüftung und Feuchtigkeitsschutz bei energetischer Sanierung</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Energetische Sanierung verändert das Raumklima. Wenn Gebäude dichter werden, weniger Wärme verlieren und Oberflächen anders temperiert sind, muss Feuchtigkeit kontrolliert abgeführt werden. Lüftung ist deshalb kein Nebenthema, sondern ein zentraler Bestandteil.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Feuchtigkeit entsteht täglich: Duschen, Kochen, Waschen, Atmen, Pflanzen, Wäschetrocknung und Nutzung. Wenn Luftfeuchtigkeit nicht abgeführt wird, können Schimmel, muffiger Geruch und Materialschäden entstehen. Besonders bei Bädern, Küchen, Schlafzimmern und innenliegenden Räumen ist Lüftung wichtig.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine energetische Sanierung sollte daher prüfen, ob Fensterlüftung ausreicht, ob vorhandene Lüfter funktionieren, ob Bäder verbessert werden müssen oder ob technische Lüftung sinnvoll ist. Bei innenliegenden Bädern, dichten Fenstern und sanierten Gebäuden kann die Lüftungsplanung besonders wichtig werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex ist zertifiziert für Schimmel- und Asbestsanierung und kann Feuchtigkeits- und Schimmelthemen im Zusammenhang mit energetischer Sanierung einordnen. Wenn Schimmel bereits vorhanden ist, sollte nicht einfach gedämmt oder gestrichen werden. Erst Ursache prüfen, dann sanieren.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Energetische Sanierung besprechen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'energetische-sanierung-und-badsanierung-sinnvoll-verbinden',
    title: "Energetische Sanierung und Badsanierung sinnvoll verbinden",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="section-label">Energetische Sanierung und Badsanierung sinnvoll verbinden</div>
  <h2>Energetische Sanierung und Badsanierung sinnvoll verbinden</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Badsanierung und energetische Sanierung überschneiden sich häufiger, als viele Eigentümer denken. Im Bad kommen Heizung, Warmwasser, Lüftung, Feuchtigkeit, Abdichtung, Elektrokoordination und Innenausbau zusammen. Wenn ein Bad saniert wird, ist das ein guter Zeitpunkt, Heizkörper, Lüfter, Warmwasser, Leitungen und Schimmelrisiken mitzudenken.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Ein alter Badheizkörper kann zu klein sein oder ungünstig sitzen. Ein innenliegendes Bad braucht einen funktionierenden Lüfter. Eine neue Dusche erhöht möglicherweise die Feuchtigkeitsbelastung. Neue Fenster verändern Lüftung und Raumklima. Wenn Warmwasser lange braucht oder Leitungen alt sind, sollte das im Zuge der Sanierung geprüft werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex ist SHK-meistergeführt im Bereich Heizung, Sanitär und Gebäudetechnik und kann Badsanierung mit energetischen Themen verbinden. Elektroarbeiten für Lüfter, Licht, Spiegelschrank oder Dusch-WC werden durch qualifizierte Elektrofachpartner ausgeführt und koordiniert.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Wenn Sie ohnehin eine Badsanierung planen und gleichzeitig Energieeffizienz verbessern möchten, rufen Sie Radex unter <a href="tel:+496074960620">06074 960620</a> an. Oft ist es sinnvoller, solche Themen gemeinsam zu planen, statt später fertige Flächen erneut zu öffnen.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Energetische Sanierung besprechen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'energetische-sanierung-nach-hauskauf-oder-erbschaft',
    title: "Energetische Sanierung nach Hauskauf oder Erbschaft",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Energetische Sanierung nach Hauskauf oder Erbschaft</div>
  <h2>Energetische Sanierung nach Hauskauf oder Erbschaft</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Nach Hauskauf oder Erbschaft ist energetische Sanierung besonders wichtig. Viele Eigentümer übernehmen eine Immobilie, deren Modernisierungsstand unklar ist. Die Heizung funktioniert vielleicht noch, ist aber alt. Fenster wurden teilweise getauscht. Das Dach ist möglicherweise ungedämmt. Im Keller riecht es muffig. Das Bad ist veraltet. Die Elektroinstallation passt nicht mehr zur heutigen Nutzung. In dieser Phase sollte energetische Sanierung nicht isoliert, sondern als Teil der Gesamtmodernisierung betrachtet werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Der Vorteil: Vor dem Einzug oder vor einer umfassenden Sanierung lassen sich Maßnahmen besser bündeln. Wenn Böden, Wände, Bad, Heizung und Innenausbau ohnehin geplant sind, können energetische Punkte direkt mitgedacht werden. Das spart spätere Eingriffe.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bei einer geerbten Immobilie ist häufig auch die langfristige Strategie wichtig. Soll das Haus selbst genutzt, vermietet, verkauft oder für mehrere Generationen vorbereitet werden? Davon hängt ab, welche energetischen Maßnahmen wirtschaftlich sinnvoll sind.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex kann bei Hausmodernisierung nach Kauf oder Erbschaft helfen, eine sinnvolle Reihenfolge zu entwickeln: Bestand prüfen, energetische Schwachstellen erkennen, technische Gewerke koordinieren, Fördermöglichkeiten prüfen lassen und Sanierung in Etappen planen.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Energetische Sanierung besprechen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'energetische-sanierung-im-bewohnten-haus',
    title: "Energetische Sanierung im bewohnten Haus",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="section-label">Energetische Sanierung im bewohnten Haus</div>
  <h2>Energetische Sanierung im bewohnten Haus</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Nicht jede energetische Sanierung findet im Leerstand statt. Viele Eigentümer wohnen bereits im Haus und möchten Schritt für Schritt modernisieren. Das ist möglich, braucht aber gute Planung. Staub, Lärm, Heizungsunterbrechungen, Wasserabschaltungen, Bauabschnitte und Zugang müssen berücksichtigt werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Ein Heizungstausch kann zeitweise Warmwasser oder Wärme betreffen. Dämmarbeiten können bestimmte Räume, Dachboden oder Keller beeinflussen. Fensterarbeiten betreffen Wohnräume direkt. Badsanierung ist im bewohnten Zustand besonders sensibel. Deshalb sollten energetische Maßnahmen so geplant werden, dass der Alltag möglichst wenig belastet wird.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine Etappenplanung kann sinnvoll sein. Vielleicht wird zuerst die Heizung modernisiert, später die Dämmung verbessert und danach Bad oder Innenausbau angepasst. Oder es wird zuerst das Dach gedämmt, bevor die Heizung neu dimensioniert wird. Entscheidend ist, dass die Reihenfolge technisch sinnvoll bleibt.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex kann bewohnte Sanierungen koordinieren und die Gewerke so abstimmen, dass Eigentümer nicht jeden Fachpartner einzeln steuern müssen.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Energetische Sanierung besprechen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'energetische-sanierung-vor-einzug',
    title: "Energetische Sanierung vor Einzug",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Energetische Sanierung vor Einzug</div>
  <h2>Energetische Sanierung vor Einzug</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Wenn ein Haus oder eine Wohnung noch leer steht, ist der Zeitpunkt für energetische Sanierung besonders günstig. Vor Einzug lassen sich Wände öffnen, Heizkörper versetzen, Böden erneuern, Leitungen prüfen, Fensteranschlüsse herstellen, Bäder sanieren, alte Materialien prüfen und Oberflächen neu aufbauen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Wer nach Kauf direkt einzieht und energetische Themen verschiebt, muss später erneut Baustellen im bewohnten Zustand organisieren. Deshalb ist es oft sinnvoll, vor dem Einzug zumindest die wichtigsten Punkte zu prüfen: Heizung, Bad, Warmwasser, Elektrokoordination, Fenster, Dämmung, Feuchtigkeit, Schimmel und alte Bodenbeläge.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Nicht alles muss sofort umgesetzt werden. Aber eine vorbereitende Planung kann spätere Eingriffe reduzieren. Beispielsweise können Leitungswege, Heizkörperpositionen, Lüfter, Netzwerk oder Dämmanschlüsse vorbereitet werden, wenn ohnehin saniert wird.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Wenn Sie eine Immobilie gekauft haben und vor dem Einzug energetisch sinnvoll modernisieren möchten, rufen Sie Radex unter <a href="tel:+496074960620">06074 960620</a> an oder senden Sie eine Anfrage über den <a href="/kontakt">Kontaktbogen</a>. Je früher die Planung beginnt, desto besser lassen sich Maßnahmen bündeln.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Energetische Sanierung besprechen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'foerderung-bei-energetischer-sanierung-chancen-pruefen-aber-nicht-blind-planen',
    title: "Förderung bei energetischer Sanierung: Chancen prüfen, aber nicht blind planen",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="section-label">Förderung bei energetischer Sanierung: Chancen prüfen, aber nicht blind planen</div>
  <h2>Förderung bei energetischer Sanierung: Chancen prüfen, aber nicht blind planen</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Förderung kann energetische Sanierung attraktiver machen, sollte aber nie die einzige Entscheidungsgrundlage sein. Wichtig ist zuerst, welche Maßnahme technisch und wirtschaftlich sinnvoll ist. Danach sollte geprüft werden, ob Förderprogramme passen, welche Anforderungen gelten und wann der Antrag gestellt werden muss.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Die Bundesförderung für effiziente Gebäude unterstützt Sanierungsmaßnahmen, die dauerhaft Energiekosten einsparen und das Klima schützen; beim BAFA können weiterhin Einzelmaßnahmen an der Gebäudehülle, Anlagentechnik außer Heizung, Heizungsoptimierung sowie Gebäude- oder Wärmenetze beantragt werden, während Wärmeerzeuger über die KfW gefördert werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Wichtig ist: Förderbedingungen können sich ändern. Es gibt technische Mindestanforderungen, Antragsfristen, Nachweise, mögliche Energieberaterpflichten und Haushaltsvorbehalte. Deshalb sollte Förderung immer aktuell und vor Maßnahmenbeginn geprüft werden. Radex kann im Sanierungsablauf unterstützen, ersetzt aber keine Förderzusage.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Wenn Sie Interesse an Förderung für energetische Sanierung haben, sprechen Sie uns früh an. Rufen Sie Radex unter <a href="tel:+496074960620">06074 960620</a> an oder senden Sie Ihre Anfrage über den <a href="/kontakt">Kontaktbogen</a>. Je früher das Thema Förderung geklärt wird, desto besser lässt es sich in Planung und Angebot einordnen.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Energetische Sanierung besprechen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'geg-und-neue-heizungen-was-eigentuemer-grundsaetzlich-beachten-sollten',
    title: "GEG und neue Heizungen: Was Eigentümer grundsätzlich beachten sollten",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">GEG und neue Heizungen: Was Eigentümer grundsätzlich beachten sollten</div>
  <h2>GEG und neue Heizungen: Was Eigentümer grundsätzlich beachten sollten</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Das Gebäudeenergiegesetz ist für viele Eigentümer ein wichtiges Thema, besonders bei Heizungsmodernisierung. Die Bundesregierung beschreibt, dass neue Heizungen spätestens ab Mitte 2028 mit mindestens 65 Prozent erneuerbarer Energie laufen sollen; die Regel ist eng mit der kommunalen Wärmeplanung verbunden, während für Neubauten in Neubaugebieten bereits seit 2024 entsprechende Vorgaben gelten.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Für Eigentümer bedeutet das nicht, dass jede bestehende Heizung sofort ausgetauscht werden muss. Es bedeutet aber, dass Modernisierungsentscheidungen langfristig gedacht werden sollten. Wer heute Heizung, Dämmung oder Warmwasser plant, sollte zukünftige Anforderungen, kommunale Wärmeplanung, Fördermöglichkeiten und technische Entwicklung berücksichtigen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex formuliert hier bewusst keine Rechtsberatung. Die konkrete Pflicht, Übergangsregelung oder Förderfähigkeit muss projektbezogen aktuell geprüft werden. Wichtig ist die praktische Konsequenz: Heizungsmodernisierung sollte nicht isoliert erfolgen. Gebäudezustand, Heizflächen, Dämmung, Warmwasser und Nutzung müssen zusammen betrachtet werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Wenn Sie unsicher sind, welche Heizlösung zu Ihrer Immobilie passt, sprechen Sie mit Radex. Wir helfen, die handwerklichen und technischen Schnittstellen zu ordnen und passende Fachpartner einzubinden.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Heizungsberatung anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'energetische-sanierung-und-schimmelrisiko',
    title: "Energetische Sanierung und Schimmelrisiko",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="section-label">Energetische Sanierung und Schimmelrisiko</div>
  <h2>Energetische Sanierung und Schimmelrisiko</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Energetische Sanierung kann Schimmelrisiken reduzieren, wenn sie richtig geplant wird. Bessere Dämmung, wärmere Oberflächen, passende Heizung und kontrollierte Lüftung können helfen, Feuchtigkeit zu vermeiden. Gleichzeitig können falsch geplante Einzelmaßnahmen neue Risiken schaffen. Deshalb müssen Dämmung, Fenster, Lüftung und Heizung zusammenpassen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Ein typischer Fall: Alte Fenster werden durch neue dichte Fenster ersetzt, aber Lüftung und kalte Außenwände bleiben unverändert. Dann kann Feuchtigkeit an Wandbereichen kondensieren. Ein anderer Fall: Innenbereiche werden gedämmt, ohne Feuchtigkeit und Anschlüsse zu prüfen. Auch das kann problematisch werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Wenn bereits Schimmel vorhanden ist, sollte vor energetischen Maßnahmen die Ursache geklärt werden. Schimmel nur zu überstreichen und danach zu dämmen, ist keine gute Lösung. Radex ist zertifiziert für Schimmel- und Asbestsanierung und kann solche Themen im Sanierungsablauf einordnen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Gerade bei Bädern, Schlafzimmern, Kellerbereichen und Außenwänden lohnt sich eine sorgfältige Betrachtung. Energetische Sanierung soll Komfort verbessern – nicht neue Feuchtigkeitsprobleme erzeugen.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Energetische Sanierung besprechen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'schadstoffverdacht-bei-energetischer-sanierung-im-bestand',
    title: "Schadstoffverdacht bei energetischer Sanierung im Bestand",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Schadstoffverdacht bei energetischer Sanierung im Bestand</div>
  <h2>Schadstoffverdacht bei energetischer Sanierung im Bestand</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Energetische Sanierung kann Rückbauarbeiten auslösen: alte Bodenbeläge werden entfernt, Putze bearbeitet, Dämmstoffe ausgebaut, Decken geöffnet, Heizräume verändert oder Bäder saniert. Bei älteren Gebäuden können dabei Schadstoffthemen relevant werden. Dazu gehören etwa alte Kleber, Bodenbeläge, Fliesenkleber, Spachtelmassen, Putze, Plattenmaterialien, Dämmstoffe oder Rohrisolierungen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Das bedeutet nicht, dass jedes alte Material belastet ist. Aber bei Verdacht sollte nicht einfach geschliffen, gefräst, gestemmt oder abgebrochen werden. Erst prüfen, dann entscheiden. Radex ist zertifiziert für Asbest- und Schimmelsanierung und verfügt über Sachkunde nach TRGS 519.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Schadstoffprüfung ist besonders wichtig, wenn energetische Sanierung mit Altbausanierung, Badsanierung, Heizungsmodernisierung oder Innenausbau verbunden wird. Ein unerkannter Schadstofffund mitten in der Sanierung kann Zeitplan und Kosten stark beeinflussen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex kann Schadstoffverdacht im Sanierungsablauf berücksichtigen und die nächsten Schritte fachgerecht koordinieren.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Energetische Sanierung besprechen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'ablauf-einer-energetischen-sanierung-mit-radex',
    title: "Ablauf einer energetischen Sanierung mit Radex",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="section-label">Ablauf einer energetischen Sanierung mit Radex</div>
  <h2>Ablauf einer energetischen Sanierung mit Radex</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine energetische Sanierung mit Radex beginnt mit einem Gespräch über Ihr Ziel. Möchten Sie Heizkosten senken, ein Haus nach Kauf modernisieren, eine alte Heizung ersetzen, Fördermöglichkeiten prüfen, Schimmel vermeiden, das Bad sanieren oder langfristig den Wert der Immobilie verbessern? Danach folgt die Bestandsaufnahme.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Im nächsten Schritt werden sinnvolle Maßnahmen eingeordnet. Das kann eine Heizungsmodernisierung sein, eine Wärmepumpe, Dämmung, Fensteranschlüsse, Lüftung, Badmodernisierung, Innenausbau oder eine Kombination. Bei Förderthemen wird geklärt, ob Energieberatung oder Fachplanung einzubinden ist und welche Anforderungen vor Beauftragung geprüft werden müssen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Danach wird der Sanierungsumfang beschrieben. Radex koordiniert SHK, Innenausbau, Rückbau, Böden, Trockenbau, Badsanierung, Schadstoffthemen und Elektrofachpartner. So entstehen weniger Schnittstellen für Eigentümer.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Nach Besichtigung und fachlicher Bewertung erhalten Sie ein transparentes Angebot mit klar beschriebenem Leistungsumfang. Wenn der Umfang eindeutig abgegrenzt ist, kann auch eine Festpreis-Kalkulation geprüft werden. Bei unklaren Förder-, Statik-, Energieberatungs- oder Schadstofffragen müssen diese Punkte vorab geklärt werden.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Ablauf besprechen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'kosten-einer-energetischen-sanierung-realistisch-einschaetzen',
    title: "Kosten einer energetischen Sanierung realistisch einschätzen",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Kosten einer energetischen Sanierung realistisch einschätzen</div>
  <h2>Kosten einer energetischen Sanierung realistisch einschätzen</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Die Kosten einer energetischen Sanierung hängen stark vom Bestand und vom Umfang ab. Eine Heizungsoptimierung ist nicht mit einer vollständigen Heizungsmodernisierung vergleichbar. Eine Kellerdeckendämmung ist anders zu bewerten als eine Fassadendämmung. Eine Badsanierung mit Lüftung und Heizkörper ist anders als eine reine Dämmmaßnahme. Deshalb sind pauschale Aussagen oft ungenau.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Wichtige Kostenfaktoren sind Heizsystem, Warmwasser, Dämmflächen, Fenster, Lüftung, Innenausbau, Rückbau, Schadstoffprüfung, Zugänglichkeit, Materialqualität, Förderanforderungen und Wiederherstellung von Oberflächen. Auch bewohnter Zustand oder Leerstand beeinflussen den Aufwand.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Förderung kann die Wirtschaftlichkeit verbessern, sollte aber nicht als garantiert eingeplant werden. Förderprogramme, Anträge, technische Anforderungen, verfügbare Haushaltsmittel und Nachweise müssen aktuell geprüft werden. Die BAFA nennt für Fachplanung und Baubegleitung im Wohngebäude einen Fördersatz von 50 Prozent der förderfähigen Ausgaben mit gedeckelten förderfähigen Ausgaben; solche Details müssen je Projekt aktuell geprüft und passend eingeordnet werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex hilft, Kosten und Umfang verständlich zu strukturieren, damit Eigentümer nicht nur einzelne Preise vergleichen, sondern die richtige Sanierungslogik erkennen.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Unverbindliches Angebot anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'haeufige-fehler-bei-energetischer-sanierung',
    title: "Häufige Fehler bei energetischer Sanierung",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="section-label">Häufige Fehler bei energetischer Sanierung</div>
  <h2>Häufige Fehler bei energetischer Sanierung</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Ein häufiger Fehler ist, eine Maßnahme isoliert zu betrachten. Eine neue Heizung ohne Prüfung der Heizkörper, Vorlauftemperatur und Gebäudehülle kann unter ihren Möglichkeiten bleiben. Neue Fenster ohne Lüftungskonzept können Feuchtigkeitsprobleme begünstigen. Dämmung ohne Feuchtigkeitsprüfung kann Risiken erzeugen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Ein weiterer Fehler ist, Förderung zu spät zu prüfen. Viele Förderprogramme verlangen, dass Antragstellung und technische Anforderungen vor Maßnahmenbeginn geklärt sind. Wer zu früh beauftragt oder startet, kann Förderchancen verlieren.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Auch die Reihenfolge wird oft unterschätzt. Wenn zuerst Oberflächen fertiggestellt werden und später Heizungsleitungen, Lüfter oder Dämmanschlüsse geändert werden, entstehen doppelte Arbeiten. Besonders nach Kauf oder vor Einzug sollte energetische Sanierung früh in die Gesamtplanung.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Ein weiterer Fehler ist, Schimmel oder Feuchtigkeit zu überdecken. Energetische Maßnahmen sollten Ursachen lösen, nicht verdecken.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex setzt deshalb auf strukturierte Bestandsaufnahme, klare Schnittstellen und koordinierte Ausführung.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Energetische Sanierung besprechen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'wann-radex-der-richtige-ansprechpartner-ist',
    title: "Wann Radex der richtige Ansprechpartner ist",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Wann Radex der richtige Ansprechpartner ist</div>
  <h2>Wann Radex der richtige Ansprechpartner ist</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex ist besonders dann der richtige Ansprechpartner, wenn energetische Sanierung nicht nur aus einer einzelnen Maßnahme besteht, sondern mehrere Gewerke zusammenkommen. Das gilt bei Heizung, Sanitär, Badsanierung, Innenausbau, Dämmung, Fensteranschlüssen, Lüftung, Schadstoffverdacht, Schimmelthemen, Wohnungssanierung, Haussanierung oder Modernisierung nach Kauf.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex übernimmt nicht die Rolle einer Förderstelle oder Behörde. Radex koordiniert Sanierung und handwerkliche Umsetzung. Im Bereich Heizung, Sanitär und Gebäudetechnik ist Radex SHK-meistergeführt. Elektroarbeiten werden durch qualifizierte Elektrofachpartner ausgeführt und eingebunden. Bei Schimmel- und Asbestthemen bringt Radex Zertifizierung und Sachkunde nach TRGS 519 ein.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Wenn Sie eine energetische Sanierung planen, Interesse an Förderung haben oder wissen möchten, welche Maßnahmen bei Ihrem Objekt wirklich sinnvoll sind, rufen Sie Radex unter <a href="tel:+496074960620">06074 960620</a> an oder senden Sie eine unverbindliche Anfrage über den <a href="/kontakt">Kontaktbogen</a>.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Kostenlos beraten lassen</a>
  </div>
</div>` }}
      />
    ),
  }
];
