/* Auto-generated by scripts/build-kernsanierung-legacy.mjs – do not edit by hand. */
/* eslint-disable react/no-danger */

export const kernsanierungLegacySections = [
  {
    id: 'kernsanierung-im-bestand',
    title: "Kernsanierung im Bestand",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="intro-section">
  <div class="intro-text">
    <div class="section-label">Kernsanierung im Bestand</div>
    <p style="font-size:17px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine Kernsanierung ist die tiefste Form der Sanierung im Bestand. Sie wird dann relevant, wenn eine Immobilie nicht nur modernisiert, sondern technisch, baulich und funktional grundlegend neu aufgebaut werden soll. Während eine <a href="/komplettsanierung-rhein-main">Komplettsanierung</a> viele Bereiche einer Immobilie erneuert, geht eine Kernsanierung meist deutlich weiter: Rückbau, Leitungen, Heizung, Sanitär, Elektrokoordination, Innenwände, Bodenaufbau, Decken, Bad, Küche, Raumaufteilung, energetische Maßnahmen, Feuchtigkeit, Schadstoffprüfung und Ausbau müssen als ein Gesamtprojekt geplant werden.</p>
    <p style="font-size:17px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Gerade bei älteren Häusern, Wohnungen, Mehrfamilienhäusern, Gewerbeflächen oder Bestandsimmobilien nach Kauf zeigt sich häufig erst nach genauer Prüfung, wie tief eine Sanierung wirklich gehen muss. Ein Bad ist nicht nur veraltet, sondern die Leitungen sind ebenfalls überholt. Alte Bodenbeläge müssen entfernt werden, doch darunter können Kleber, Schichten oder Schadstoffverdacht auftauchen. Die Elektrostruktur reicht nicht mehr für heutige Nutzung. Wände, Decken und Böden sind uneben oder mehrfach überarbeitet. Die Heizung arbeitet noch, passt aber nicht mehr zum zukünftigen Gebäudezustand. Keller, Feuchtigkeit, Schimmel oder alte Materialien müssen eingeordnet werden.</p>
    <p style="font-size:17px;color:var(--text-light);line-height:1.75;margin-bottom:20px">In solchen Fällen reicht eine oberflächliche Renovierung nicht aus. Eine Kernsanierung kann die richtige Lösung sein, wenn eine Immobilie auf eine neue technische Grundlage gestellt werden soll. Ziel ist nicht, Bestand pauschal zu entwerten. Ziel ist, vorhandene Substanz fachlich zu prüfen, erhaltenswerte Bauteile zu respektieren und dort tief einzugreifen, wo Technik, Sicherheit, Komfort, Energieeffizienz oder Nutzung es erforderlich machen.</p>
    <p style="font-size:17px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Die Radex Objektmanagement GmbH aus Rödermark begleitet Kernsanierungen im Rhein-Main-Gebiet als koordinierender <a href="/generalunternehmer-rhein-main">Generalunternehmer</a>. Für Eigentümer, Käufer, Eigennutzer, Vermieter, Hausverwaltungen und Gewerbekunden bedeutet das: ein fester Ansprechpartner, klare Projektsteuerung, abgestimmte Fachgewerke und ein Ablauf, bei dem Rückbau, Technik und Ausbau sinnvoll ineinandergreifen.</p>
    <p style="font-size:17px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Im Bereich Heizung, Sanitär und Gebäudetechnik ist Radex meistergeführt durch Bernd Knoop, SHK-Meister und Betriebsleiter. Sanitärinstallation, Wasserleitungen, Abwasser, Heizungsmodernisierung, Warmwasserbereitung, Heizkörper, Fußbodenheizung und Gebäudetechnik werden dadurch fachlich verantwortet. Weitere Gewerke wie Elektrotechnik, Trockenbau, Fliesen, Bodenverlegung, Malerarbeiten, Innenausbau, Dämmung oder Schadstoffsanierung werden durch qualifizierte Fachpartner umgesetzt und von Radex koordiniert.</p>
    <p style="font-size:17px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine Kernsanierung braucht Erfahrung, weil viele entscheidende Punkte vor der fertigen Oberfläche liegen. Leitungen, Abdichtung, Elektrostruktur, Bodenaufbau, Wandaufbau, Feuchtigkeit, Schadstoffe und energetische Schwachstellen sind später nicht mehr sichtbar, bestimmen aber die Qualität der Sanierung. Deshalb ist eine saubere Planung vor dem Rückbau und eine klare Koordination während der Ausführung entscheidend.</p>
    <p style="font-size:17px;color:var(--text-light);line-height:1.75">Wer eine Immobilie im Rhein-Main-Gebiet kernsanieren möchte, kann Radex direkt unter <a href="tel:+496074960620">06074 960620</a> erreichen oder das Projekt über den <a href="/kontakt">Kontaktbogen</a> anfragen. Eine frühe Einschätzung hilft, Sanierungstiefe, Ablauf, Risiken, Kostenrahmen und sinnvolle Reihenfolge besser zu planen.</p>
    <div class="link-list" style="margin-top:24px">
      <a href="/generalunternehmer-rhein-main" class="link-pill">Generalunternehmer</a>
      <a href="/komplettsanierung-rhein-main" class="link-pill">Komplettsanierung</a>
      <a href="/teilsanierung-rhein-main" class="link-pill">Teilsanierung</a>
      <a href="/schadstoffsanierung-rhein-main" class="link-pill">Schadstoffsanierung</a>
      <a href="/heizung-sanitaer-rhein-main" class="link-pill">Heizung &amp; Sanitär</a>
    </div>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'wann-ist-eine-kernsanierung-sinnvoll',
    title: "Wann ist eine Kernsanierung sinnvoll?",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Wann ist es sinnvoll</div>
  <h2>Wann ist eine Kernsanierung sinnvoll?</h2>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine Kernsanierung ist sinnvoll, wenn eine Immobilie technisch und baulich so weit überarbeitet werden muss, dass einzelne Renovierungsmaßnahmen nicht mehr ausreichen. Das kann bei älteren Häusern, Wohnungen, Altbauten, Mehrfamilienhäusern, Gewerbeflächen, Bestandsobjekten nach Kauf oder Immobilien mit längerem Sanierungsstau der Fall sein.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:16px">Typische Auslöser für eine Kernsanierung sind:</p>
    <ul class="bullet-list" style="margin-bottom:20px">
      <li>veraltete Wasserleitungen und Abwasserleitungen</li>
      <li>stark überholte Elektrostruktur</li>
      <li>alte Heizungsanlage oder ungeeignete Wärmeverteilung</li>
      <li>mehrere nicht zusammenpassende frühere Umbauten</li>
      <li>Feuchtigkeit, Schimmel oder unklare Schadensursachen</li>
      <li>Asbestverdacht oder andere mögliche Schadstoffe</li>
      <li>stark veraltete Bäder und Küchenanschlüsse</li>
      <li>unklare Wand-, Boden- oder Deckenaufbauten</li>
      <li>neue Raumaufteilung mit größeren Eingriffen</li>
      <li>energetische Modernisierung mit tieferem Eingriff</li>
      <li>Immobilie soll vor Einzug vollständig neu aufgebaut werden</li>
      <li>Gewerbefläche soll für neue Nutzung vorbereitet werden</li>
      <li>Rückbau bis auf zentrale Bauteile oder tragende Struktur notwendig</li>
    </ul>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine Kernsanierung ist besonders häufig nach einem Immobilienkauf relevant. Käufer sehen Potenzial, Lage und Grundriss, merken aber bei genauer Prüfung, dass die technische Grundlage nicht mehr zum geplanten Anspruch passt. Wenn Bad, Heizung, Sanitär, Elektro, Innenausbau, Böden, Wände und energetische Themen gleichzeitig betroffen sind, ist eine Kernsanierung oft sinnvoller als viele Einzelmaßnahmen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Der Vorteil liegt in der Klarheit. Statt immer wieder Teilbereiche zu öffnen, wird die Immobilie einmal umfassend betrachtet. Verdeckte Probleme können erkannt, technische Installationen neu geplant und Oberflächen erst dann aufgebaut werden, wenn die Grundlage stimmt. Das reduziert spätere Nacharbeiten und schafft eine Immobilie, die technisch und funktional langfristig besser aufgestellt ist.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine Kernsanierung ist aber nicht automatisch die richtige Lösung für jedes ältere Gebäude. Manche Immobilien brauchen nur eine <a href="/komplettsanierung-rhein-main">Komplettsanierung</a> oder <a href="/teilsanierung-rhein-main">Teilsanierung</a>. Andere sind gepflegt und technisch so gut erhalten, dass ein tiefer Rückbau nicht wirtschaftlich oder notwendig wäre. Deshalb prüft Radex den tatsächlichen Zustand objektbezogen. Nicht die Bezeichnung „alt" entscheidet, sondern die Substanz, Technik, Nutzung und gewünschte Sanierungstiefe.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Wenn Sie unsicher sind, ob eine Kernsanierung notwendig ist, kann Radex Ihr Projekt früh einordnen. Unter <a href="tel:+496074960620">06074 960620</a> lässt sich klären, ob eine tiefgreifende Sanierung, eine Komplettsanierung oder eine gezielte Teilsanierung besser passt.</p>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Kostenlos beraten lassen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'kernsanierung-oder-komplettsanierung-der-wichtige-unterschied',
    title: "Kernsanierung oder Komplettsanierung – der wichtige Unterschied",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="section-label">Abgrenzung</div>
  <h2>Kernsanierung oder Komplettsanierung – der wichtige Unterschied</h2>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Die Begriffe Kernsanierung und Komplettsanierung werden oft verwechselt. Beide können umfangreich sein, aber sie meinen nicht dasselbe.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine Komplettsanierung umfasst viele oder alle zentralen Bereiche einer Immobilie. Bad, Küche, Böden, Wände, Decken, Türen, Heizung, Sanitär, Elektrokoordination und Innenausbau werden modernisiert. Dabei kann viel erneuert werden, ohne dass die Immobilie bis auf tragende oder zentrale Bauteile zurückgebaut wird.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine Kernsanierung geht tiefer. Sie umfasst meist einen stärkeren Rückbau und greift in die technische und bauliche Grundlage ein. Leitungen, Installationen, Bodenaufbauten, Innenwände, Decken, technische Anlagen und energetische Bauteile können umfassend erneuert werden. Eine Kernsanierung bedeutet häufig, dass die Immobilie innen weitgehend neu aufgebaut wird.</p>

    <div style="display:grid;grid-template-columns:1fr 1fr;gap:32px;margin:28px 0">
      <div>
        <h3 style="color:var(--navy);font-size:16px;margin-bottom:12px">Eine Komplettsanierung kann zum Beispiel sinnvoll sein, wenn:</h3>
        <ul class="bullet-list">
          <li>ein Bad vollständig saniert wird</li>
          <li>die Heizung modernisiert wird</li>
          <li>Böden, Türen, Wände und Decken erneuert werden</li>
          <li>Elektrokoordination punktuell oder umfangreich erfolgt</li>
          <li>Küchenanschlüsse vorbereitet werden</li>
          <li>Innenausbau und Oberflächen modernisiert werden</li>
          <li>eine Wohnung bezugsfertig gemacht wird</li>
        </ul>
      </div>
      <div>
        <h3 style="color:var(--navy);font-size:16px;margin-bottom:12px">Eine Kernsanierung ist eher sinnvoll, wenn zusätzlich:</h3>
        <ul class="bullet-list">
          <li>alte Leitungen vollständig ersetzt werden müssen</li>
          <li>Elektrostruktur grundlegend erneuert werden muss</li>
          <li>Bodenaufbauten entfernt und neu aufgebaut werden</li>
          <li>Innenwände oder Grundrisse stärker verändert werden</li>
          <li>Rückbau bis auf zentrale Bauteile notwendig ist</li>
          <li>Schadstoffe oder Asbestverdacht systematisch geprüft werden müssen</li>
          <li>energetische Maßnahmen tiefer in das Gebäude eingreifen</li>
          <li>Bad, Heizung, Sanitär, Elektro, Innenausbau und Struktur gemeinsam neu geplant werden</li>
        </ul>
      </div>
    </div>

    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex hilft, diese Sanierungstiefe realistisch zu bestimmen. Das ist wichtig, weil eine falsch eingeschätzte Sanierung zu Kostenverschiebungen, Verzögerungen und Enttäuschungen führen kann. Wer eine Kernsanierung plant, braucht andere Vorbereitung als bei einer einfachen Modernisierung. Rückbau, Entsorgung, Schadstoffprüfung, Statik, Leitungsführung, Materialentscheidungen und Gewerkeplanung müssen früher geklärt werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Gleichzeitig sollte der Begriff Kernsanierung nicht unnötig verwendet werden. Wenn ein Objekt keine tiefe Sanierung braucht, wäre eine Kernsanierung überdimensioniert. Radex empfiehlt deshalb nicht pauschal den größten Eingriff, sondern prüft, welche Sanierungstiefe zum Gebäude und zum Ziel passt.</p>

  <div style="text-align:center;margin-top:40px;">
    <a href="https://wa.me/491744684189" class="btn-primary gold" target="_blank" rel="noopener">Jetzt per WhatsApp anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'kernsanierung-eines-hauses-wenn-das-gebaeude-technisch-neu-aufgestellt-wird',
    title: "Kernsanierung eines Hauses – wenn das Gebäude technisch neu aufgestellt wird",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Haus kernsanieren</div>
  <h2>Kernsanierung eines Hauses – wenn das Gebäude technisch neu aufgestellt wird</h2>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine Kernsanierung eines Hauses wird häufig dann notwendig, wenn mehrere technische und bauliche Bereiche gleichzeitig überholt sind. Viele Häuser im Rhein-Main-Gebiet haben gute Lagen, solide Grundsubstanz und viel Potenzial. Trotzdem können Leitungen, Heizung, Elektrostruktur, Bad, Bodenaufbau, Keller, Dämmung oder Innenausbau so stark veraltet sein, dass eine tiefere Sanierung sinnvoll wird.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine Kernsanierung bedeutet nicht, dass ein Haus seinen Charakter verliert. Im Gegenteil: Gerade bei wertvollen Bestandsimmobilien geht es darum, die Substanz zu sichern und gleichzeitig eine moderne technische Grundlage zu schaffen. Erhaltenswerte Elemente können bestehen bleiben, wenn sie fachlich sinnvoll sind. Kritische Bereiche werden geöffnet, geprüft und neu aufgebaut.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:16px">Typische Leistungen bei einer Kernsanierung eines Hauses:</p>
    <ul class="bullet-list" style="margin-bottom:20px">
      <li>umfassender Rückbau von Oberflächen und Einbauten</li>
      <li>Prüfung und Erneuerung von Wasserleitungen</li>
      <li>Austausch oder Anpassung von Abwasserleitungen</li>
      <li>Heizungsmodernisierung und neue Wärmeverteilung</li>
      <li>Prüfung von Heizkörpern oder Fußbodenheizung</li>
      <li>Elektrokoordination mit qualifizierten Fachpartnern</li>
      <li>neue Raumaufteilung oder Innenwandanpassungen</li>
      <li>Trockenbau, Wand- und Deckenaufbau</li>
      <li>neue Bodenaufbauten und Bodenbeläge</li>
      <li>Badsanierung und Gäste-WC-Sanierung</li>
      <li>Küchenanschlüsse und technische Vorbereitung</li>
      <li>Feuchtigkeitsprüfung im Keller oder an Außenwänden</li>
      <li>Schimmel- oder Asbestverdacht einordnen</li>
      <li>energetische Maßnahmen vorbereiten oder umsetzen</li>
      <li>Koordination der Fachgewerke und Bauleitung</li>
    </ul>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Besonders vor dem Einzug ist eine Kernsanierung oft sinnvoll. Wenn ein Haus leer steht, lassen sich Rückbau, Leitungen, Elektrokoordination, <a href="/badsanierung-rhein-main">Bad</a>, Heizung und Innenausbau deutlich besser umsetzen als im bewohnten Zustand. Staubschutz, Materialtransport, Entsorgung und Gewerkeabfolge sind einfacher planbar. Gleichzeitig ist diese Phase entscheidend, weil Fehler in der Reihenfolge später teuer werden können.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex prüft vor einer Kernsanierung, welche Bereiche wirklich betroffen sind. Gibt es alte Leitungen? Wie ist die Heizung aufgebaut? Welche Wand- und Bodenaufbauten sind vorhanden? Gibt es Feuchtigkeit? Besteht Schadstoffverdacht? Welche Räume sollen verändert werden? Welche energetischen Maßnahmen passen zum Gebäude? Welche Arbeiten müssen zwingend vor dem Ausbau erfolgen?</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine Kernsanierung eines Hauses ist ein anspruchsvolles Projekt. Sie sollte nicht aus vielen Einzelentscheidungen bestehen, sondern aus einem Gesamtplan. Radex übernimmt dabei die Rolle des koordinierenden <a href="/generalunternehmer-rhein-main">Generalunternehmers</a> und sorgt dafür, dass SHK-Leistungen, Elektrofachpartner, Innenausbau, Trockenbau, Fliesen, Böden, Malerarbeiten und weitere Fachgewerke sinnvoll zusammenarbeiten.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Wenn Sie ein Haus im Rhein-Main-Gebiet kernsanieren möchten, sprechen Sie früh mit Radex. Telefon: <a href="tel:+496074960620">06074 960620</a>.</p>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Unverbindlich anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'kernsanierung-einer-wohnung-wenn-mehr-als-bad-boden-und-waende-betroffen-sind',
    title: "Kernsanierung einer Wohnung – wenn mehr als Bad, Boden und Wände betroffen sind",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="section-label">Wohnung kernsanieren</div>
  <h2>Kernsanierung einer Wohnung – wenn mehr als Bad, Boden und Wände betroffen sind</h2>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine Wohnung zu kernsanieren bedeutet, tiefer einzugreifen als bei einer klassischen Wohnungssanierung. Das ist besonders relevant, wenn eine Eigentumswohnung nach Kauf, Erbschaft, langer Vermietung oder vor Eigennutzung technisch umfassend erneuert werden soll. Oft sind Bad, Küche, Böden, Wände, Türen, Heizkörper, Elektrostruktur, Leitungen und Innenausbau betroffen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bei einer Kernsanierung einer Wohnung müssen zusätzliche Rahmenbedingungen beachtet werden. Die Wohnung liegt häufig in einem Mehrfamilienhaus. Hausordnung, Nachbarn, Treppenhaus, Aufzug, Schallschutz, Leitungsführung, Eigentümergemeinschaft und Hausverwaltung spielen eine Rolle. Rückbau, Materialtransport, Entsorgung, Bauzeiten und Arbeiten an gemeinschaftlichen Bereichen müssen sauber abgestimmt werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:16px">Typische Themen bei einer Wohnungskernsanierung:</p>
    <ul class="bullet-list" style="margin-bottom:20px">
      <li>vollständiger Rückbau alter Oberflächen</li>
      <li>Badsanierung mit Leitungsprüfung</li>
      <li>Küchenanschlüsse neu planen</li>
      <li>Elektrostruktur und Steckdosenkonzept koordinieren</li>
      <li>Heizkörper prüfen oder austauschen</li>
      <li>alte Bodenbeläge und Kleber bewerten</li>
      <li>Wände und Decken neu aufbauen</li>
      <li>Türen, Zargen und Sockelleisten erneuern</li>
      <li>Trockenbau für neue Raumaufteilung</li>
      <li>Schadstoffverdacht bei alten Materialien prüfen</li>
      <li>bezugsfertige oder vermietbare Übergabe vorbereiten</li>
    </ul>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine Wohnungskernsanierung ist besonders sinnvoll, wenn die Wohnung leer steht. Vor dem Einzug oder vor Neuvermietung können die Arbeiten effizienter umgesetzt werden. Wenn die Wohnung bereits bewohnt ist, muss der Ablauf genauer in Abschnitte aufgeteilt werden. In beiden Fällen hilft ein Generalunternehmer, weil viele Gewerke auf engem Raum arbeiten und die Reihenfolge entscheidend ist.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Ein typischer Fehler bei Wohnungssanierungen ist, zuerst auf Oberflächen zu schauen. Neue Böden, glatte Wände und moderne Türen sind wichtig, aber sie sollten nicht vor technischen Fragen stehen. Wenn das Bad später geöffnet werden muss, weil Leitungen nicht geprüft wurden, entstehen doppelte Kosten. Wenn Elektroanschlüsse fehlen, müssen fertige Wände wieder bearbeitet werden. Wenn alte Kleber oder Bodenbeläge Schadstoffverdacht haben, darf Rückbau nicht unkoordiniert erfolgen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex betrachtet die Wohnung als Gesamtprojekt. Welche Arbeiten müssen zuerst passieren? Welche Fachpartner werden gebraucht? Welche SHK-Leistungen sind erforderlich? Wo muss Elektro früh geplant werden? Was muss mit der Hausverwaltung abgestimmt werden? Welche Oberflächen kommen erst zum Schluss?</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Für Eigentümer, Vermieter und Hausverwaltungen im Rhein-Main-Gebiet ist eine strukturierte Wohnungskernsanierung besonders wertvoll, wenn Wert, Vermietbarkeit oder Eigennutzung langfristig gesichert werden sollen. Radex ist unter <a href="tel:+496074960620">06074 960620</a> erreichbar.</p>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Beratungsgespräch vereinbaren</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'kernsanierung-nach-immobilienkauf-vor-dem-einzug-richtig-tief-pruefen',
    title: "Kernsanierung nach Immobilienkauf – vor dem Einzug richtig tief prüfen",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Nach dem Kauf</div>
  <h2>Kernsanierung nach Immobilienkauf – vor dem Einzug richtig tief prüfen</h2>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine der häufigsten Situationen für eine Kernsanierung ist der Kauf einer älteren Immobilie. Käufer sehen Lage, Grundstück, Grundriss und Potenzial. Nach genauerer Betrachtung zeigt sich jedoch, dass die Immobilie nicht nur renoviert, sondern technisch grundlegend neu aufgestellt werden sollte.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine Kernsanierung nach Hauskauf oder Wohnungskauf kann sinnvoll sein, wenn viele zentrale Bereiche gleichzeitig betroffen sind. Das Bad ist veraltet, Leitungen sind alt, Elektro entspricht nicht mehr heutiger Nutzung, Böden und Wände sind mehrfach überarbeitet, die Heizung muss geprüft werden, Keller oder Feuchtigkeit werfen Fragen auf und alte Materialien können Schadstoffverdacht auslösen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Gerade vor dem Einzug bietet sich die Chance, diese Themen geordnet anzugehen. Räume sind leer, Rückbau ist einfacher, Material kann besser transportiert werden, und mehrere Gewerke können sinnvoll koordiniert werden. Wird zu spät saniert, müssen Möbel, Alltag und bewohnte Räume geschützt oder wieder ausgeräumt werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:16px">Typische Fragen vor einer Kernsanierung nach Kauf:</p>
    <ul class="bullet-list" style="margin-bottom:20px">
      <li>Müssen Wasserleitungen komplett erneuert werden?</li>
      <li>Reicht die bestehende Elektrostruktur noch aus?</li>
      <li>Soll die Heizung modernisiert werden?</li>
      <li>Sind Heizkörper oder Fußbodenheizung passend?</li>
      <li>Gibt es Feuchtigkeit oder Schimmel?</li>
      <li>Besteht Asbestverdacht bei Bodenbelägen, Klebern oder Dämmstoffen?</li>
      <li>Soll die Raumaufteilung verändert werden?</li>
      <li>Sind Bäder und Gäste-WCs technisch neu aufzubauen?</li>
      <li>Welche energetischen Maßnahmen sind sinnvoll?</li>
      <li>Welche Arbeiten müssen vor Einzug abgeschlossen sein?</li>
    </ul>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex hilft Käufern, diese Fragen zu ordnen. Eine Kernsanierung sollte nicht aus spontanen Einzelentscheidungen entstehen. Sie braucht eine klare Priorisierung: Rückbau, Prüfung, Technik, Rohinstallation, Innenausbau, Abdichtung, Oberflächen, Endmontage und Übergabe.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bei einer Kernsanierung nach Kauf ist auch der Kostenrahmen wichtig. Viele Käufer möchten vorab verstehen, welche Maßnahmen zwingend notwendig sind und welche später folgen können. Radex kann nach einer Bestandsaufnahme helfen, den Umfang realistischer einzuschätzen. Das ersetzt keine pauschalen Quadratmeterpreise, schafft aber eine bessere Grundlage für Entscheidungen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine gute Kernsanierung nach Kauf verbindet Wertschätzung für das Objekt mit technischer Klarheit. Nicht alles Alte ist schlecht. Nicht alles Neue ist automatisch sinnvoll. Entscheidend ist, wo echte technische Notwendigkeit besteht und wo eine intelligente Modernisierung reicht.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Wer eine Immobilie gekauft hat und eine Kernsanierung im Rhein-Main-Gebiet plant, sollte Radex früh kontaktieren. Unter <a href="tel:+496074960620">06074 960620</a> kann der erste Schritt abgestimmt werden.</p>

  <div style="text-align:center;margin-top:40px;">
    <a href="https://wa.me/491744684189" class="btn-primary gold" target="_blank" rel="noopener">Angebot anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'rueckbau-schadstoffpruefung-und-sichere-vorbereitung',
    title: "Rückbau, Schadstoffprüfung und sichere Vorbereitung",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="section-label">Rückbau &amp; Schadstoffe</div>
  <h2>Rückbau, Schadstoffprüfung und sichere Vorbereitung</h2>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Der Rückbau ist bei einer Kernsanierung besonders wichtig. Bevor neue Leitungen, Wände, Böden, Bäder oder Technik aufgebaut werden können, müssen alte Schichten entfernt und bewertet werden. Dabei geht es nicht nur um Abriss, sondern um fachlich saubere Vorbereitung.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bei älteren Immobilien können beim Rückbau Materialien auftauchen, die heute anders bewertet werden als zum Zeitpunkt des Einbaus. Alte Bodenbeläge, Kleber, Spachtelmassen, Dämmstoffe, Rohrisolierungen, Brandschutzplatten oder Deckenmaterialien können Schadstoffverdacht auslösen. Auch Schimmel oder Feuchtigkeit werden oft erst sichtbar, wenn Oberflächen geöffnet werden.</p>

    <div class="info-box">
      <strong style="display:block;color:var(--navy);margin-bottom:6px">Zertifizierte Kompetenz bei Schadstoffen</strong>
      Radex ist zertifiziert für Schimmel- und <a href="/asbestsanierung-rhein-main">Asbestsanierung</a> und verfügt über Sachkunde nach TRGS 519. Dadurch können Verdachtsfälle fachlich eingeordnet und in den Sanierungsablauf integriert werden. Wichtig ist: Verdächtige Materialien sollten nicht eigenständig gebrochen, geschliffen, gebohrt oder entfernt werden. Erst prüfen, dann handeln.
    </div>

    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:16px">Typische Punkte beim Rückbau:</p>
    <ul class="bullet-list" style="margin-bottom:20px">
      <li>alte Fliesen und Sanitärobjekte entfernen</li>
      <li>Bodenbeläge und Kleber bewerten</li>
      <li>abgehängte Decken prüfen</li>
      <li>alte Rohrisolierungen erkennen</li>
      <li>Wand- und Deckenaufbauten öffnen</li>
      <li>Feuchtigkeit und Schimmel einordnen</li>
      <li>Schadstoffverdacht vor staubintensiven Arbeiten klären</li>
      <li>Entsorgung fachgerecht vorbereiten</li>
      <li>Rückbau in die weitere Planung integrieren</li>
    </ul>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Ein sauberer Rückbau schafft Klarheit. Erst wenn verdeckte Bereiche sichtbar sind, können Leitungswege, Bodenaufbau, Feuchtigkeit und technische Anschlussdetails verlässlich bewertet werden. Deshalb ist Rückbau nicht nur ein grober erster Schritt, sondern Teil der Planung.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bei Kernsanierungen im Rhein-Main-Gebiet übernimmt Radex die Koordination dieser Phase. Je nach Projekt werden Fachpartner eingebunden, Prüfungen vorbereitet und die nächsten Schritte abgestimmt. So wird verhindert, dass der Ausbau beginnt, bevor die Grundlage geklärt ist.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Wenn bei Ihrer Immobilie Schimmel, Asbestverdacht, alte Bodenbeläge oder unklare Materialien vorhanden sind, sprechen Sie Radex früh an. Telefon: <a href="tel:+496074960620">06074 960620</a>.</p>

    <div class="link-list">
      <a href="/schadstoffsanierung-rhein-main" class="link-pill">Schadstoffsanierung</a>
      <a href="/asbestsanierung-rhein-main" class="link-pill">Asbestsanierung</a>
    </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Kostenlos beraten lassen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'heizung-und-sanitaer-bei-einer-kernsanierung',
    title: "Heizung und Sanitär bei einer Kernsanierung",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Heizung &amp; Sanitär</div>
  <h2>Heizung und Sanitär bei einer Kernsanierung</h2>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Heizung und Sanitär gehören zu den wichtigsten technischen Bereichen einer Kernsanierung. Wenn Wände, Böden und Bäder ohnehin geöffnet werden, ist das der richtige Zeitpunkt, Wasserleitungen, Abwasserleitungen, Warmwasser, Heizkörper, Heizungsanlage und Wärmeverteilung zu prüfen. Alte Installationen hinter neuen Oberflächen zu belassen, kann später teuer werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Im Bereich <a href="/heizung-sanitaer-rhein-main">Heizung, Sanitär und Gebäudetechnik</a> ist Radex meistergeführt durch Bernd Knoop, SHK-Meister und Betriebsleiter. Für Kernsanierungen ist das besonders relevant, weil SHK-Arbeiten nicht isoliert betrachtet werden dürfen. Wasserleitungen beeinflussen Bad, Küche, Bodenaufbau und Wandaufbau. Abwasserleitungen bestimmen Gefälle und Leitungsführung. Heizkörper beeinflussen Raumaufteilung und Oberflächen. Eine neue Heizung muss zum Gebäudezustand passen.</p>

    <div class="gewerk-grid" style="grid-template-columns:repeat(2,1fr);margin-bottom:24px">
      <div class="gewerk-card">
        <div class="gewerk-icon">
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="var(--gold)" stroke-width="2" aria-hidden="true"><path d="M12 2v6M12 22v-6M4.93 4.93l4.24 4.24M14.83 14.83l4.24 4.24M2 12h6M22 12h-6M4.93 19.07l4.24-4.24M14.83 9.17l4.24-4.24"/></svg>
        </div>
        <h3>SHK-Leistungen bei Kernsanierungen</h3>
        <p>Wasserleitungen erneuern, Abwasserleitungen prüfen oder ersetzen, Bad und Gäste-WC technisch neu planen, Küchenanschlüsse vorbereiten, Warmwasserbereitung bewerten, Heizungsmodernisierung planen, Heizkörper tauschen oder versetzen, Fußbodenheizung in Teilbereichen prüfen, Wärmepumpe oder Brennwerttechnik einordnen, Wärmeverteilung mit energetischen Maßnahmen abstimmen.</p>
      </div>
      <div class="gewerk-card">
        <div class="gewerk-icon">
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="var(--gold)" stroke-width="2" aria-hidden="true"><circle cx="12" cy="12" r="10"/><path d="M12 8v4l3 3"/></svg>
        </div>
        <h3>Früh einbinden spart spätere Kosten</h3>
        <p>Bei einer Kernsanierung ist besonders wichtig, dass SHK früh in die Planung eingebunden wird. Wenn der Innenausbau bereits läuft und Leitungen erst später geklärt werden, entstehen Verzögerungen und Nacharbeiten. Wenn ein Bad gestaltet wird, bevor Leitungswege und Abdichtung feststehen, kann die Planung nicht verlässlich umgesetzt werden.</p>
      </div>
    </div>

    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex verbindet SHK-Meisterkompetenz mit der Koordination der weiteren Gewerke. Elektro, Trockenbau, Fliesen, Boden, Malerarbeiten und Innenausbau werden passend abgestimmt. Dadurch entsteht eine technische Grundlage, auf der die fertigen Oberflächen sicher aufgebaut werden können.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Wer eine Kernsanierung mit Bad, Heizung oder Sanitär im Rhein-Main-Gebiet plant, kann Radex unter <a href="tel:+496074960620">06074 960620</a> erreichen.</p>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Heizungsberatung anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'elektrokoordination-bei-kernsanierungen',
    title: "Elektrokoordination bei Kernsanierungen",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="section-label">Elektrokoordination</div>
  <h2>Elektrokoordination bei Kernsanierungen</h2>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bei einer Kernsanierung wird die Elektrostruktur häufig grundlegend neu gedacht. Moderne Immobilien brauchen deutlich mehr als ein paar Steckdosen. Küche, Bad, Homeoffice, Netzwerk, Beleuchtung, Außenbereiche, Smart-Home-Vorbereitung, Sicherheitsbereiche, Ladeinfrastruktur und leistungsfähige Geräte müssen früh geplant werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex führt Elektroarbeiten nicht als eigener Elektro-Meisterbetrieb aus, sondern koordiniert qualifizierte Elektrofachpartner. Diese rechtlich saubere Trennung ist wichtig. Radex sorgt dafür, dass Elektroarbeiten im Gesamtablauf rechtzeitig berücksichtigt werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:16px">Typische Elektrothemen bei Kernsanierungen:</p>
    <ul class="bullet-list" style="margin-bottom:20px">
      <li>Unterverteilung und Sicherungskasten prüfen</li>
      <li>Stromkreise neu planen</li>
      <li>Steckdosen und Schalter sinnvoll positionieren</li>
      <li>Badbeleuchtung und Sicherheitsbereiche abstimmen</li>
      <li>Küchenanschlüsse vorbereiten</li>
      <li>Netzwerk und Homeoffice planen</li>
      <li>Beleuchtungskonzept für Wohnräume, Flure und Treppen</li>
      <li>Elektrokoordination bei Wandöffnungen</li>
      <li>Vorbereitung für Wallbox oder spätere Erweiterungen</li>
      <li>Abstimmung mit Trockenbau, Boden und Innenausbau</li>
    </ul>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Der richtige Zeitpunkt ist entscheidend. Elektroplanung gehört vor Trockenbau, vor geschlossene Wände, vor Fliesen und vor fertige Oberflächen. Bei einer Kernsanierung kann die Elektrostruktur besonders gut vorbereitet werden, weil viele Bereiche ohnehin geöffnet sind. Das ist eine Chance, die spätere Nutzung deutlich komfortabler zu machen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Fehler entstehen häufig, wenn Elektro zu spät behandelt wird. Dann fehlen Steckdosen an wichtigen Stellen, Lichtanschlüsse sitzen ungünstig, Küchenplanung und Elektro passen nicht zusammen oder Wände müssen erneut geöffnet werden. Radex koordiniert diese Schnittstellen früh.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Gerade bei Sanierung nach Kauf oder vor Einzug lohnt sich eine zukunftsfähige Elektrokoordination. Was heute nicht geplant wird, ist später oft nur mit Aufwand nachrüstbar. Dazu gehören Homeoffice, Netzwerk, moderne Küche, Badtechnik, Außenbereiche oder Ladevorbereitung. Wenn Ihre Kernsanierung Elektroarbeiten umfasst, plant Radex die Fachpartnerkoordination von Beginn an mit ein.</p>

  <div style="text-align:center;margin-top:40px;">
    <a href="https://wa.me/491744684189" class="btn-primary gold" target="_blank" rel="noopener">Elektroplanung besprechen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'innenausbau-raumaufteilung-und-neue-nutzung',
    title: "Innenausbau, Raumaufteilung und neue Nutzung",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Innenausbau &amp; Raumaufteilung</div>
  <h2>Innenausbau, Raumaufteilung und neue Nutzung</h2>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine Kernsanierung bietet die Möglichkeit, Räume neu zu denken. Viele Bestandsimmobilien haben gute Flächen, aber nicht immer die passende Aufteilung für heutiges Wohnen oder Arbeiten. Eine Küche soll geöffnet werden, ein Bad vergrößert werden, ein Homeoffice entstehen, ein Flur effizienter genutzt werden oder eine Gewerbefläche eine neue Struktur bekommen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Innenausbau ist bei einer Kernsanierung nicht nur Oberflächenarbeit. Er verbindet Grundriss, Trockenbau, Wandaufbau, Decken, Böden, Türen, Stauraum, Nischen, Akustik, Licht und technische Leitungsführung. Deshalb muss Innenausbau eng mit Heizung, Sanitär, Elektrokoordination und energetischen Maßnahmen abgestimmt werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:16px">Typische Innenausbau-Themen:</p>
    <ul class="bullet-list" style="margin-bottom:20px">
      <li>neue Raumaufteilung</li>
      <li>Trockenbauwände setzen oder entfernen</li>
      <li>Wanddurchbruch prüfen</li>
      <li>Bad vergrößern oder neu positionieren</li>
      <li>Küche öffnen oder technisch vorbereiten</li>
      <li>Homeoffice oder Gästezimmer schaffen</li>
      <li>Bodenaufbau erneuern</li>
      <li>Decken abhängen oder glätten</li>
      <li>Türen, Zargen und Sockelleisten erneuern</li>
      <li>Nischen und Stauraum integrieren</li>
      <li>Oberflächen hochwertig fertigstellen</li>
    </ul>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Wenn eine Wand entfernt werden soll, muss geprüft werden, ob sie tragend ist und ob Leitungen verlaufen. Wenn ein Bad vergrößert wird, müssen Sanitärleitungen, Abdichtung, Lüftung und Elektrokoordination passen. Wenn ein Boden neu aufgebaut wird, müssen Aufbauhöhe, Übergänge, Schallschutz und Heizflächen berücksichtigt werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex koordiniert diese Fragen im Gesamtprojekt. So wird verhindert, dass Innenausbau nur optisch geplant wird, ohne die Technik mitzudenken. Gerade bei Kernsanierungen ist diese Verbindung entscheidend, weil viele Bauteile neu aufgebaut werden und spätere Korrekturen aufwendig wären.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Wer bei einer Kernsanierung neue Raumaufteilung, Innenausbau oder hochwertigen Ausbau plant, kann Radex früh einbinden. Eine abgestimmte Planung spart später Zeit und vermeidet unnötige Eingriffe.</p>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Beratungsgespräch vereinbaren</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'energetische-massnahmen-bei-einer-kernsanierung',
    title: "Energetische Maßnahmen bei einer Kernsanierung",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="section-label">Energetische Maßnahmen</div>
  <h2>Energetische Maßnahmen bei einer Kernsanierung</h2>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine Kernsanierung ist häufig der richtige Zeitpunkt, energetische Maßnahmen zu prüfen. Wenn Bauteile geöffnet, Heizungen bewertet, Innenausbau geplant und Technik erneuert wird, lassen sich Energieeffizienz, Komfort und Zukunftsfähigkeit sinnvoll einordnen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Energetische Sanierung bedeutet jedoch nicht, wahllos einzelne Maßnahmen umzusetzen. Eine neue Heizung allein löst nicht jedes Problem. Neue Fenster verändern das Lüftungsverhalten. Dämmmaßnahmen müssen zum Gebäude passen. Eine Wärmepumpe braucht passende Heizflächen und möglichst niedrige Vorlauftemperaturen. Lüftung und Feuchtigkeitsschutz dürfen nicht vergessen werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:16px">Typische energetische Themen bei Kernsanierungen:</p>
    <ul class="bullet-list" style="margin-bottom:20px">
      <li>Heizungsmodernisierung</li>
      <li>Wärmepumpe prüfen</li>
      <li>Heizkörper oder Heizflächen optimieren</li>
      <li>Kellerdecke dämmen</li>
      <li>Dachboden oder Dachbereich prüfen</li>
      <li>Gebäudehülle bewerten</li>
      <li>Lüftung und Feuchtigkeitsschutz berücksichtigen</li>
      <li>Warmwasserbereitung abstimmen</li>
      <li>energetische Maßnahmen mit Innenausbau verbinden</li>
      <li>Förderung mit Energieberatung vorbereiten</li>
    </ul>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Förderprogramme über KfW oder BAFA können je nach Maßnahme relevant sein. Die Bedingungen ändern sich regelmäßig und sollten vor Beginn geprüft werden. Für verbindliche Förderberatung sollte ein zugelassener Energieberater eingebunden werden. Radex kann die bauliche Umsetzung und Gewerkeabstimmung übernehmen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bei einer Kernsanierung ist energetische Planung besonders sinnvoll, weil spätere Nachrüstung oft aufwendiger ist. Wenn Böden, Wände oder Decken ohnehin geöffnet werden, können Dämmung, Leitungen, Heizflächen oder Lüftung besser berücksichtigt werden. Wichtig ist aber, dass die Maßnahmen technisch zusammenpassen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Radex hilft, energetische Themen in den Sanierungsablauf einzubinden. So entstehen keine isolierten Einzelmaßnahmen, sondern ein abgestimmtes Konzept aus Heizung, Gebäudezustand, Innenausbau und Nutzung.</p>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Energetische Sanierung besprechen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'ablauf-einer-kernsanierung-mit-radex',
    title: "Ablauf einer Kernsanierung mit Radex",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">So läuft es ab</div>
  <h2>Ablauf einer Kernsanierung mit Radex</h2>
  <p style="font-size:16px;color:var(--text-light);line-height:1.75;max-width:720px;margin-bottom:8px">Eine Kernsanierung braucht klare Struktur. Ohne Ablaufplanung können Rückbau, Prüfung, Technik und Ausbau schnell unübersichtlich werden. Radex führt Kernsanierungen deshalb in geordneten Schritten.</p>

  <ol class="phase-list" style="max-width:800px">
    <li>
      <div>
        <strong>Erstgespräch</strong>
        Im ersten Gespräch werden Objektart, Zustand, Ziel, Nutzung, Zeitrahmen und gewünschter Sanierungsumfang geklärt. Geht es um ein Haus, eine Wohnung, einen Altbau, ein Mehrfamilienhaus oder eine Gewerbefläche? Ist das Objekt leer oder bewohnt? Soll vor Einzug saniert werden?
      </div>
    </li>
    <li>
      <div>
        <strong>Bestandsaufnahme</strong>
        Bei einer Kernsanierung ist die Bestandsaufnahme besonders wichtig. Radex betrachtet Bad, Heizung, Sanitär, Leitungen, Böden, Wände, Decken, Elektrokoordination, Feuchtigkeit, mögliche Schadstoffe, Raumaufteilung und energetische Themen.
      </div>
    </li>
    <li>
      <div>
        <strong>Sanierungstiefe festlegen</strong>
        Anschließend wird geklärt, ob tatsächlich eine Kernsanierung notwendig ist oder ob eine Komplettsanierung bzw. Teilsanierung ausreicht. Diese Unterscheidung schützt vor zu großem oder zu kleinem Eingriff.
      </div>
    </li>
    <li>
      <div>
        <strong>Rückbau und Prüfung planen</strong>
        Rückbau, Entsorgung, Schadstoffverdacht, Materialprüfung und Schutzmaßnahmen werden vorbereitet. Bei Bedarf werden Fachpartner eingebunden.
      </div>
    </li>
    <li>
      <div>
        <strong>Technik und Rohinstallation</strong>
        SHK, Elektrokoordination, Leitungen, Heizung, Warmwasser, Bad, Küche und weitere technische Grundlagen werden geplant und umgesetzt, bevor Oberflächen geschlossen werden.
      </div>
    </li>
    <li>
      <div>
        <strong>Innenausbau und Aufbau</strong>
        Trockenbau, Bodenaufbau, Wände, Decken, Türen, Fliesen, Oberflächen und Innenausbau folgen auf die technische Grundlage.
      </div>
    </li>
    <li>
      <div>
        <strong>Endmontage und Übergabe</strong>
        Zum Schluss werden Bad, Sanitär, Oberflächen, Türen, Sockelleisten und weitere Endleistungen fertiggestellt. Das Projekt wird geprüft und übergeben.
      </div>
    </li>
  </ol>

  <div class="info-box" style="margin-top:32px">
    Während der gesamten Sanierung bleibt Radex zentraler Ansprechpartner. Das ist besonders wichtig, weil bei Kernsanierungen im Bestand immer Befunde auftreten können, die erst nach Öffnung sichtbar werden.
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="https://wa.me/491744684189" class="btn-primary gold" target="_blank" rel="noopener">Ablauf besprechen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'kernsanierung-im-rhein-main-gebiet-regionale-erfahrung-fuer-anspruchsvolle-besta',
    title: "Kernsanierung im Rhein-Main-Gebiet – regionale Erfahrung für anspruchsvolle Bestandsimmobilien",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="section-label">Einsatzgebiet</div>
  <h2>Kernsanierung im Rhein-Main-Gebiet – regionale Erfahrung für anspruchsvolle Bestandsimmobilien</h2>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex sitzt in Rödermark und begleitet Kernsanierungen im Rhein-Main-Gebiet. Die Region ist vielfältig: städtische Wohnungen, Einfamilienhäuser in gewachsenen Wohnlagen, Altbauten, Mehrfamilienhäuser, hochwertige Bestandsimmobilien, Gewerbeflächen, Praxen und Objekte nach Kauf oder Erbschaft.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">In Frankfurt am Main, Offenbach am Main, Darmstadt, Hanau, Wiesbaden, Mainz, Aschaffenburg, Bad Homburg, Neu-Isenburg, Dreieich, Langen, Rodgau, Dietzenbach, Heusenstamm, Obertshausen, Mühlheim am Main, Seligenstadt, Maintal, Rüsselsheim, Groß-Gerau, Eschborn, Hofheim, Bad Soden, Kronberg, Königstein und Rödermark können Kernsanierungen sehr unterschiedlich aussehen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine Wohnung in einem Mehrfamilienhaus braucht andere Logistik als ein freistehendes Haus. Ein hochwertiger Bestand in Kronberg, Königstein oder Bad Soden stellt andere Anforderungen an Materialwahl und Gestaltung als eine wirtschaftlich geplante Sanierung nach Mieterwechsel. Ein Haus in Rödermark, Rodgau oder Langen bringt andere technische Fragen mit als eine Gewerbefläche in Eschborn oder Frankfurt.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Radex plant deshalb objektbezogen. Die regionale Erfahrung hilft, typische Gebäudesituationen, Eigentümerziele und Sanierungsabläufe besser einzuordnen. Gleichzeitig bleibt jede Kernsanierung individuell.</p>
    <div class="link-list">
      <a href="/einsatzgebiete-rhein-main" class="link-pill">Alle Einsatzgebiete</a>
      <a href="/sanierung-rhein-main" class="link-pill">Sanierung Rhein-Main</a>
      <a href="/kontakt" class="link-pill">Kontakt aufnehmen</a>
    </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Beratung anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'warum-radex-fuer-ihre-kernsanierung',
    title: "Warum Radex für Ihre Kernsanierung?",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Warum Radex</div>
  <h2>Warum Radex für Ihre Kernsanierung?</h2>
  <p style="font-size:16px;color:var(--text-light);line-height:1.75;max-width:720px;margin-bottom:28px">Eine Kernsanierung braucht Vertrauen, technische Erfahrung und eine klare Projektsteuerung. Radex verbindet regionale Nähe, SHK-Meisterkompetenz, Erfahrung mit Bestandsimmobilien und koordinierte Fachpartner. Dadurch eignet sich Radex besonders für Projekte, bei denen Rückbau, Technik und Ausbau eng zusammenhängen.</p>
  <ul class="trust-list">
    <li>
      <div class="tl-icon"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--gold)" stroke-width="2.5" aria-hidden="true"><polyline points="20 6 9 17 4 12"/></svg></div>
      <div><strong>Ein Ansprechpartner</strong>Kunden müssen nicht jedes Gewerk einzeln suchen, beauftragen und koordinieren. Radex führt das Projekt als <a href="/generalunternehmer-rhein-main">Generalunternehmer</a>.</div>
    </li>
    <li>
      <div class="tl-icon"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--gold)" stroke-width="2.5" aria-hidden="true"><polyline points="20 6 9 17 4 12"/></svg></div>
      <div><strong>SHK-Meisterkompetenz</strong>Heizung, Sanitär und Gebäudetechnik werden unter Meisterverantwortung durch Bernd Knoop, SHK-Meister und Betriebsleiter, geführt. Das ist besonders wichtig bei Leitungen, Bädern, Warmwasser, Heizung und Gebäudetechnik.</div>
    </li>
    <li>
      <div class="tl-icon"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--gold)" stroke-width="2.5" aria-hidden="true"><polyline points="20 6 9 17 4 12"/></svg></div>
      <div><strong>Koordinierte Fachpartner</strong>Elektro, Trockenbau, Fliesen, Böden, Malerarbeiten, Innenausbau, Dämmung und weitere Gewerke werden über qualifizierte Fachbetriebe umgesetzt.</div>
    </li>
    <li>
      <div class="tl-icon"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--gold)" stroke-width="2.5" aria-hidden="true"><polyline points="20 6 9 17 4 12"/></svg></div>
      <div><strong>Erfahrung im Bestand</strong>Radex kennt typische Herausforderungen bei Kernsanierungen: alte Leitungen, Feuchtigkeit, Schadstoffe, unklare Wandaufbauten, gewachsene Grundrisse und technische Schnittstellen.</div>
    </li>
    <li>
      <div class="tl-icon"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--gold)" stroke-width="2.5" aria-hidden="true"><polyline points="20 6 9 17 4 12"/></svg></div>
      <div><strong>Schimmel- und Asbestkompetenz</strong>Radex ist zertifiziert für Schimmel- und <a href="/asbestsanierung-rhein-main">Asbestsanierung</a> und verfügt über Sachkunde nach TRGS 519.</div>
    </li>
    <li>
      <div class="tl-icon"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--gold)" stroke-width="2.5" aria-hidden="true"><polyline points="20 6 9 17 4 12"/></svg></div>
      <div><strong>Strukturierter Ablauf</strong>Rückbau, Prüfung, Technik, Innenausbau und Übergabe werden geordnet geführt – von der Bestandsaufnahme bis zur Abnahme.</div>
    </li>
    <li>
      <div class="tl-icon"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--gold)" stroke-width="2.5" aria-hidden="true"><polyline points="20 6 9 17 4 12"/></svg></div>
      <div><strong>Regionale Nähe</strong>Als Unternehmen aus Rödermark ist Radex im Rhein-Main-Gebiet schnell erreichbar und regional verankert.</div>
    </li>
    <li>
      <div class="tl-icon"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--gold)" stroke-width="2.5" aria-hidden="true"><polyline points="20 6 9 17 4 12"/></svg></div>
      <div><strong>Realistische Beratung</strong>Nicht jede Immobilie braucht eine Kernsanierung. Radex prüft, ob Kernsanierung, <a href="/komplettsanierung-rhein-main">Komplettsanierung</a>, <a href="/teilsanierung-rhein-main">Teilsanierung</a> oder Etappenlösung passt.</div>
    </li>
  </ul>

  <div class="info-box" style="margin-top:32px">
    Wenn Sie eine Immobilie kernsanieren möchten, sprechen Sie früh mit Radex. Unter <a href="tel:+496074960620">06074 960620</a> oder über den <a href="/kontakt">Kontaktbogen</a> können Sie Ihr Projekt unverbindlich anfragen.
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Unverbindlich anfragen</a>
  </div>
</div>` }}
      />
    ),
  }
];

export const kernsanierungLegacyFaqs = [];
