/* Auto-generated by scripts/build-mieterausbau-legacy.mjs – do not edit by hand. */
/* eslint-disable react/no-danger */

export const mieterausbauLegacySections = [
  {
    id: 'mieterausbau-ist-mehr-als-renovierung',
    title: "Mieterausbau ist mehr als Renovierung",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Mieterausbau ist mehr als Renovierung</div>
  <h2>Mieterausbau ist mehr als Renovierung</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Mieterausbau bedeutet deutlich mehr als neue Farbe an der Wand. Eine Bürofläche braucht eine andere Raumaufteilung als eine Praxis. Ein Ladenlokal stellt andere Anforderungen an Licht, Bodenbelag und Kundenwege als eine Servicefläche. Eine Teeküche, ein Sanitärbereich, zusätzliche Steckdosen, Trennwände, Schallschutz, Heizkörper, Netzwerkanschlüsse oder neue Bodenbeläge müssen technisch und zeitlich zusammenpassen. Wenn diese Gewerke nicht sauber koordiniert sind, entstehen Verzögerungen, doppelte Arbeiten und unnötige Kosten.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Viele Gewerbeflächen werden nach einem Mieterwechsel zunächst als „leer" betrachtet. Tatsächlich ist eine leere Fläche aber selten automatisch bereit für den nächsten Nutzer. Alte Trennwände passen nicht zum neuen Grundriss. Steckdosen sitzen an der falschen Stelle. Der Bodenbelag ist abgenutzt. Sanitärbereiche entsprechen nicht mehr der Nutzung. Beleuchtung ist veraltet. Teeküchenanschlüsse fehlen. Die Technik wurde über Jahre nur punktuell ergänzt.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Ein professioneller Mieterausbau beginnt deshalb nicht mit der Frage, welche Farbe gestrichen wird. Er beginnt mit der Frage, welche Nutzung die Fläche künftig erfüllen soll. Arbeiten dort Büroangestellte? Kommen Kunden in die Fläche? Wird eine Praxis eingerichtet? Braucht der Mieter Lagerzonen, Besprechungsräume, Empfangsbereiche, Personalräume oder besondere Anschlüsse? Erst wenn diese Anforderungen geklärt sind, lässt sich sinnvoll planen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex betrachtet den Mieterausbau als Gesamtprojekt. Rückbau, Raumaufteilung, Trockenbau, Elektrokoordination, Sanitär, Heizung, Boden, Oberflächen und Übergabe werden nicht isoliert betrachtet, sondern in eine logische Reihenfolge gebracht. Das ist besonders wichtig, weil viele Gewerke voneinander abhängig sind. Elektro- und Datenleitungen müssen liegen, bevor Wände geschlossen werden. Sanitäranschlüsse müssen geplant sein, bevor Fliesen oder Bodenbeläge eingebaut werden. Malerarbeiten kommen nicht vor dem Trockenbau. Die Endmontage kommt nicht vor der Fertigstellung der Oberflächen. Für Eigentümer bedeutet diese Koordination weniger Aufwand und mehr Sicherheit. Für Mieter bedeutet sie eine Fläche, die zum Start besser funktioniert. Für Hausverwaltungen bedeutet sie weniger Abstimmungsstress und eine klare Zuständigkeit.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Kostenlos beraten lassen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'fuer-wen-ein-koordinierter-mieterausbau-sinnvoll-ist',
    title: "Für wen ein koordinierter Mieterausbau sinnvoll ist",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="section-label">Für wen ein koordinierter Mieterausbau sinnvoll ist</div>
  <h2>Für wen ein koordinierter Mieterausbau sinnvoll ist</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Ein Mieterausbau ist für alle relevant, die Gewerbeflächen vermieten, verwalten, kaufen, modernisieren oder neu positionieren möchten. Besonders sinnvoll ist die koordinierte Umsetzung immer dann, wenn der Übergabetermin bereits feststeht oder mehrere Gewerke beteiligt sind.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px"><strong>Eigentümer und Vermieter</strong> profitieren, weil ein professionell vorbereiteter Ausbau die Vermietbarkeit verbessert. Eine Fläche mit sauberer Raumstruktur, funktionierender Technik, nutzbaren Sanitärbereichen, gepflegten Oberflächen und klarer Übergabedokumentation ist für viele Mieter attraktiver als eine Einheit, die sie selbst erst mühsam ausbauen müssen. Gerade im Rhein-Main-Gebiet, wo Gewerbeflächen stark miteinander konkurrieren, kann ein guter Ausbaustandard Leerstand verkürzen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px"><strong>Hausverwaltungen</strong> profitieren, weil sie nicht selbst jedes Gewerk einzeln steuern müssen. Ein Mieterausbau kann viele Abstimmungen erzeugen: Eigentümerwünsche, Mietervorgaben, technische Fragen, Zugangstermine, Hausordnung, Nachbarn, Lieferungen, Rechnungen und Abnahmen. Mit Radex gibt es einen zentralen Ansprechpartner, der den Ausbau technisch und organisatorisch zusammenhält.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px"><strong>Investoren und Bestandshalter</strong> profitieren, wenn eine Gewerbefläche nach Erwerb oder Leerstand neu positioniert werden soll. Ein Gebäude kann durch gute Ausbaustandards, moderne Grundrisse, bessere Beleuchtung, aktuelle Sanitärbereiche und gepflegte Oberflächen deutlich marktfähiger werden. Radex hilft dabei, Aufwand und Nutzen realistisch einzuordnen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Auch Mieter können indirekt profitieren, wenn der Ausbau im Auftrag des Eigentümers klar koordiniert wird. Je genauer die Anforderungen vor Baubeginn festgelegt sind, desto geringer ist das Risiko, dass während der Ausführung nachgebessert, umgeplant oder improvisiert werden muss. Wenn Sie als Eigentümer oder Verwalter eine Gewerbefläche kurzfristig für einen neuen Mieter vorbereiten müssen, lohnt sich eine frühe Anfrage. Telefonisch unter <a href="tel:+496074960620">06074 960620</a> lässt sich schnell klären, welche Schritte als nächstes sinnvoll sind.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="https://wa.me/491744684189" class="btn-primary gold" target="_blank" rel="noopener">Jetzt per WhatsApp anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'bueroausbau-praxisausbau-und-ladenflaechen-im-rhein-main-gebiet',
    title: "Büroausbau, Praxisausbau und Ladenflächen im Rhein-Main-Gebiet",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Büroausbau, Praxisausbau und Ladenflächen im Rhein-Main-Gebiet</div>
  <h2>Büroausbau, Praxisausbau und Ladenflächen im Rhein-Main-Gebiet</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Büroflächen gehören zu den häufigsten Nutzungen beim Mieterausbau. Die Anforderungen wirken auf den ersten Blick überschaubar: Räume, Licht, Steckdosen, Boden, Wände, Teeküche, Sanitär. In der Umsetzung entscheidet jedoch die Abstimmung über die Qualität. Eine Bürofläche muss nicht nur neu aussehen, sondern im Alltag funktionieren. Für moderne Büros sind flexible Raumstrukturen wichtig. Manche Mieter wünschen offene Arbeitsbereiche, andere brauchen Einzelbüros, Besprechungsräume, Telefonzonen, Empfangsbereiche oder Rückzugsräume. Dazu kommen technische Anforderungen: ausreichend Steckdosen, Datenanschlüsse, Beleuchtung, eventuell Akustikmaßnahmen, Heizkörperanpassung, Teeküche und Sanitärräume. Gerade in Bürostandorten wie Eschborn, Frankfurt am Main, Neu-Isenburg, Raunheim, Kelsterbach, Groß-Gerau oder Mörfelden-Walldorf zählt der Übergabetermin. Ein Unternehmen, das einzieht, plant Arbeitsplätze, IT, Möbel, Umzug und Personal. Wenn der Ausbau hinterherhinkt, entstehen echte Folgekosten. Radex arbeitet deshalb mit klarer Ablaufplanung und realistischen Zeitfenstern.</p>

    <h3 style="font-size:18px;color:var(--navy);font-weight:700;margin:28px 0 10px">Praxisausbau und Ausbau für Gesundheitsflächen</h3>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Praxen, Therapieräume, Beratungsflächen und medizinisch genutzte Einheiten stellen besondere Anforderungen. Hier geht es nicht nur um eine schöne Fläche, sondern um Funktion, Hygiene, Diskretion, Patientenwege, Schallschutz, Sanitär, Wartebereiche, Behandlungsräume und gegebenenfalls spezielle technische Anschlüsse. Ein Praxisausbau kann Räume für Empfang, Wartezone, Behandlung, Personal, Lager, Hygiene, WC und Technik benötigen. Die Raumaufteilung muss zum Ablauf der späteren Praxis passen. Gleichzeitig müssen Oberflächen pflegeleicht und robust sein. Böden sollten belastbar und leicht zu reinigen sein. Beleuchtung muss funktional und angenehm sein. Sanitärbereiche müssen sinnvoll erreichbar sein. Radex koordiniert solche Ausbauprojekte als Generalunternehmer. Dabei werden Trockenbau, Innenausbau, Bodenbeläge, Oberflächen, Elektrofachpartner und SHK-Leistungen zusammengebracht. Bei Praxen ist auch die Abstimmung mit Vermieter, Mieter und eventuell Fachplanern wichtig. Radex übernimmt nicht die fachplanerische Verantwortung für Spezialanforderungen, koordiniert aber die vereinbarten Ausbauleistungen und bindet passende Fachpartner ein.</p>

    <h3 style="font-size:18px;color:var(--navy);font-weight:700;margin:28px 0 10px">Ladenfläche, Verkaufsfläche und Servicefläche ausbauen</h3>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Ladenflächen und Serviceflächen müssen Kunden empfangen, Orientierung schaffen und gleichzeitig im Hintergrund technisch funktionieren. Hier spielen Licht, Boden, Wände, Verkaufsbereiche, Lager, Personalbereiche, Sanitär und manchmal auch Sichtachsen eine größere Rolle als bei klassischen Büroflächen. Ein Ladenlokal nach Mieterwechsel braucht oft zunächst Rückbau. Alte Regale, Zwischenwände, Bodenbeläge, Deckeninstallationen oder veraltete Beleuchtung müssen entfernt werden. Danach wird die Fläche an das neue Konzept angepasst. Radex koordiniert Rückbau, Trockenbau, Bodenarbeiten, Malerarbeiten, Sanitär und Elektrokoordination. Wenn neue Räume entstehen, werden Leitungen und Anschlüsse vor dem Schließen der Wände eingeplant. Für Vermieter ist ein sauberer Mieterausbau ein Vermietungsargument. Eine gepflegte, gut vorbereitete Ladenfläche wirkt wertiger, reduziert Einstiegshürden für Mieter und erleichtert die Übergabe.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Unverbindlich anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'rueckbau-raumaufteilung-und-trockenbau',
    title: "Rückbau, Raumaufteilung und Trockenbau",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="section-label">Rückbau, Raumaufteilung und Trockenbau</div>
  <h2>Rückbau, Raumaufteilung und Trockenbau</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Viele Mieterausbauten beginnen mit Rückbau. Der Vormieter hat Einbauten hinterlassen, der Grundriss passt nicht mehr, alte Bodenbeläge sind abgenutzt oder technische Installationen müssen freigelegt werden. Rückbau ist aber nicht einfach „alles raus". Er muss kontrolliert erfolgen, damit verwertbare Bauteile erhalten bleiben, angrenzende Bereiche geschützt werden und keine verdeckten Probleme übersehen werden. Vor dem Rückbau wird festgelegt, was entfernt wird und was bleiben soll. Trennwände, Bodenbeläge, alte Decken, Einbaumöbel, Sanitärobjekte, Leuchten, Kabelkanäle oder alte Küchenbereiche können betroffen sein.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">In Bestandsgebäuden muss außerdem geprüft werden, ob Schadstoffe wie Asbest, alte Kleber, KMF-Dämmstoffe oder Schimmel eine Rolle spielen können. Radex ist zertifiziert für Schimmel- und Asbestsanierung und verfügt über Sachkunde nach TRGS 519. Wenn bei einem Mieterausbau im Bestand Verdachtsmomente auftreten, werden diese fachlich eingeordnet und in den Ablauf eingebunden. Das schützt Eigentümer, Mieter und ausführende Gewerke. Nach dem Rückbau muss die Fläche für den Ausbau vorbereitet werden: Untergründe prüfen, Unebenheiten beseitigen, Anschlüsse sichern, Leitungen freilegen oder zurückbauen, Flächen reinigen und den nächsten Gewerken übergeben. Wenn der Rückbau unsauber endet, starten die Ausbaugewerke mit Problemen.</p>

    <h3 style="font-size:18px;color:var(--navy);font-weight:700;margin:28px 0 10px">Raumaufteilung, Trockenbau und Innenausbau</h3>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Die Raumaufteilung ist einer der wichtigsten Bestandteile des Mieterausbaus. Sie entscheidet, ob die Fläche später sinnvoll nutzbar ist. Trockenbau ist dabei oft das zentrale Gewerk, weil er flexible Trennwände, Raumzonen, Installationsbereiche, Abkastungen, Deckenlösungen und Schallschutzmaßnahmen ermöglicht. Radex koordiniert Trockenbau und Innenausbau so, dass die neue Raumstruktur mit Technik, Nutzung und Oberflächen zusammenpasst. Wenn Wände gestellt werden, müssen Elektro- und Datenleitungen eingeplant sein. Wenn Sanitäranschlüsse in einem Bereich benötigt werden, müssen Leitungswege und Schächte geprüft werden. Wenn Schallschutz wichtig ist, muss die Konstruktion entsprechend gewählt werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Der Innenausbau umfasst neben Trockenbau auch Türen, Zargen, Wand- und Deckenflächen, Nischen, Akustiklösungen, Oberflächen und Details, die den fertigen Eindruck bestimmen. Gerade bei Gewerbeflächen ist der Innenausbau nicht nur Dekoration. Er beeinflusst Nutzbarkeit, Akustik, Arbeitskomfort und Außenwirkung. Ein gut geplanter Mieterausbau verhindert, dass später provisorische Lösungen entstehen. Radex achtet darauf, dass die Raumaufteilung vor der Ausführung klar ist und Änderungen nicht erst dann diskutiert werden, wenn Wände schon geschlossen sind.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Kostenlos beraten lassen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'elektrokoordination-beleuchtung-und-dateninfrastruktur',
    title: "Elektrokoordination, Beleuchtung und Dateninfrastruktur",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Elektrokoordination, Beleuchtung und Dateninfrastruktur</div>
  <h2>Elektrokoordination, Beleuchtung und Dateninfrastruktur</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Elektrotechnik gehört bei fast jedem Mieterausbau zu den wichtigsten Schnittstellen. Gewerbeflächen brauchen ausreichend Steckdosen, passende Stromkreise, Beleuchtung, Netzwerkanschlüsse, eventuell EDV-Verkabelung, Anschlüsse für Teeküche, Empfang, Geräte, Server, Kassensysteme oder Präsentationstechnik. Radex ist kein Elektro-Meisterbetrieb, koordiniert Elektrotechnik aber früh mit qualifizierten Fachpartnern. Das ist entscheidend, weil Elektroplanung direkt mit Raumaufteilung und Innenausbau zusammenhängt. Steckdosen müssen dort sitzen, wo Arbeitsplätze entstehen. Licht muss zur Nutzung passen. Datenanschlüsse müssen dort liegen, wo Technik gebraucht wird. Leitungen müssen eingebaut sein, bevor Wände geschlossen werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bei Büroflächen sind Netzwerk und Beleuchtung besonders wichtig. Bei Praxen kommen je nach Nutzung weitere Anforderungen hinzu. Bei Ladenflächen ist die Beleuchtung ein Teil der Verkaufswirkung. Bei Serviceflächen kann die Stromversorgung für Geräte oder Arbeitsbereiche entscheidend sein. Radex koordiniert diese Themen im Gesamtprojekt, damit die Elektroarbeiten nicht zu spät kommen und keine fertigen Oberflächen wieder geöffnet werden müssen.</p>

    <h3 style="font-size:18px;color:var(--navy);font-weight:700;margin:28px 0 10px">Heizung, Sanitär und Gebäudetechnik beim Mieterausbau</h3>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Im Bereich Heizung, Sanitär und Gebäudetechnik bringt Radex eigene SHK-Meisterkompetenz ein. Das ist beim Mieterausbau besonders wertvoll, weil gewerbliche Flächen oft neue oder angepasste Sanitärräume, Teeküchen, Wasseranschlüsse, Heizkörper oder gebäudetechnische Anpassungen benötigen. Ein Büro braucht vielleicht eine Teeküche. Eine Praxis benötigt funktionsfähige Waschmöglichkeiten. Eine Ladenfläche braucht einen Personal-WC-Bereich. Eine Bestandsfläche hat Heizkörper an Stellen, die nach neuer Raumaufteilung nicht mehr sinnvoll sind. Genau solche Punkte müssen früh geprüft werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex plant und koordiniert SHK-Arbeiten im Rahmen des Mieterausbaus: Wasserleitungen, Abwasser, Warmwasser, Heizkörper, Heizungsanpassungen, Sanitäranlagen, Anschlüsse und technische Abstimmung mit anderen Gewerken. Wenn neue Wände entstehen, muss klar sein, wo Leitungen verlaufen. Wenn Bodenbeläge eingebaut werden, dürfen darunter keine ungeklärten technischen Punkte offen bleiben. Für Eigentümer ist diese integrierte SHK-Kompetenz ein Vorteil, weil Sanitär und Gebäudetechnik nicht separat organisiert werden müssen. Der Ausbau bleibt in einer Hand koordiniert.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="https://wa.me/491744684189" class="btn-primary gold" target="_blank" rel="noopener">Elektroplanung besprechen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'bodenbelaege-oberflaechen-und-ausbaustandards',
    title: "Bodenbeläge, Oberflächen und Ausbaustandards",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="section-label">Bodenbeläge, Oberflächen und Ausbaustandards</div>
  <h2>Bodenbeläge, Oberflächen und Ausbaustandards</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bodenbeläge und Oberflächen entscheiden, wie eine Gewerbefläche wahrgenommen wird. Sie müssen zur Nutzung, zur Belastung und zum gewünschten Standard passen. Ein Büro braucht andere Böden als eine Praxis. Eine Ladenfläche braucht andere Oberflächen als ein Lagerbüro. Ein Besprechungsbereich soll anders wirken als ein Technikraum. Typische Bodenbeläge im Mieterausbau sind Vinyl, Designbelag, Teppichfliesen, Fliesen, Linoleum, Parkett, Laminat oder robuste Objektbeläge. Die Wahl hängt von Nutzung, Pflegeaufwand, Akustik, Belastung und Budget ab. Auch der Untergrund ist entscheidend: Unebenheiten, alte Kleber, Feuchtigkeit oder Höhenunterschiede müssen vor der Verlegung geprüft werden. Provisorische Ausbesserungen fallen sofort auf und schwächen den Gesamteindruck. Radex koordiniert Boden- und Oberflächenarbeiten so, dass sie zum Ausbaustandard passen und zum richtigen Zeitpunkt ausgeführt werden. Erst wenn Technik, Trockenbau und Untergründe fertig sind, lohnt sich die finale Oberfläche.</p>

    <h3 style="font-size:18px;color:var(--navy);font-weight:700;margin:28px 0 10px">Ausbaustandard: Basis, nutzungsfertig oder nach Mietervorgabe</h3>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Nicht jeder Mieterausbau braucht denselben Standard. Manchmal soll eine Fläche nur vorbereitet werden, damit der Mieter selbst weiter ausbauen kann. Manchmal soll die Einheit bezugsfertig übergeben werden. Manchmal gibt der Mieter sehr konkrete Anforderungen vor.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Ein <strong>Basisausbau</strong> umfasst typischerweise nutzbare Räume, einfache Oberflächen, funktionierende Grundtechnik, Sanitäreinrichtungen und grundlegende Elektroversorgung. Dieser Standard kann sinnvoll sein, wenn der Mieter noch eigene Anpassungen plant. Ein <strong>nutzungsfertiger Ausbau</strong> geht deutlich weiter. Hier sind Räume fertig gegliedert, Oberflächen abgeschlossen, Bodenbeläge verlegt, Sanitärbereiche nutzbar, Beleuchtung installiert und technische Grundausstattung vorbereitet. Der Mieter kann nach Übergabe kurzfristig einziehen. Ein <strong>Ausbau nach Mietervorgabe</strong> ist besonders bei größeren Einheiten, Praxen, Büros oder hochwertigen Gewerbeflächen üblich. Hier werden Anforderungen an Grundriss, Technik, Ausstattung, Material und Übergabezustand vorab konkretisiert und in den Leistungsumfang aufgenommen. Radex hilft Eigentümern, den passenden Standard zu definieren. Ziel ist nicht, möglichst viel zu bauen, sondern genau das, was zur Vermietung, zum Objekt und zum Mieter passt. Das schützt Budget und Übergabetermin.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Kostenlos beraten lassen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'abstimmung-zwischen-eigentuemer-mieter-und-hausverwaltung',
    title: "Abstimmung zwischen Eigentümer, Mieter und Hausverwaltung",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Abstimmung zwischen Eigentümer, Mieter und Hausverwaltung</div>
  <h2>Abstimmung zwischen Eigentümer, Mieter und Hausverwaltung</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Mieterausbau scheitert selten am einzelnen Handgriff. Probleme entstehen meistens dort, wo Erwartungen nicht klar festgelegt wurden. Was übernimmt der Eigentümer? Was bringt der Mieter selbst ein? Welche Ausstattung ist vereinbart? Wer entscheidet bei Änderungen? Welche Termine sind verbindlich? Welche Qualität wird erwartet?</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex unterstützt die strukturierte Abstimmung. Vor Beginn sollten Leistungsumfang, Zeitplan, Ausbaustandard, technische Anforderungen und Zuständigkeiten klar sein. Wenn der Mieter besondere Wünsche hat, sollten diese früh aufgenommen werden. Wenn die Hausverwaltung Vorgaben zu Zugängen, Arbeitszeiten, Schutzmaßnahmen oder Dokumentation hat, gehören diese in die Planung.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine gute Abstimmung verhindert teure Änderungen während der Bauphase. Wenn erst nach dem Trockenbau auffällt, dass ein zusätzlicher Datenanschluss benötigt wird, entstehen Nacharbeiten. Wenn ein Sanitäranschluss zu spät geplant wird, muss eventuell wieder geöffnet werden. Wenn der Bodenbelag erst kurz vor Übergabe entschieden wird, kann sich der Termin verschieben. Radex koordiniert den Ausbau so, dass solche Schnittstellen möglichst früh geklärt werden.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="https://wa.me/491744684189" class="btn-primary gold" target="_blank" rel="noopener">Jetzt per WhatsApp anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'mieterausbau-im-bestand-besondere-risiken-und-chancen',
    title: "Mieterausbau im Bestand: besondere Risiken und Chancen",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="section-label">Mieterausbau im Bestand: besondere Risiken und Chancen</div>
  <h2>Mieterausbau im Bestand: besondere Risiken und Chancen</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Viele Gewerbeflächen im Rhein-Main-Gebiet befinden sich in Bestandsgebäuden. Das kann ein Bürogebäude aus den 1980er-Jahren sein, eine Ladenfläche im Erdgeschoss eines Wohn- und Geschäftshauses, eine Praxis in einem älteren Mehrfamilienhaus oder eine Servicefläche in einem Gewerbeobjekt. Bestandsflächen haben Vorteile: Lage, Erreichbarkeit, bestehende Infrastruktur, gewachsene Mieterstruktur. Sie bringen aber auch Risiken mit: veraltete Leitungen, unklare Pläne, alte Bodenaufbauten, geringe Deckenhöhen, eingeschränkte Schächte, alte Heizkörperpositionen, Schadstoffverdacht oder brandschutzrelevante Fragen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex beginnt deshalb mit einer Bestandsaufnahme. Was ist vorhanden? Was kann genutzt werden? Was muss erneuert werden? Welche Bereiche sind kritisch? Welche Arbeiten hängen voneinander ab? Diese Prüfung ist die Grundlage für einen realistischen Ablauf. Gerade bei Mieterausbauten im Bestand ist Erfahrung mit Sanierung wichtig. Es reicht nicht, eine neue Wand zu setzen. Man muss verstehen, was im Gebäude bereits vorhanden ist und wie der neue Ausbau daran anschließt.</p>

    <h3 style="font-size:18px;color:var(--navy);font-weight:700;margin:28px 0 10px">Schadstoffe, Schimmel und alte Materialien vor dem Ausbau prüfen</h3>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bei Bestandsflächen können alte Materialien zum Thema werden. Bodenbeläge, Kleber, Spachtelmassen, Deckenplatten, Dämmstoffe oder alte Wandverkleidungen können Schadstoffe enthalten. Auch Schimmel kann in schlecht belüfteten oder lange leerstehenden Flächen auftreten. Wenn eine Gewerbefläche vor dem Ausbau zurückgebaut wird, sollten solche Risiken früh erkannt werden. Asbestverdächtige Materialien dürfen nicht einfach entfernt oder geschliffen werden. Schimmel sollte nicht nur überstrichen werden. Alte Dämmstoffe oder Kleber müssen fachlich eingeordnet werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex ist zertifiziert für Schimmel- und Asbestsanierung und verfügt über Sachkunde nach TRGS 519. Schadstoffthemen werden in die Ausbauplanung integriert, statt den Ablauf später zu blockieren. Das ist besonders wichtig für Eigentümer und Hausverwaltungen, weil ein unerwarteter Schadstofffund kurz vor Übergabe den gesamten Mietbeginn gefährden kann. Früh prüfen heißt besser planen.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Unverbindlich anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'zeitplan-laufender-betrieb-und-genehmigungen',
    title: "Zeitplan, laufender Betrieb und Genehmigungen",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Zeitplan, laufender Betrieb und Genehmigungen</div>
  <h2>Zeitplan, laufender Betrieb und Genehmigungen</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Beim Mieterausbau ist der Zeitplan oft genauso wichtig wie die Ausführung. Der neue Mieter plant Möbel, Personal, Technik, Eröffnung, Kundenkommunikation oder Umzug. Wenn die Fläche nicht rechtzeitig fertig ist, kann das direkte wirtschaftliche Folgen haben. Radex plant Mieterausbauten mit klarer Reihenfolge: Zuerst Bestandsaufnahme und Leistungsumfang. Dann Rückbau und Vorbereitung. Danach technische Gewerke wie Elektrokoordination und SHK. Anschließend Trockenbau, Boden, Oberflächen, Endmontage, Reinigung und Übergabe. Wichtig sind realistische Puffer. Radex verspricht keine unrealistischen Termine, nur um einen Auftrag zu bekommen. Ziel ist ein belastbarer Ablauf, der gehalten werden kann. Wenn ein Übergabetermin bereits feststeht, sollte Radex früh eingebunden werden. Direkt anrufen unter <a href="tel:+496074960620">06074 960620</a> und Projektumfang besprechen.</p>

    <h3 style="font-size:18px;color:var(--navy);font-weight:700;margin:28px 0 10px">Mieterausbau während laufendem Betrieb</h3>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Nicht jeder Mieterausbau findet in einem leerstehenden Gebäude statt. Oft sind Nachbarflächen belegt, andere Mieter arbeiten weiter, Kundenverkehr läuft oder die Immobilie wird teilweise genutzt. Dann müssen Lärm, Staub, Lieferungen, Flure, Treppenhäuser, Aufzüge und Arbeitszeiten besonders sorgfältig geplant werden. Radex berücksichtigt diese Rahmenbedingungen. Schutzmaßnahmen, abgestimmte Zugangswege, geregelte Arbeitszeiten und klare Kommunikation helfen, Beeinträchtigungen zu reduzieren. Bei Gewerbeobjekten mit mehreren Mietern ist das ein wichtiger Bestandteil der Projektsteuerung. Auch Teilausbauten sind möglich, wenn die Fläche abschnittsweise bearbeitet werden soll. Dabei muss die Abfolge besonders sauber geplant werden, damit bereits nutzbare Bereiche nicht wieder beschädigt werden und laufende Nutzung nicht unnötig gestört wird.</p>

    <h3 style="font-size:18px;color:var(--navy);font-weight:700;margin:28px 0 10px">Brandschutz, Genehmigung und Fachplanung</h3>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Je nach Umfang und Nutzung können beim Mieterausbau zusätzliche fachliche oder behördliche Anforderungen entstehen. Das betrifft insbesondere Nutzungsänderungen, Brandschutz, Fluchtwege, tragende Bauteile, Lüftung, besondere Praxisanforderungen, Versammlungsbereiche oder technische Sondernutzungen. Radex gibt keine pauschalen Genehmigungszusagen. Ob eine Genehmigung, eine Fachplanung oder eine Abstimmung mit Behörden notwendig ist, hängt vom konkreten Objekt und der geplanten Nutzung ab. Radex koordiniert die vereinbarten Ausbauleistungen und bindet bei Bedarf geeignete Fachplaner oder Fachpartner ein. Für Eigentümer ist wichtig: Solche Fragen sollten früh gestellt werden. Wenn erst kurz vor Übergabe auffällt, dass eine Nutzungsänderung, ein Brandschutzthema oder ein technischer Nachweis fehlt, kann sich der Einzug deutlich verzögern.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Beratungsgespräch vereinbaren</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'mieterausbau-als-teil-von-gewerbe-und-objektsanierung',
    title: "Mieterausbau als Teil von Gewerbe- und Objektsanierung",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="section-label">Mieterausbau als Teil von Gewerbe- und Objektsanierung</div>
  <h2>Mieterausbau als Teil von Gewerbe- und Objektsanierung</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Mieterausbau ist häufig Teil einer größeren Gewerbe- oder Objektsanierung. Ein einzelnes Ladenlokal wird neu vorbereitet. Eine komplette Büroetage wird neu vermietet. Ein gemischt genutztes Gebäude wird modernisiert. Mehrere Einheiten sollen nacheinander ausgebaut werden. In solchen Fällen ist die Generalunternehmerkoordination besonders wertvoll. Radex kann Ausbau, Sanierung, Rückbau, SHK, Innenausbau, Elektrokoordination, Boden, Malerarbeiten und Übergabe in einem Projektfluss zusammenführen. Eigentümer müssen nicht für jede Einheit neu erklären, wie das Gebäude funktioniert. Hausverwaltungen bekommen eine wiederkehrende Struktur. Gerade bei mehreren Einheiten ist Dokumentation wichtig: Welche Leitungen wurden erneuert? Welche Sanitärbereiche wurden angepasst? Welche Wände wurden gesetzt? Welche Bodenbeläge wurden eingebaut? Eine saubere Dokumentation erleichtert spätere Wartung, Folgevermietung und weitere Ausbauten.</p>

    <h3 style="font-size:18px;color:var(--navy);font-weight:700;margin:28px 0 10px">Regionale Einsatzgebiete im Rhein-Main-Gebiet</h3>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex ist in über 60 Städten im Rhein-Main-Gebiet aktiv und koordiniert Mieterausbau, Gewerbeumbau, Objektsanierung, Innenausbau und Sanierung im Bestand. Zum Einsatzgebiet gehören unter anderem Rödermark, Rodgau, Dietzenbach, Dreieich, Langen, Neu-Isenburg, Offenbach am Main, Frankfurt am Main, Mühlheim am Main, Obertshausen, Heusenstamm, Hanau, Maintal, Seligenstadt, Darmstadt, Dieburg, Weiterstadt, Groß-Gerau, Rüsselsheim am Main, Mörfelden-Walldorf, Kelsterbach, Raunheim, Hattersheim am Main, Flörsheim am Main, Hochheim am Main, Hofheim am Taunus, Eschborn, Bad Vilbel, Bad Homburg, Oberursel, Wiesbaden, Mainz, Aschaffenburg und weitere Städte im Rhein-Main-Gebiet. Die regionale Nähe hilft bei Mieterausbauten, weil Bestandsaufnahme, Gewerke, Abstimmungen, Nacharbeiten und Übergabe eng getaktet sind. Wer eine Fläche kurzfristig vorbereiten muss, profitiert von einem Ansprechpartner, der in der Region aktiv ist.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="https://wa.me/491744684189" class="btn-primary gold" target="_blank" rel="noopener">Angebot anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'warum-radex-fuer-mieterausbau',
    title: "Warum Radex für Mieterausbau",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Warum Radex für Mieterausbau</div>
  <h2>Warum Radex für Mieterausbau</h2>
  <div>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Ein Mieterausbau braucht nicht nur Handwerker. Er braucht jemanden, der den Ablauf versteht, die Gewerke sortiert und Entscheidungen rechtzeitig vorbereitet. Genau hier liegt die Stärke von Radex.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex verbindet Generalunternehmerkoordination mit SHK-Meisterkompetenz im Bereich Heizung, Sanitär und Gebäudetechnik. Das ist besonders wertvoll, weil Gewerbeflächen häufig technische Anpassungen brauchen: Sanitärbereiche, Teeküchen, Heizkörper, Wasseranschlüsse, Warmwasser, Leitungen und gebäudetechnische Schnittstellen. Für weitere Gewerke arbeitet Radex mit qualifizierten Fachpartnern und koordiniert deren Einsatz.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eigentümer, Vermieter und Hausverwaltungen bekommen einen festen Ansprechpartner statt vieler Einzelkontakte. Das reduziert Abstimmungsaufwand, verhindert Schnittstellenprobleme und macht den Übergabetermin besser planbar. Radex denkt Mieterausbau nicht als Themenportal, sondern als praktisches Projekt: Fläche ansehen, Nutzung verstehen, Aufwand einschätzen, Gewerke koordinieren, ausführen, übergeben. Wenn Sie eine Gewerbefläche vorbereiten möchten, sprechen Sie direkt mit Radex. Telefon: <a href="tel:+496074960620">06074 960620</a>.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Kostenlos beraten lassen</a>
  </div>
</div>` }}
      />
    ),
  }
];

export const mieterausbauLegacyFaqs = [];
