/* Auto-generated by scripts/build-sicherungskasten-legacy.mjs – do not edit by hand. */
/* eslint-disable react/no-danger */

export const sicherungskastenLegacySections = [
  {
    id: 'wann-sollte-ein-sicherungskasten-erneuert-werden',
    title: "Wann sollte ein Sicherungskasten erneuert werden?",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="container">
    <h2>Wann sollte ein Sicherungskasten erneuert werden?</h2>
    <p>Ein Sicherungskasten sollte geprüft werden, wenn er veraltet wirkt, nicht mehr zur Nutzung passt, häufig Sicherungen auslösen, neue Verbraucher geplant sind oder eine größere Sanierung ansteht. Ob eine Erneuerung notwendig ist, entscheidet ein qualifizierter Elektrofachbetrieb nach Prüfung des Bestands. Radex koordiniert diese Prüfung im Rahmen der Sanierung und bindet sie in den Ablauf ein.</p>
    <p>Typische Situationen, in denen eine Prüfung sinnvoll ist:</p>
    <ul>
      <li>ältere Wohnung oder älteres Haus wird saniert</li>
      <li><a href="/altbau-elektrik-erneuern-rhein-main">Altbau-Elektrik</a> soll erneuert werden</li>
      <li>neue Küche mit leistungsstarken Geräten wird geplant</li>
      <li>Bad wird modernisiert</li>
      <li>zusätzliche Steckdosen oder Stromkreise werden benötigt</li>
      <li>Homeoffice und Netzwerk sollen vorbereitet werden</li>
      <li><a href="/waermepumpe-rhein-main">Wärmepumpe</a> oder Heizungsmodernisierung ist geplant</li>
      <li>Wallbox-Vorbereitung wird gewünscht</li>
      <li>Sicherungen lösen häufig aus</li>
      <li>Unterverteilung wirkt unübersichtlich oder sehr alt</li>
      <li>frühere Umbauten wurden nur teilweise dokumentiert</li>
      <li><a href="/komplettsanierung-rhein-main">Komplettsanierung</a> oder <a href="/kernsanierung-rhein-main">Kernsanierung</a> steht an</li>
      <li>Gewerbefläche wird umgebaut oder für neue Nutzung vorbereitet</li>
    </ul>
    <p>Viele Eigentümer bemerken den Sicherungskasten erst, wenn die Anforderungen steigen. Eine neue Küche benötigt eigene Anschlüsse. Ein Bad braucht sichere Elektrobereiche, Spiegelanschluss, Lüfter und Beleuchtung. Ein Homeoffice benötigt verlässliche Strom- und Netzwerkstruktur. Eine Wärmepumpe stellt zusätzliche Anforderungen an die Elektroinstallation. Eine Gewerbefläche braucht Arbeitsplätze, Licht, Datentechnik und technische Anschlüsse. In solchen Fällen reicht es oft nicht, einzelne Steckdosen zu ergänzen, ohne die Verteilung zu prüfen.</p>
    <p>Bei älteren Immobilien ist außerdem wichtig, die vorhandene Elektrostruktur als Ganzes zu betrachten. Ein Sicherungskasten kann nicht sinnvoll bewertet werden, ohne Stromkreise, Leitungen, Nutzung und geplante Erweiterungen zu berücksichtigen. Manchmal reicht eine Anpassung. Manchmal ist eine umfassendere Erneuerung sinnvoll. Manchmal muss die gesamte <a href="/altbau-elektrik-erneuern-rhein-main">Altbau-Elektrik</a> geprüft werden.</p>
    <p>Radex koordiniert diese Einschätzung mit qualifizierten Elektrofachbetrieben. Dadurch wird die Entscheidung nicht pauschal getroffen, sondern passend zum Objekt, zur Nutzung und zum Sanierungsumfang.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Kostenlos beraten lassen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'sicherungskasten-bei-altbausanierung-pruefen',
    title: "Sicherungskasten bei Altbausanierung prüfen",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="container">
    <h2>Sicherungskasten bei Altbausanierung prüfen</h2>
    <p>Bei Altbausanierungen ist der Sicherungskasten besonders wichtig. Viele ältere Häuser und Wohnungen haben über Jahrzehnte gewachsene Elektroinstallationen. Einzelne Räume wurden modernisiert, Steckdosen ergänzt, Küchenanschlüsse verändert oder Bäder umgebaut, ohne dass die gesamte Elektrostruktur neu geplant wurde. Dadurch kann eine Unterverteilung entstehen, die zwar noch funktioniert, aber nicht mehr zu heutigen Anforderungen passt.</p>
    <p>Eine Altbauimmobilie muss deshalb nicht schlecht sein. Viele ältere Häuser und Wohnungen haben solide Substanz, gute Lagen und hohen Wohnwert. Die Elektroinstallation sollte aber fachlich geprüft werden, bevor neue Oberflächen entstehen. Besonders bei <a href="/komplettsanierung-rhein-main">Komplettsanierung</a>, <a href="/kernsanierung-rhein-main">Kernsanierung</a>, Wohnungssanierung oder Haussanierung ist der richtige Zeitpunkt, Sicherungskasten, Stromkreise und Leitungen zu bewerten.</p>
    <p>Typische Fragen bei Altbau und Sicherungskasten:</p>
    <ul>
      <li>Wie alt ist die Unterverteilung?</li>
      <li>Sind ausreichend Stromkreise vorhanden?</li>
      <li>Passen die Absicherungen zur Nutzung?</li>
      <li>Gibt es getrennte Stromkreise für Küche, Bad und größere Verbraucher?</li>
      <li>Sind Schutzvorrichtungen zeitgemäß?</li>
      <li>Wurden frühere Erweiterungen fachgerecht eingebunden?</li>
      <li>Gibt es klare Zuordnung der Stromkreise?</li>
      <li>Müssen Leitungen gleichzeitig geprüft werden?</li>
      <li>Soll Netzwerk, Wärmepumpe oder Wallbox vorbereitet werden?</li>
      <li>Wird im Rahmen der Sanierung ohnehin an Wänden oder Böden gearbeitet?</li>
    </ul>
    <p>Radex bindet Elektrofachpartner früh ein, damit diese Fragen vor der Ausführung geklärt werden. Das ist besonders wichtig, weil eine Sicherungskastenerneuerung Auswirkungen auf Leitungsführung, Wandarbeiten, Trockenbau, Malerarbeiten, Küche, Bad und Innenausbau haben kann.</p>
    <p>Bei <a href="/altbausanierung-rhein-main">Altbausanierungen</a> können zusätzlich Schadstoffthemen relevant sein. Wenn Wände geöffnet, alte Bodenbeläge entfernt oder alte Materialien bearbeitet werden, können Verdachtsmomente auftreten. Radex ist zertifiziert für Schimmel- und <a href="/asbestsanierung-rhein-main">Asbestsanierung</a> und verfügt über Sachkunde nach TRGS 519. Dadurch können solche Themen in den Sanierungsablauf eingeordnet werden.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="https://wa.me/491744684189" class="btn-primary gold" target="_blank" rel="noopener">Jetzt per WhatsApp anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'sicherungskasten-bei-hauskauf-oder-wohnungskauf-pruefen',
    title: "Sicherungskasten bei Hauskauf oder Wohnungskauf prüfen",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="container">
    <h2>Sicherungskasten bei Hauskauf oder Wohnungskauf prüfen</h2>
    <p>Nach dem Kauf einer Immobilie stellen viele Eigentümer fest, dass die Elektroinstallation nicht vollständig zum geplanten Alltag passt. Bei Besichtigungen stehen oft Lage, Grundriss, Zustand, Bad, Küche, Fenster, Heizung und Gesamteindruck im Vordergrund. Der Sicherungskasten wird zwar gesehen, aber selten fachlich bewertet. Spätestens bei der Sanierungsplanung wird jedoch deutlich, ob die Unterverteilung ausreichend ist.</p>
    <p>Gerade vor dem Einzug ist der richtige Zeitpunkt, den Sicherungskasten prüfen zu lassen. Räume sind leer, Wände können leichter bearbeitet werden, Küchenplanung und Badmodernisierung stehen noch bevor, und Fachpartner können besser koordiniert werden. Wird erst nach dem Einzug festgestellt, dass Stromkreise fehlen oder die Unterverteilung nicht passt, wird die Anpassung deutlich aufwendiger.</p>
    <p>Typische Fragen nach dem Kauf:</p>
    <ul>
      <li>Reicht der Sicherungskasten für die geplante Nutzung?</li>
      <li>Gibt es genug Stromkreise für Küche, Bad und Wohnräume?</li>
      <li>Können zusätzliche Steckdosen eingeplant werden?</li>
      <li>Ist die Küche für moderne Geräte vorbereitet?</li>
      <li>Wird ein Homeoffice eingerichtet?</li>
      <li>Ist eine <a href="/waermepumpe-rhein-main">Wärmepumpe</a> oder Wallbox langfristig denkbar?</li>
      <li>Muss <a href="/altbau-elektrik-erneuern-rhein-main">Altbau-Elektrik</a> geprüft werden?</li>
      <li>Sind Leitungen und Unterverteilung aufeinander abgestimmt?</li>
      <li>Welche Arbeiten sollten vor dem Einzug erledigt werden?</li>
    </ul>
    <p>Radex koordiniert die Prüfung des Sicherungskastens als Teil der Sanierung. Wenn zusätzlich Bad, Küche, Böden, Wände, Heizung, Sanitär oder Innenausbau geplant sind, wird der Elektrofachpartner rechtzeitig eingebunden. Dadurch können notwendige Arbeiten in der richtigen Reihenfolge erfolgen.</p>
    <p>Für Käufer ist diese frühzeitige Einschätzung besonders wertvoll. Sie hilft, Sanierungskosten realistischer einzuordnen und verhindert, dass fertige Räume später erneut geöffnet werden müssen. Eine neue Küche, ein modernes Bad oder ein Homeoffice sollten nicht durch eine unzureichende Elektrostruktur eingeschränkt werden.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Unverbindlich anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'sicherungskasten-bei-wohnungssanierung',
    title: "Sicherungskasten bei Wohnungssanierung",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="container">
    <h2>Sicherungskasten bei Wohnungssanierung</h2>
    <p>Bei <a href="/wohnungssanierung-rhein-main">Wohnungssanierungen</a> ist der Sicherungskasten ein wichtiger Prüfpunkt. Viele ältere Wohnungen haben Unterverteilungen, die für heutige Anforderungen knapp bemessen sind. Moderne Küchen, Bäder, Waschmaschine, Trockner, Homeoffice, Netzwerk, Beleuchtung und zusätzliche Steckdosen können neue Stromkreise oder Anpassungen erforderlich machen.</p>
    <p>In Mehrfamilienhäusern müssen bei Elektroarbeiten zusätzliche Rahmenbedingungen berücksichtigt werden. Hausverwaltung, Eigentümergemeinschaft, Zählerplatz, gemeinschaftliche Bereiche, Zugänge, Bauzeiten und Nachbarn können relevant sein. Deshalb sollte die Prüfung des Sicherungskastens früh in den Ablauf der Wohnungssanierung eingebunden werden.</p>
    <p>Typische Themen bei Wohnungen:</p>
    <ul>
      <li>Unterverteilung in der Wohnung prüfen</li>
      <li>Stromkreise für Küche bewerten</li>
      <li>Badtechnik und Sicherheitsbereiche berücksichtigen</li>
      <li>zusätzliche Steckdosen planen</li>
      <li>Homeoffice und Netzwerk vorbereiten</li>
      <li>Waschmaschine und Trockner einordnen</li>
      <li>alte Leitungen bewerten</li>
      <li>Abstimmung mit Hausverwaltung oder Eigentümergemeinschaft</li>
      <li>Bauzeiten und Zugänge berücksichtigen</li>
      <li>Sanierung vor Einzug oder nach Mieterwechsel planen</li>
    </ul>
    <p>Für Eigennutzer ist die Elektrostruktur im Alltag sofort spürbar. Zu wenige Steckdosen, ungünstige Lichtanschlüsse oder fehlende Netzwerkpunkte stören dauerhaft. Für Vermieter ist eine zeitgemäße Elektroinstallation ein wichtiger Faktor für Vermietbarkeit, Werterhalt und weniger spätere Reparaturen.</p>
    <p>Radex koordiniert den Elektrofachpartner im Rahmen der Wohnungssanierung. SHK-Arbeiten im Bad, Sanitärinstallation oder Heizkörper werden unter Meisterverantwortung geführt. Elektro, Trockenbau, Fliesen, Boden, Malerarbeiten und Innenausbau werden zeitlich abgestimmt. So entsteht eine Sanierung, bei der der Sicherungskasten nicht isoliert betrachtet wird.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Beratungsgespräch vereinbaren</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'sicherungskasten-bei-haussanierung',
    title: "Sicherungskasten bei Haussanierung",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="container">
    <h2>Sicherungskasten bei Haussanierung</h2>
    <p>Bei einer <a href="/haussanierung-rhein-main">Haussanierung</a> ist die Prüfung des Sicherungskastens besonders wichtig. Ein Haus hat viele Nutzungsbereiche: Küche, Bad, Gäste-WC, Wohnräume, Schlafzimmer, Kinderzimmer, Homeoffice, Keller, Technikraum, Dachgeschoss, Außenbereich, Garage, Garten und manchmal eine Einliegerwohnung oder Gewerbenutzung. Die elektrische Verteilung muss diese Nutzung sicher und sinnvoll abbilden.</p>
    <p>Viele ältere Häuser wurden über Jahre erweitert. Steckdosen wurden ergänzt, Räume umgenutzt, Bäder modernisiert, Küchen erneuert, Außenbereiche elektrifiziert oder Heiztechnik angepasst. Oft wurde dabei punktuell gearbeitet, ohne das Gesamtsystem neu zu planen. Eine Haussanierung ist der richtige Zeitpunkt, den Sicherungskasten und die gesamte Elektrostruktur zu prüfen.</p>
    <p>Typische Fragen bei einer Haussanierung:</p>
    <ul>
      <li>Reicht der Sicherungskasten für alle Etagen und Räume?</li>
      <li>Sind Stromkreise sinnvoll aufgeteilt?</li>
      <li>Gibt es ausreichend Reserve für Erweiterungen?</li>
      <li>Werden Küche, Bad und Technik separat berücksichtigt?</li>
      <li>Muss der Keller oder Technikraum angepasst werden?</li>
      <li>Ist eine <a href="/waermepumpe-rhein-main">Wärmepumpe</a> geplant?</li>
      <li>Soll eine Wallbox vorbereitet werden?</li>
      <li>Gibt es Außenstrom für Garten, Garage oder Terrasse?</li>
      <li>Wird Netzwerk in mehreren Etagen benötigt?</li>
      <li>Muss <a href="/altbau-elektrik-erneuern-rhein-main">Altbau-Elektrik</a> erneuert werden?</li>
    </ul>
    <p>Radex koordiniert die Elektrofachbetriebe im Rahmen der Haussanierung. Dadurch kann die Prüfung des Sicherungskastens mit Innenausbau, Trockenbau, Böden, Wänden, Bad, Küche, Heizung, Sanitär und energetischen Maßnahmen verbunden werden. Besonders wenn Wände geöffnet oder Räume vollständig saniert werden, lassen sich Leitungen und Stromkreise besser vorbereiten.</p>
    <p>Bei bewohnten Häusern muss der Ablauf sorgfältig geplant werden. Stromversorgung, Zugänge, Bauabschnitte und Alltag müssen berücksichtigt werden. Bei leerstehenden Häusern, etwa nach Kauf oder vor Einzug, kann die Elektroerneuerung oft effizienter umgesetzt werden.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="https://wa.me/491744684189" class="btn-primary gold" target="_blank" rel="noopener">Angebot anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'sicherungskasten-bei-badsanierung',
    title: "Sicherungskasten bei Badsanierung",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="container">
    <h2>Sicherungskasten bei Badsanierung</h2>
    <p>Eine <a href="/badsanierung-rhein-main">Badsanierung</a> kann eine Prüfung des Sicherungskastens erforderlich machen. Moderne Bäder brauchen mehr Elektroplanung als frühere Bäder. Beleuchtung, Spiegelanschluss, Steckdosen, Lüfter, eventuell Dusch-WC, Komforttechnik, elektrische Zusatzfunktionen oder Handtuchwärmer müssen sicher und fachgerecht eingebunden werden.</p>
    <p>Im Bad gelten besondere Anforderungen, weil Feuchtigkeit, Wasser und elektrische Installationen auf engem Raum zusammenkommen. Elektroarbeiten im Bad müssen durch qualifizierte Elektrofachbetriebe ausgeführt werden. Radex koordiniert diese Fachpartner mit SHK, Abdichtung, Trockenbau, Fliesen und Innenausbau.</p>
    <p>Typische Elektrothemen im Bad:</p>
    <ul>
      <li>Licht am Spiegel</li>
      <li>Deckenbeleuchtung</li>
      <li>Steckdosen am Waschtisch</li>
      <li>Lüfteranschluss</li>
      <li>elektrische Zusatzfunktionen</li>
      <li>Sicherheitsbereiche im Nassraum</li>
      <li>Stromkreis und Absicherung</li>
      <li>Schalterpositionen</li>
      <li>Abstimmung mit Vorwandinstallation</li>
      <li>Koordination vor Fliesenarbeiten</li>
    </ul>
    <p>Wenn ein älteres Bad saniert wird, sollte geprüft werden, ob die vorhandene Elektrostruktur und der Sicherungskasten die neue Planung unterstützen. Es ist ungünstig, ein Bad hochwertig zu sanieren und erst danach festzustellen, dass Anschlüsse fehlen oder nicht sinnvoll abgesichert sind.</p>
    <p>Radex sorgt dafür, dass die Elektrokoordination rechtzeitig erfolgt. Die SHK-Seite der Badsanierung wird unter Meisterverantwortung geführt, Elektro wird über Fachpartner eingebunden. Dadurch können Badgestaltung, Sanitärinstallation, Abdichtung und Elektroplanung sinnvoll zusammenarbeiten.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Kostenlos beraten lassen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'sicherungskasten-bei-kuechenmodernisierung',
    title: "Sicherungskasten bei Küchenmodernisierung",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="container">
    <h2>Sicherungskasten bei Küchenmodernisierung</h2>
    <p>Die Küche ist einer der wichtigsten Gründe, einen Sicherungskasten prüfen zu lassen. Moderne Küchen haben deutlich höhere und differenziertere Anforderungen als frühere Küchen. Kochfeld, Backofen, Dampfgarer, Spülmaschine, Kühlschrank, Gefriergerät, Dunstabzug, Arbeitsflächensteckdosen, Beleuchtung, Kücheninsel, Kaffeevollautomat und weitere Geräte brauchen passende Anschlüsse und Stromkreise.</p>
    <p>Wenn die Unterverteilung veraltet oder knapp bemessen ist, kann die Küchenplanung eingeschränkt werden. Provisorische Mehrfachsteckdosen sind keine Lösung für dauerhaft hohe elektrische Lasten. Deshalb sollte vor der Küchenmodernisierung geprüft werden, ob Sicherungskasten und <a href="/elektroinstallation-rhein-main">Elektroinstallation</a> zur geplanten Küche passen.</p>
    <p>Typische Fragen:</p>
    <ul>
      <li>Gibt es eigene Stromkreise für leistungsstarke Geräte?</li>
      <li>Ist der Kochfeldanschluss passend?</li>
      <li>Sind Backofen, Spülmaschine und Kühlschrank berücksichtigt?</li>
      <li>Gibt es genug Steckdosen an der Arbeitsfläche?</li>
      <li>Ist Beleuchtung vorbereitet?</li>
      <li>Muss die Unterverteilung angepasst werden?</li>
      <li>Sind Wasser, Abwasser und Elektro auf die Küchenplanung abgestimmt?</li>
      <li>Wird eine Kücheninsel geplant?</li>
    </ul>
    <p>Radex koordiniert Küchenvorbereitung im Rahmen von Wohnungssanierungen, Haussanierungen und <a href="/komplettsanierung-rhein-main">Komplettsanierungen</a>. Sanitäranschlüsse werden unter SHK-Meisterverantwortung betrachtet. Elektroarbeiten werden über qualifizierte Elektrofachbetriebe eingebunden. So passen Strom, Wasser, Abwasser, Licht, Innenausbau und Küchenplanung besser zusammen.</p>
    <p>Gerade vor dem Einzug ist die Küchenmodernisierung ein entscheidender Zeitpunkt. Wer jetzt den Sicherungskasten prüft, vermeidet spätere Einschränkungen und Nacharbeiten.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="https://wa.me/491744684189" class="btn-primary gold" target="_blank" rel="noopener">Jetzt per WhatsApp anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'sicherungskasten-bei-waermepumpe-und-heizungsmodernisierung',
    title: "Sicherungskasten bei Wärmepumpe und Heizungsmodernisierung",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="container">
    <h2>Sicherungskasten bei Wärmepumpe und Heizungsmodernisierung</h2>
    <p>Eine <a href="/waermepumpe-rhein-main">Wärmepumpe</a> oder moderne Heiztechnik kann zusätzliche Anforderungen an die Elektroinstallation stellen. Stromversorgung, Steuerung, Regeltechnik, Außeneinheit, Inneneinheit, Technikraum und mögliche Zähler- oder Anschlussfragen müssen fachgerecht geprüft werden. Deshalb sollte bei einer <a href="/heizungsmodernisierung-rhein-main">Heizungsmodernisierung</a> auch der Sicherungskasten betrachtet werden.</p>
    <p>Radex ist im Bereich Heizung, Sanitär und Gebäudetechnik SHK-meistergeführt. Wenn elektrische Arbeiten für Wärmepumpe oder Heiztechnik erforderlich sind, werden qualifizierte Elektrofachpartner eingebunden und koordiniert. Diese Zusammenarbeit ist wichtig, weil SHK und Elektro bei moderner Heiztechnik eng zusammenhängen.</p>
    <p>Typische Schnittstellen:</p>
    <ul>
      <li>Stromversorgung für Wärmepumpe</li>
      <li>Absicherung und Unterverteilung</li>
      <li>Steuerung und Regeltechnik</li>
      <li>Technikraum</li>
      <li>Leitungsführung</li>
      <li>Außeneinheit und Inneneinheit</li>
      <li>Heizungsmodernisierung</li>
      <li>Warmwasserbereitung</li>
      <li>mögliche Wallbox-Vorbereitung</li>
      <li>energetische Sanierung</li>
    </ul>
    <p>Bei einer Haussanierung oder <a href="/komplettsanierung-rhein-main">Komplettsanierung</a> lassen sich diese Punkte besonders gut vorbereiten. Wenn Räume, Technikbereiche oder Wände ohnehin bearbeitet werden, können Leitungen und Anschlussmöglichkeiten besser geplant werden. Wird die elektrische Infrastruktur erst später angepasst, entstehen zusätzliche Eingriffe.</p>
    <p>Radex koordiniert die Abstimmung zwischen <a href="/heizungsmodernisierung-rhein-main">Heizungsmodernisierung</a>, <a href="/waermepumpe-rhein-main">Wärmepumpe</a>, Sicherungskasten und Elektrofachpartnern als Teil des Sanierungsablaufs.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Unverbindlich anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'sicherungskasten-und-wallbox-vorbereitung',
    title: "Sicherungskasten und Wallbox-Vorbereitung",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="container">
    <h2>Sicherungskasten und Wallbox-Vorbereitung</h2>
    <p>Viele Eigentümer möchten ihre Immobilie langfristig auf Elektromobilität vorbereiten. Eine Wallbox-Vorbereitung kann deshalb bei Haussanierung, <a href="/altbausanierung-rhein-main">Altbausanierung</a> oder Elektroerneuerung sinnvoll sein. Ob und wie eine Wallbox möglich ist, muss ein Elektrofachbetrieb fachgerecht prüfen. Dabei spielen Anschlussleistung, Sicherungskasten, Leitungswege, Garage, Stellplatz, Außenbereich und mögliche Laststeuerung eine Rolle.</p>
    <p>Typische Fragen:</p>
    <ul>
      <li>Gibt es einen geeigneten Stellplatz?</li>
      <li>Wie weit ist der Leitungsweg?</li>
      <li>Reicht die vorhandene elektrische Infrastruktur?</li>
      <li>Muss der Sicherungskasten angepasst werden?</li>
      <li>Ist eine spätere Wallbox nur vorzubereiten oder direkt umzusetzen?</li>
      <li>Gibt es weitere große Verbraucher wie <a href="/waermepumpe-rhein-main">Wärmepumpe</a>?</li>
      <li>Müssen Außenbereiche geöffnet werden?</li>
      <li>Wie wird die Wallbox in den Sanierungsablauf eingebunden?</li>
    </ul>
    <p>Radex koordiniert diese Prüfung im Rahmen der Sanierung. Besonders wenn Haus, Garage, Keller, Technikraum, Außenbereich oder Zufahrt ohnehin bearbeitet werden, kann eine Vorbereitung sinnvoll sein. Nicht jede Wallbox muss sofort eingebaut werden. Manchmal reicht es, Leitungswege oder Leerrohre vorzubereiten, damit später weniger Aufwand entsteht.</p>
    <p>Wichtig ist: Die Ausführung und technische Bewertung erfolgen durch Elektrofachbetriebe. Radex übernimmt die Koordination und sorgt dafür, dass Wallbox-Vorbereitung nicht isoliert, sondern im Zusammenhang mit Sicherungskasten, <a href="/elektroinstallation-rhein-main">Elektroinstallation</a>, <a href="/heizungsmodernisierung-rhein-main">Heizungsmodernisierung</a> und Gebäudenutzung betrachtet wird.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Beratungsgespräch vereinbaren</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'sicherungskasten-bei-gewerbe-buero-praxis-und-mieterausbau',
    title: "Sicherungskasten bei Gewerbe, Büro, Praxis und Mieterausbau",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="container">
    <h2>Sicherungskasten bei Gewerbe, Büro, Praxis und Mieterausbau</h2>
    <p>In Gewerbeflächen, Büros, Praxen, Ladenflächen und Mieterausbauten ist der Sicherungskasten oft besonders wichtig. Arbeitsplätze, Beleuchtung, Datentechnik, Geräte, Teeküche, Sanitärbereiche, Empfang, Kundenbereiche, Server, Praxisgeräte und Betriebsabläufe stellen andere Anforderungen als private Wohnräume.</p>
    <p>Wenn eine Gewerbefläche saniert oder für einen neuen Nutzer vorbereitet wird, sollte die elektrische Verteilung früh geprüft werden. Ein neuer Grundriss, zusätzliche Arbeitsplätze oder geänderte Nutzung können neue Stromkreise, mehr Steckdosen, andere Beleuchtung oder technische Anpassungen erforderlich machen.</p>
    <p>Typische Themen:</p>
    <ul>
      <li>Unterverteilung in Gewerbeflächen prüfen</li>
      <li>Stromkreise für Arbeitsplätze</li>
      <li>Beleuchtung für Büro, Praxis oder Laden</li>
      <li>Datentechnik und Netzwerk</li>
      <li>Teeküche und Geräteanschlüsse</li>
      <li>Sanitärbereiche</li>
      <li>Praxis- oder Spezialgeräte</li>
      <li>Trockenbau und Raumaufteilung</li>
      <li>Mieterausbau nach Nutzeranforderung</li>
      <li>Übergabetermin und Bauzeit</li>
    </ul>
    <p>Bei Gewerbeprojekten ist der Zeitplan oft besonders wichtig. Eine Fläche soll vermietet werden, ein Mieter möchte einziehen oder ein Betrieb soll möglichst wenig beeinträchtigt werden. Radex koordiniert Elektrofachpartner, Innenausbau, Sanitär, Trockenbau, Böden, Malerarbeiten und Übergabe, damit die Sanierung planbar bleibt.</p>
    <p>Eine gewerbliche <a href="/elektroinstallation-rhein-main">Elektroinstallation</a> muss zur späteren Nutzung passen. Deshalb sollte vor der Ausführung klar sein, wie die Fläche genutzt wird und welche technischen Anforderungen bestehen.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="https://wa.me/491744684189" class="btn-primary gold" target="_blank" rel="noopener">Angebot anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'sicherungskasten-bei-komplettsanierung-und-kernsanierung',
    title: "Sicherungskasten bei Komplettsanierung und Kernsanierung",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="container">
    <h2>Sicherungskasten bei Komplettsanierung und Kernsanierung</h2>
    <p>Bei <a href="/komplettsanierung-rhein-main">Komplettsanierung</a> und <a href="/kernsanierung-rhein-main">Kernsanierung</a> ist der Sicherungskasten ein zentraler Bestandteil der technischen Planung. Wenn eine Immobilie umfassend modernisiert oder tiefgreifend zurückgebaut wird, sollte die Elektrostruktur grundsätzlich geprüft werden. Leitungen, Stromkreise, Steckdosen, Licht, Küche, Bad, Netzwerk, Heiztechnik, Außenbereiche und Sicherungskasten müssen zusammenpassen.</p>
    <p>Bei einer Komplettsanierung werden viele Bereiche einer Immobilie erneuert. Bei einer Kernsanierung geht der Eingriff tiefer und betrifft oft Rückbau, technische Installationen, Wand- und Bodenaufbau, Innenstruktur und energetische Maßnahmen. In beiden Fällen ist die frühe Elektroprüfung wichtig.</p>
    <p>Typische Aufgaben:</p>
    <ul>
      <li>Sicherungskasten prüfen</li>
      <li>Unterverteilung erneuern oder anpassen lassen</li>
      <li>Stromkreise neu planen</li>
      <li>Leitungen prüfen oder erneuern</li>
      <li>Küche, Bad und Technikbereiche berücksichtigen</li>
      <li>Netzwerk und Homeoffice vorbereiten</li>
      <li>Wärmepumpe oder Wallbox einordnen</li>
      <li>Elektro mit Trockenbau, Böden und Wänden abstimmen</li>
      <li>Rückbau und mögliche Schadstoffthemen berücksichtigen</li>
    </ul>
    <p>Bei Kernsanierungen können Schadstoffthemen auftreten. Wenn alte Bodenbeläge, Kleber, Deckenmaterialien oder Dämmstoffe sichtbar werden, sollte bei Verdacht fachlich geprüft werden. Radex ist zertifiziert für Schimmel- und <a href="/asbestsanierung-rhein-main">Asbestsanierung</a> und kann solche Themen in den Sanierungsablauf integrieren.</p>
    <p>Radex koordiniert Sicherungskasten, Elektrofachpartner und weitere Gewerke, damit die technische Grundlage nicht erst nach dem Ausbau geklärt wird.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Kostenlos beraten lassen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'ablauf-sicherungskasten-erneuern-mit-radex',
    title: "Ablauf: Sicherungskasten erneuern mit Radex",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="container">
    <h2>Ablauf: Sicherungskasten erneuern mit Radex</h2>
    <p>Radex koordiniert die Prüfung und Erneuerung des Sicherungskastens im Rahmen einer Sanierung in klaren Schritten. Die Elektroarbeiten selbst werden durch qualifizierte Elektrofachbetriebe ausgeführt.</p>
    <div class="ablauf-steps">
      <div class="ablauf-step">
        <div class="ablauf-step-title">Erstes Gespräch</div>
        <p>Am Anfang wird geklärt, warum der Sicherungskasten geprüft werden soll. Geht es um Altbau, Wohnungssanierung, Haussanierung, neue Küche, Badsanierung, Wärmepumpe, Wallbox, Gewerbeumbau oder Komplettsanierung?</p>
      </div>
      <div class="ablauf-step">
        <div class="ablauf-step-title">Bestandsaufnahme</div>
        <p>Radex betrachtet den Sanierungsumfang und koordiniert die fachliche Prüfung durch Elektrofachpartner. Dabei werden Unterverteilung, Stromkreise, Leitungen, Küche, Bad, Heiztechnik, Netzwerk und geplante Erweiterungen berücksichtigt.</p>
      </div>
      <div class="ablauf-step">
        <div class="ablauf-step-title">Umfang festlegen</div>
        <p>Der Elektrofachbetrieb bewertet, ob eine Anpassung, Erweiterung oder Erneuerung des Sicherungskastens sinnvoll oder erforderlich ist. Radex bindet diese Einschätzung in die Gesamtplanung ein.</p>
      </div>
      <div class="ablauf-step">
        <div class="ablauf-step-title">Schnittstellen planen</div>
        <p>Elektro wird mit SHK, Trockenbau, Fliesen, Innenausbau, Küche, Böden, Malerarbeiten, Schadstoffprüfung und energetischen Maßnahmen abgestimmt.</p>
      </div>
      <div class="ablauf-step">
        <div class="ablauf-step-title">Ausführung koordinieren</div>
        <p>Die Arbeiten am Sicherungskasten und an der Elektroinstallation werden in der passenden Reihenfolge umgesetzt, bevor Wände geschlossen, Fliesen gesetzt oder Oberflächen fertiggestellt werden.</p>
      </div>
      <div class="ablauf-step">
        <div class="ablauf-step-title">Übergabe</div>
        <p>Zum Abschluss wird die Sanierung geordnet übergeben. Ziel ist eine elektrische Infrastruktur, die fachgerecht ausgeführt, praktisch nutzbar und in das gesamte Projekt eingebunden ist.</p>
      </div>
    </div>
    <p>Wer einen Sicherungskasten im Rhein-Main-Gebiet erneuern oder prüfen lassen möchte, kann Radex unter <a href="tel:+496074960620">06074 960620</a> erreichen.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="https://wa.me/491744684189" class="btn-primary gold" target="_blank" rel="noopener">Jetzt per WhatsApp anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'sicherungskasten-erneuern-im-rhein-main-gebiet',
    title: "Sicherungskasten erneuern im Rhein-Main-Gebiet",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="container">
    <h2>Sicherungskasten erneuern im Rhein-Main-Gebiet</h2>
    <p>Radex sitzt in Rödermark und begleitet Sanierungen mit Elektrokoordination im Rhein-Main-Gebiet. Viele Immobilien in der Region haben gute Substanz, attraktive Lagen und hohes Modernisierungspotenzial. Gleichzeitig entsprechen ältere Sicherungskästen und Elektroinstallationen nicht immer dem heutigen Bedarf.</p>
    <p>Ob Eigentumswohnung in Frankfurt oder Offenbach, Haus in Rödermark, Rodgau, Langen, Dreieich oder Neu-Isenburg, Bestandsimmobilie in Darmstadt oder Hanau, hochwertige Wohnlage in Bad Homburg, Kronberg, Königstein oder Bad Soden oder Gewerbefläche in Eschborn, Hofheim, Groß-Gerau, Rüsselsheim oder Maintal: Die Prüfung des Sicherungskastens sollte zum Objekt passen.</p>
    <p>Eine Wohnung in einem Mehrfamilienhaus braucht andere Abstimmungen als ein freistehendes Haus. Eine Küche stellt andere Anforderungen als ein Bad. Eine Wärmepumpe braucht andere elektrische Voraussetzungen als ein reiner Innenausbau. Eine Gewerbefläche hat andere Anforderungen als ein Einfamilienhaus.</p>
    <p>Radex koordiniert die passenden Elektrofachpartner objektbezogen und bindet die Arbeiten in die Sanierung ein. Entscheidend ist, dass der Sicherungskasten nicht losgelöst geplant wird, sondern mit Bad, Küche, <a href="/heizung-sanitaer-rhein-main">Heizung, Sanitär</a>, Innenausbau, Netzwerk, Nutzung und Zukunftsanforderungen zusammenpasst.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Unverbindlich anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'warum-radex-fuer-sicherungskasten-und-elektrokoordination',
    title: "Warum Radex für Sicherungskasten und Elektrokoordination?",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="container">
    <h2>Warum Radex für Sicherungskasten und Elektrokoordination?</h2>
    <p>Die Erneuerung eines Sicherungskastens ist ein sicherheitsrelevantes Fachthema und muss durch qualifizierte Elektrofachbetriebe ausgeführt werden. Radex übernimmt die gewerkeübergreifende Koordination im Rahmen der Sanierung und sorgt dafür, dass Elektro rechtzeitig mit Bad, Küche, Heizung, Sanitär, Innenausbau und Oberflächen abgestimmt wird.</p>
    <p>Die wichtigsten Vorteile:</p>
    <ul>
      <li><strong>Frühe Elektrokoordination:</strong> Der Sicherungskasten wird nicht erst nachträglich betrachtet, sondern früh in den Sanierungsablauf eingebunden.</li>
      <li><strong>Qualifizierte Fachpartner:</strong> Elektroarbeiten werden durch Elektrofachbetriebe umgesetzt.</li>
      <li><strong>Ein Ansprechpartner:</strong> Kunden müssen nicht jedes Gewerk einzeln abstimmen.</li>
      <li><strong>SHK-Meisterkompetenz:</strong> Heizung, Sanitär und Gebäudetechnik werden bei Radex unter Meisterverantwortung geführt.</li>
      <li><strong>Bestandskompetenz:</strong> Alte Leitungen, Unterverteilungen, Schadstoffverdacht, Feuchtigkeit und gewachsene Strukturen werden berücksichtigt.</li>
      <li><strong>Schnittstellenkompetenz:</strong> Bad, Küche, Wärmepumpe, Innenausbau, Netzwerk, Wallbox-Vorbereitung und Sicherungskasten werden im Gesamtprojekt betrachtet.</li>
      <li><strong>Regionale Nähe:</strong> Radex sitzt in Rödermark und arbeitet im Rhein-Main-Gebiet.</li>
    </ul>
    <p>Wer den Sicherungskasten in einer Wohnung, einem Haus, einem Altbau oder einer Gewerbefläche prüfen oder erneuern lassen möchte, kann Radex unter <a href="tel:+496074960620">06074 960620</a> anrufen oder das Projekt über den <a href="/kontakt">Kontaktbogen</a> anfragen.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Beratungsgespräch vereinbaren</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'warum-radex',
    title: "Warum Radex?",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Ihre Vorteile</div>
  <h2>Warum Radex?</h2>
  <div class="warum-grid" style="grid-template-columns:repeat(3,1fr)">
    <div class="warum-card"><div class="warum-card-num">01</div><h4>Klare Planung</h4><p>Transparente Abläufe von Anfang an.</p></div>
    <div class="warum-card"><div class="warum-card-num">02</div><h4>HSK Meisterbetrieb</h4><p>Fachgerechte Ausführung nach höchsten Standards.</p></div>
    <div class="warum-card"><div class="warum-card-num">03</div><h4>Alles aus einer Hand</h4><p>Koordination aller Arbeiten durch Radex.</p></div>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'so-laeuft-ihr-projekt-ab',
    title: "So läuft Ihr Projekt ab",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="section-label">Ablauf</div>
  <h2>So läuft Ihr Projekt ab</h2>
  <div class="process-grid">
    <div class="process-card">
      <div class="process-card-num">01</div>
      <h4>Beratung</h4>
      <p>Wir besprechen Ihre Wünsche in einem kostenlosen Erstgespräch.</p>
    </div>
    <div class="process-card">
      <div class="process-card-num">02</div>
      <h4>Planung</h4>
      <p>Radex erstellt ein klares Konzept mit Kosten und Zeitrahmen.</p>
    </div>
    <div class="process-card">
      <div class="process-card-num">03</div>
      <h4>Umsetzung</h4>
      <p>Die Umsetzung erfolgt sauber, termintreu und in höchster Qualität.</p>
    </div>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'haben-sie-fragen-unser-ki-assistent-hilft-sofort',
    title: "Haben Sie Fragen? Unser KI-Assistent hilft sofort.",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="ai-strip">
  <div class="ai-strip-left">
    <div class="ai-icon"><svg width="20" height="20" fill="none" viewBox="0 0 24 24" stroke="#C8861A" stroke-width="2"><path d="M12 2a2 2 0 012 2v2a2 2 0 01-2 2 2 2 0 01-2-2V4a2 2 0 012-2zm0 14a2 2 0 012 2v2a2 2 0 01-2 2 2 2 0 01-2-2v-2a2 2 0 012-2zM4 10a2 2 0 012-2h2a2 2 0 012 2 2 2 0 01-2 2H6a2 2 0 01-2-2zm10 0a2 2 0 012-2h2a2 2 0 012 2 2 2 0 01-2 2h-2a2 2 0 01-2-2z"/></svg></div>
    <div><h3>Haben Sie Fragen? Unser KI-Assistent hilft sofort.</h3><p>Kostenlos, rund um die Uhr – für alle Fragen zu Sanierung und Planung.</p></div>
  </div>
  <a href="../ki-assistent.php" class="btn-primary gold">KI-Assistent starten &rarr;</a>
</div>` }}
      />
    ),
  }
];
