/* Auto-generated by scripts/build-teilsanierung-legacy.mjs – do not edit by hand. */
/* eslint-disable react/no-danger */

export const teilsanierungLegacySections = [
  {
    id: 'gezielt-sanieren-im-bestand',
    title: "Gezielt sanieren im Bestand",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="intro-section">
  <div class="intro-text">
    <div class="section-label">Gezielt sanieren im Bestand</div>
    <p style="font-size:17px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine Teilsanierung ist sinnvoll, wenn nicht die komplette Immobilie erneuert werden muss, sondern einzelne Bereiche gezielt modernisiert, technisch verbessert oder instand gesetzt werden sollen. Viele Häuser, Wohnungen und Gewerbeflächen im Rhein-Main-Gebiet haben eine gute Grundlage. Nicht immer ist eine <a href="/komplettsanierung-rhein-main">Komplettsanierung</a> oder <a href="/kernsanierung-rhein-main">Kernsanierung</a> notwendig. Oft reicht es, Bad, Gäste-WC, Heizung, Sanitärleitungen, einzelne Räume, Böden, Wände, Innenausbau, Raumaufteilung, Feuchtigkeit, Schimmel oder bestimmte technische Schnittstellen sorgfältig zu prüfen und sinnvoll zu erneuern.</p>
    <p style="font-size:17px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Genau darin liegt der Wert einer guten Teilsanierung: Sie greift dort ein, wo es wirklich sinnvoll ist, und lässt intakte Bereiche bestehen. Eine Immobilie wird nicht pauschal aufgerissen, sondern gezielt weiterentwickelt. Für Eigentümer, Eigennutzer, Käufer, Vermieter, Hausverwaltungen und Gewerbekunden kann das wirtschaftlich, organisatorisch und baulich die richtige Lösung sein.</p>
    <p style="font-size:17px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Die Radex Objektmanagement GmbH aus Rödermark begleitet Teilsanierungen im Rhein-Main-Gebiet als koordinierender Sanierungspartner. Wenn mehrere Gewerke beteiligt sind, übernimmt Radex die Abstimmung als <a href="/generalunternehmer-rhein-main">Generalunternehmer</a>: ein Ansprechpartner, klare Projektsteuerung, abgestimmte Fachgewerke und ein nachvollziehbarer Ablauf.</p>
    <p style="font-size:17px;color:var(--text-light);line-height:1.75">Im Bereich Heizung, Sanitär und Gebäudetechnik ist Radex meistergeführt durch Bernd Knoop, SHK-Meister und Betriebsleiter. Sanitärinstallation, Wasserleitungen, Abwasser, Heizungsmodernisierung, Warmwasserbereitung, Heizkörper und Gebäudetechnik werden dadurch fachlich verantwortet. Weitere Gewerke wie Elektrotechnik, Trockenbau, Fliesen, Bodenverlegung, Malerarbeiten, <a href="/innenausbau-umbau-rhein-main">Innenausbau</a>, Dämmung oder <a href="/schimmelsanierung-rhein-main">Schadstoffsanierung</a> werden durch qualifizierte Fachpartner umgesetzt und von Radex koordiniert.</p>
    <div class="link-list" style="margin-top:24px">
      <a href="/generalunternehmer-rhein-main" class="link-pill">Generalunternehmer</a>
      <a href="/komplettsanierung-rhein-main" class="link-pill">Komplettsanierung</a>
      <a href="/kernsanierung-rhein-main" class="link-pill">Kernsanierung</a>
      <a href="/badsanierung-rhein-main" class="link-pill">Badsanierung</a>
      <a href="/heizung-sanitaer-rhein-main" class="link-pill">Heizung &amp; Sanitär</a>
      <a href="/kontakt" class="link-pill">Kontakt</a>
    </div>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'wann-ist-eine-teilsanierung-sinnvoll',
    title: "Wann ist eine Teilsanierung sinnvoll?",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Wann sinnvoll</div>
  <h2>Wann ist eine Teilsanierung sinnvoll?</h2>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine Teilsanierung ist sinnvoll, wenn bestimmte Bereiche einer Immobilie modernisiert werden sollen, ohne das gesamte Haus, die ganze Wohnung oder das komplette Objekt neu aufzubauen. Sie ist besonders geeignet, wenn die Immobilie insgesamt in gutem Zustand ist, aber einzelne Räume, technische Anlagen oder Oberflächen nicht mehr zum heutigen Anspruch passen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:16px">Typische Gründe für eine Teilsanierung sind:</p>
    <ul class="bullet-list">
      <li>das Bad ist veraltet, aber die restliche Wohnung ist gepflegt</li>
      <li>das Gäste-WC soll modernisiert werden</li>
      <li>die Heizung soll erneuert oder optimiert werden</li>
      <li>einzelne Sanitärleitungen müssen angepasst werden</li>
      <li>Böden, Wände oder Türen sollen in ausgewählten Räumen erneuert werden</li>
      <li>eine Wohnung soll nach Mieterwechsel teilweise modernisiert werden</li>
      <li>ein Haus soll in Etappen saniert werden</li>
      <li>eine Küche braucht neue Anschlüsse und vorbereitete Flächen</li>
      <li>ein Kellerraum zeigt Feuchtigkeit</li>
      <li>Schimmel soll fachlich bewertet und beseitigt werden</li>
      <li>ein Raum soll durch Trockenbau neu aufgeteilt werden</li>
      <li>ein Büro, eine Praxis oder Ladenfläche soll für neue Nutzung angepasst werden</li>
      <li>energetische Einzelmaßnahmen sollen mit Innenausbau kombiniert werden</li>
    </ul>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine Teilsanierung ist nicht automatisch eine kleine Baustelle. Sie kann technisch anspruchsvoll sein, wenn mehrere Gewerke beteiligt sind. Beispiel <a href="/badsanierung-rhein-main">Badsanierung</a>: Auch wenn nur ein Raum betroffen ist, müssen Rückbau, Wasserleitungen, Abwasser, Abdichtung, Lüftung, Heizung, Elektrokoordination, Fliesen und Endmontage zusammenpassen. Beispiel Heizungsmodernisierung: Auch wenn nur die Heizung erneuert wird, müssen Heizkörper, Wärmeverteilung, Warmwasser, Gebäudezustand und mögliche energetische Maßnahmen berücksichtigt werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Der Vorteil einer Teilsanierung liegt in der Fokussierung. Statt unnötig alle Bereiche zu öffnen, wird gezielt dort gearbeitet, wo ein echter Nutzen entsteht. Das kann Kosten reduzieren, Bauzeit verkürzen und den Alltag weniger belasten. Besonders bei bewohnten Immobilien ist eine Teilsanierung oft deutlich besser planbar als ein umfassender Eingriff.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Gleichzeitig sollte eine Teilsanierung nicht zu kurz gedacht werden. Wenn ein Bad geöffnet wird, sollten Leitungen und Abdichtung geprüft werden. Wenn Böden erneuert werden, sollten vorher Elektro- oder Wandarbeiten abgeschlossen sein. Wenn ein Raum umgebaut wird, müssen Heizung, Licht und Steckdosen mitgedacht werden. Radex prüft diese Schnittstellen früh, damit eine gezielte Sanierung nicht später neue Baustellen verursacht.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Wenn Sie unsicher sind, ob eine Teilsanierung ausreicht oder ob mehrere Maßnahmen besser zusammen geplant werden sollten, können Sie Radex unter <a href="tel:+496074960620">06074 960620</a> kontaktieren.</p>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Kostenlos beraten lassen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'teilsanierung-oder-komplettsanierung-was-passt-besser',
    title: "Teilsanierung oder Komplettsanierung – was passt besser?",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="section-label">Entscheidungshilfe</div>
  <h2>Teilsanierung oder Komplettsanierung – was passt besser?</h2>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Viele Eigentümer stehen vor der Frage, ob eine Teilsanierung reicht oder ob eine <a href="/komplettsanierung-rhein-main">Komplettsanierung</a> sinnvoller wäre. Die Antwort hängt nicht nur vom Budget ab, sondern vom Zustand der Immobilie, der geplanten Nutzung und den technischen Zusammenhängen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine Teilsanierung konzentriert sich auf einzelne Bereiche. Das kann ein Bad, ein Gäste-WC, eine Heizung, ein Keller, eine Wohnung nach Mieterwechsel, ein Raumumbau oder eine gezielte Modernisierung einzelner Oberflächen sein.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine Komplettsanierung umfasst mehrere zentrale Bereiche einer Immobilie. Bei einer Wohnung können Bad, Böden, Wände, Türen, Küche, Heizkörper und Elektrokoordination dazugehören. Bei einem Haus können Bad, Heizung, Sanitär, Innenausbau, Raumaufteilung, Keller und energetische Maßnahmen zusammenkommen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine <a href="/kernsanierung-rhein-main">Kernsanierung</a> geht noch tiefer. Sie umfasst stärkeren Rückbau, Leitungen, technische Installationen, Boden- und Wandaufbau, Innenstruktur und oft auch Schadstoffprüfung.</p>
  <div style="display:grid;grid-template-columns:1fr 1fr;gap:32px;max-width:960px;align-items:start;margin-top:8px">
    <div>
      <h3 style="color:var(--navy);font-size:17px;margin-bottom:12px">Eine Teilsanierung passt häufig, wenn:</h3>
      <ul class="bullet-list">
        <li>die Immobilie insgesamt gepflegt ist</li>
        <li>nur einzelne Räume modernisiert werden sollen</li>
        <li>Technik in anderen Bereichen noch zuverlässig ist</li>
        <li>der Eingriff bewusst klein gehalten werden soll</li>
        <li>im bewohnten Zustand saniert wird</li>
        <li>eine Sanierung in Etappen geplant ist</li>
        <li>Budget und Zeitrahmen begrenzt sind</li>
        <li>die Maßnahme klar abgrenzbar ist</li>
      </ul>
    </div>
    <div>
      <h3 style="color:var(--navy);font-size:17px;margin-bottom:12px">Eine Komplettsanierung kann besser sein, wenn:</h3>
      <ul class="bullet-list">
        <li>mehrere Bereiche gleichzeitig betroffen sind</li>
        <li>vor dem Einzug saniert wird</li>
        <li>Bad, Heizung, Elektro, Böden und Innenausbau zusammenhängen</li>
        <li>spätere Nacharbeiten vermieden werden sollen</li>
        <li>die Immobilie nach Kauf neu ausgerichtet wird</li>
        <li>technische Installationen insgesamt veraltet sind</li>
        <li>eine Wohnung bezugsfertig oder vermietbar hergestellt werden soll</li>
      </ul>
    </div>
  </div>
  <div style="margin-top:28px">
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex hilft bei dieser Entscheidung. Wichtig ist, nicht nur den sichtbaren Zustand zu betrachten. Ein gepflegter Raum kann technisch veraltet sein. Umgekehrt muss ein älteres Gebäude nicht automatisch komplett saniert werden. Entscheidend ist die Bestandsaufnahme.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Gerade bei Teilsanierungen ist ehrliche Beratung wichtig. Eine zu kleine Maßnahme kann später teuer werden, wenn wichtige Schnittstellen ignoriert werden. Eine zu große Maßnahme kann unnötig sein, wenn der Bestand gut ist. Radex prüft deshalb objektbezogen und empfiehlt eine Sanierungstiefe, die zum Projekt passt.</p>
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="https://wa.me/491744684189" class="btn-primary gold" target="_blank" rel="noopener">Jetzt per WhatsApp anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'badsanierung-als-teilsanierung-ein-raum-viele-schnittstellen',
    title: "Badsanierung als Teilsanierung – ein Raum, viele Schnittstellen",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Bad &amp; Sanitär</div>
  <h2>Badsanierung als Teilsanierung – ein Raum, viele Schnittstellen</h2>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Das Badezimmer ist einer der häufigsten Gründe für eine Teilsanierung. Viele Eigentümer möchten nicht das ganze Haus oder die gesamte Wohnung sanieren, sondern zunächst das Bad modernisieren. Das ist oft sinnvoll, weil das Bad im Alltag stark genutzt wird und technische Themen wie Wasser, Abwasser, Abdichtung, Heizung und Lüftung zusammenkommen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine <a href="/badsanierung-rhein-main">Badsanierung</a> als Teilsanierung kann sehr unterschiedlich aussehen. Manchmal soll nur die Badewanne durch eine Dusche ersetzt werden. Manchmal wird ein kleines Bad neu geplant. Manchmal geht es um ein Gäste-WC. Manchmal soll ein barrierearmes Bad entstehen. Manchmal muss das Bad vollständig zurückgebaut und technisch neu aufgebaut werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:16px">Typische Leistungen:</p>
    <ul class="bullet-list">
      <li>Rückbau alter Sanitärobjekte und Fliesen</li>
      <li>Wasserleitungen und Abwasserleitungen prüfen</li>
      <li>Sanitärinstallation unter SHK-Meisterverantwortung</li>
      <li>Abdichtung im Nassbereich</li>
      <li>bodengleiche Dusche oder neue Duschlösung</li>
      <li>Badewanne austauschen oder entfernen</li>
      <li>WC, Waschtisch, Armaturen und Badmöbel</li>
      <li>Heizkörpertausch oder Handtuchheizkörper</li>
      <li>Lüftung prüfen oder anpassen</li>
      <li>Elektrokoordination für Licht, Steckdosen, Spiegel und Lüfter</li>
      <li>Trockenbau und Vorwandinstallation</li>
      <li>Fliesen, Oberflächen und Endmontage</li>
    </ul>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bei einer Badsanierung ist die Reihenfolge entscheidend. Erst Rückbau und Prüfung, dann Leitungen und Abdichtung, dann Trockenbau und Fliesen, dann Endmontage. Wenn diese Schritte nicht sauber koordiniert werden, können Feuchtigkeit, undichte Bereiche, falsche Anschlüsse oder unnötige Nacharbeiten entstehen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex bringt bei Badsanierungen die SHK-Meisterkompetenz ein und koordiniert die weiteren Fachgewerke. Dadurch müssen Eigentümer nicht separat Sanitärbetrieb, Fliesenleger, Trockenbauer, Elektriker und Maler abstimmen. Besonders bei kleinen Bädern, engen Grundrissen oder bewohnten Wohnungen ist diese Koordination wertvoll.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine Badsanierung als Teilsanierung ist auch eine gute Gelegenheit, langfristig zu denken. Bodengleiche Dusche, rutschhemmende Oberflächen, gute Beleuchtung, Stauraum, pflegeleichte Materialien und ergonomische Armaturen machen den Alltag angenehmer. Nicht jedes Bad muss luxuriös sein, aber jedes Bad sollte technisch sauber und gut nutzbar sein.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Wer sein Bad im Rhein-Main-Gebiet sanieren möchte, kann Radex unter <a href="tel:+496074960620">06074 960620</a> erreichen oder die Anfrage über den <a href="/kontakt">Kontaktbogen</a> stellen.</p>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Unverbindlich anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'teilsanierung-im-haus-schritt-fuer-schritt-sinnvoll-modernisieren',
    title: "Teilsanierung im Haus – Schritt für Schritt sinnvoll modernisieren",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="section-label">Haus sanieren in Etappen</div>
  <h2>Teilsanierung im Haus – Schritt für Schritt sinnvoll modernisieren</h2>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Viele Hauseigentümer möchten ihre Immobilie nicht auf einmal komplett sanieren. Das kann aus Budgetgründen, wegen der Wohnsituation oder aus praktischen Gründen sinnvoll sein. Eine Teilsanierung im Haus ermöglicht, einzelne Bereiche gezielt zu verbessern und trotzdem einen langfristigen Gesamtplan im Blick zu behalten.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:16px">Typische Teilsanierungen im Haus:</p>
    <ul class="bullet-list">
      <li>Bad oder Gäste-WC sanieren</li>
      <li>Heizung erneuern</li>
      <li>Heizkörper tauschen</li>
      <li>Sanitärleitungen in bestimmten Bereichen anpassen</li>
      <li>Keller oder Feuchtigkeit prüfen</li>
      <li>einzelne Räume modernisieren</li>
      <li>Küche technisch vorbereiten</li>
      <li>Böden und Wände in Wohnbereichen erneuern</li>
      <li>Raumaufteilung ändern</li>
      <li>Trockenbau oder Innenausbau umsetzen</li>
      <li>energetische Einzelmaßnahmen planen</li>
      <li>Schimmel oder Schadstoffverdacht klären</li>
    </ul>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Wichtig ist, dass Teilsanierungen nicht isoliert gedacht werden. Wenn heute das Bad saniert wird, sollte klar sein, ob später Heizung, Leitungen oder angrenzende Räume betroffen sein könnten. Wenn heute die Heizung erneuert wird, sollte der Zustand der Heizkörper und des Gebäudes berücksichtigt werden. Wenn heute Böden erneuert werden, sollten vorher staubintensive Arbeiten erledigt sein.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex hilft, eine sinnvolle Reihenfolge für Etappen zu entwickeln. Dadurch kann ein Haus über mehrere Schritte modernisiert werden, ohne dass bereits erledigte Arbeiten später wieder geöffnet werden müssen. Das ist besonders wichtig bei bewohnten Häusern. Eigentümer können in Abschnitten sanieren und trotzdem vermeiden, dass Maßnahmen gegeneinander arbeiten.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Ein Beispiel: Ein Haus in Rödermark, Langen, Rodgau, Dreieich oder Neu-Isenburg soll nicht komplett saniert werden. Die Eigentümer möchten zuerst das Bad erneuern und die Heizung prüfen. Später sollen Böden und Innenausbau folgen. Radex kann prüfen, ob bei der Badsanierung bereits Leitungen, Heizkörper oder Elektrokoordination so vorbereitet werden sollten, dass spätere Maßnahmen einfacher werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Eine Teilsanierung im Haus ist also nicht nur eine kleine Sanierung. Sie ist ein geplanter Abschnitt einer größeren Immobilienentwicklung. Wer früh richtig plant, saniert ruhiger, wirtschaftlicher und mit weniger Nacharbeit.</p>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Beratungsgespräch vereinbaren</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'teilsanierung-einer-wohnung-nach-kauf-mieterwechsel-oder-laengerer-nutzung',
    title: "Teilsanierung einer Wohnung – nach Kauf, Mieterwechsel oder längerer Nutzung",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Wohnung modernisieren</div>
  <h2>Teilsanierung einer Wohnung – nach Kauf, Mieterwechsel oder längerer Nutzung</h2>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Wohnungen werden häufig nicht komplett kernsaniert, sondern gezielt teilsaniert. Nach einem Mieterwechsel soll eine Wohnung wieder vermietbar werden. Nach einem Kauf sollen Bad, Böden und Wände vor dem Einzug modernisiert werden. Nach längerer Nutzung sollen einzelne Räume erneuert werden. Bei Eigentumswohnungen kann eine Teilsanierung sehr sinnvoll sein, wenn der Grundzustand gut ist und nur bestimmte Bereiche nicht mehr passen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:16px">Typische Teilsanierungen in Wohnungen:</p>
    <ul class="bullet-list">
      <li>Bad modernisieren</li>
      <li>Gäste-WC erneuern</li>
      <li>Bodenbeläge austauschen</li>
      <li>Wände und Decken glätten oder streichen</li>
      <li>Türen und Zargen erneuern</li>
      <li>Heizkörper prüfen oder tauschen</li>
      <li>Küchenanschlüsse vorbereiten</li>
      <li>Elektrokoordination für Küche, Bad und Homeoffice</li>
      <li>Trockenbau für Nischen oder Abtrennungen</li>
      <li>Schimmel oder Feuchtigkeit prüfen</li>
      <li>Wohnung nach Mieterwechsel wiederherstellen</li>
    </ul>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">In Mehrfamilienhäusern sind Organisation und Rücksicht wichtig. Treppenhaus, Aufzug, Nachbarn, Hausordnung, Arbeitszeiten, Entsorgung und Materialtransport müssen eingeplant werden. Wenn ein Bad saniert wird, können Leitungsführung, Schallschutz und Abstimmungen mit der Hausverwaltung relevant sein. Radex berücksichtigt diese Rahmenbedingungen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Für Vermieter ist eine Teilsanierung oft wirtschaftlich sinnvoll. Nicht jede Wohnung braucht eine vollständige Komplettsanierung. Manchmal reichen ein neues Bad, robuste Böden, saubere Wandflächen, funktionsfähige Anschlüsse und eine gepflegte Übergabe. In anderen Fällen zeigt die Bestandsaufnahme, dass eine umfassendere Sanierung besser wäre. Radex hilft, diesen Unterschied zu erkennen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Für Eigennutzer steht stärker der Komfort im Vordergrund. Eine Wohnung soll vor dem Einzug so vorbereitet werden, dass der Alltag funktioniert. Steckdosen, Licht, Bad, Küche, Stauraum, Böden und Oberflächen sollten deshalb nicht getrennt voneinander geplant werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Wer eine Wohnung im Rhein-Main-Gebiet teilweise sanieren möchte, kann Radex unter <a href="tel:+496074960620">06074 960620</a> kontaktieren. Besonders vor Einzug oder nach Mieterwechsel ist eine frühe Planung sinnvoll.</p>

  <div style="text-align:center;margin-top:40px;">
    <a href="https://wa.me/491744684189" class="btn-primary gold" target="_blank" rel="noopener">Angebot anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'teilsanierung-nach-immobilienkauf-nicht-alles-neu-aber-das-richtige-zuerst',
    title: "Teilsanierung nach Immobilienkauf – nicht alles neu, aber das Richtige zuerst",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="section-label">Nach Immobilienkauf</div>
  <h2>Teilsanierung nach Immobilienkauf – nicht alles neu, aber das Richtige zuerst</h2>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Nach einem Hauskauf oder Wohnungskauf stellt sich häufig die Frage: Was muss sofort gemacht werden, und was kann später folgen? Nicht jede gekaufte Immobilie braucht eine Komplettsanierung. Manche Häuser und Wohnungen sind gepflegt und solide, benötigen aber gezielte Teilsanierungen, damit sie zum neuen Eigentümer, zur Nutzung und zum heutigen technischen Anspruch passen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:16px">Typische Maßnahmen nach Kauf:</p>
    <ul class="bullet-list">
      <li>Bad vor Einzug sanieren</li>
      <li>Heizung prüfen oder modernisieren</li>
      <li>Sanitärleitungen in Bad oder Küche bewerten</li>
      <li>Elektrokoordination für Küche, Bad und Homeoffice</li>
      <li>Bodenbeläge erneuern</li>
      <li>Wände und Decken überarbeiten</li>
      <li>Türen und Zargen tauschen</li>
      <li>Feuchtigkeit oder Schimmel prüfen</li>
      <li>Keller bewerten</li>
      <li>Raumaufteilung punktuell verbessern</li>
      <li>energetische Einzelmaßnahmen planen</li>
    </ul>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Der Vorteil nach Kauf liegt darin, dass die Immobilie häufig noch leer ist. Staubintensive Arbeiten, Rückbau, Badmodernisierung, Bodenarbeiten oder Leitungsanpassungen lassen sich vor dem Einzug deutlich besser umsetzen. Gleichzeitig sollte nicht planlos alles begonnen werden. Eine Teilsanierung nach Kauf braucht Prioritäten.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex hilft, die richtigen Fragen zu stellen: Welche Arbeiten wären später im bewohnten Zustand besonders störend? Welche Maßnahmen hängen technisch zusammen? Welche Leitungen sollten geprüft werden, bevor Oberflächen geschlossen werden? Welche Räume sollen sofort fertig sein? Welche Arbeiten können später ohne großen Schaden folgen?</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Ein Beispiel: Ein Käufer möchte eine Wohnung in Frankfurt, Offenbach, Darmstadt oder Hanau beziehen. Das Bad ist älter, die Böden sind abgenutzt, die Küche soll neu geplant werden und einige Steckdosen fehlen. Eine gezielte Teilsanierung kann ausreichen, wenn Leitungen und Technik grundsätzlich in Ordnung sind. Wenn jedoch Bad, Elektro, Heizung, Böden und Wände umfassend betroffen sind, sollte eine <a href="/komplettsanierung-rhein-main">Komplettsanierung</a> geprüft werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Radex bewertet diese Situation objektbezogen und hilft, unnötige Arbeiten zu vermeiden, ohne wichtige Themen zu übersehen.</p>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Kostenlos beraten lassen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'heizung-und-sanitaer-als-teilsanierung',
    title: "Heizung und Sanitär als Teilsanierung",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Heizung &amp; Sanitär</div>
  <h2>Heizung und Sanitär als Teilsanierung</h2>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Heizung und Sanitär sind häufig Auslöser für gezielte Teilsanierungen. Eine Heizung soll modernisiert werden, ohne das ganze Haus umzubauen. Ein Bad braucht neue Leitungen. Ein Gäste-WC soll erneuert werden. Heizkörper sollen getauscht werden. Warmwasser soll verbessert werden. Küchenanschlüsse müssen angepasst werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Im Bereich <a href="/heizung-sanitaer-rhein-main">Heizung, Sanitär und Gebäudetechnik</a> ist Radex meistergeführt durch Bernd Knoop, SHK-Meister und Betriebsleiter. Das ist bei Teilsanierungen besonders wichtig, weil auch kleine Eingriffe technisch sauber ausgeführt werden müssen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:16px">Typische SHK-Teilsanierungen:</p>
    <ul class="bullet-list">
      <li>Sanitärinstallation im Bad</li>
      <li>Wasserleitungen und Abwasserleitungen anpassen</li>
      <li>Gäste-WC modernisieren</li>
      <li>Heizkörper tauschen</li>
      <li>Heizungsmodernisierung planen</li>
      <li>Warmwasserbereitung prüfen</li>
      <li>Fußbodenheizung in Teilbereichen prüfen</li>
      <li>Küchenanschlüsse vorbereiten</li>
      <li>Armaturen, WC, Waschtisch, Dusche oder Badewanne erneuern</li>
      <li>Leitungsführung bei Umbau abstimmen</li>
    </ul>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine Heizungsmodernisierung als Teilsanierung sollte nicht nur das Heizgerät betrachten. Passt die neue Anlage zum Gebäude? Sind Heizflächen ausreichend? Wie ist der Warmwasserbedarf? Sind Heizkörper sinnvoll angeordnet? Wird später energetisch saniert? Ist eine Wärmepumpe realistisch oder braucht das Gebäude vorher Anpassungen?</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Auch Sanitärarbeiten sollten nicht isoliert erfolgen. Wenn ein Bad geöffnet wird, ist der richtige Zeitpunkt, Leitungen und Anschlüsse zu prüfen. Wenn Küchenanschlüsse angepasst werden, sollten Elektrokoordination und spätere Küchenplanung mitgedacht werden. Wenn Heizkörper versetzt werden, betrifft das Innenausbau, Wände und Böden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Radex verbindet SHK-Meisterkompetenz mit Gewerkeabstimmung. Dadurch werden Heizung und Sanitär nicht als Einzelmaßnahme ohne Blick auf das Gesamtprojekt behandelt.</p>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Heizungsberatung anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'innenausbau-boeden-und-raumaufteilung-als-teilsanierung',
    title: "Innenausbau, Böden und Raumaufteilung als Teilsanierung",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="section-label">Innenausbau &amp; Raumaufteilung</div>
  <h2>Innenausbau, Böden und Raumaufteilung als Teilsanierung</h2>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Nicht jede Teilsanierung beginnt mit Bad oder Heizung. Häufig geht es um Wohnräume, Innenausbau, neue Raumaufteilung, Böden, Wände, Decken, Türen oder Trockenbau. Gerade in Bestandsimmobilien kann eine gezielte <a href="/innenausbau-umbau-rhein-main">Innenausbau</a>-Teilsanierung den Alltag stark verbessern.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:16px">Typische Innenausbau-Teilsanierungen:</p>
    <ul class="bullet-list">
      <li>Raumaufteilung ändern</li>
      <li>Wand entfernen oder neue Wand setzen</li>
      <li>Trockenbau für Homeoffice, Kinderzimmer oder Abstellbereich</li>
      <li>Böden erneuern</li>
      <li>Wände und Decken glätten</li>
      <li>Türen, Zargen und Sockelleisten erneuern</li>
      <li>Nischen und Stauraum schaffen</li>
      <li>Kellerraum nutzbarer machen</li>
      <li>Dachgeschoss oder einzelnes Zimmer ausbauen</li>
      <li>Gewerbefläche neu aufteilen</li>
    </ul>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Wenn eine Wand entfernt werden soll, müssen Statik, Leitungen, Elektro und Oberflächen geprüft werden. Wenn ein neuer Raum entsteht, braucht er Licht, Steckdosen und gegebenenfalls Heizung. Wenn ein Boden erneuert wird, müssen Untergrund, Aufbauhöhe, Übergänge und spätere Arbeiten berücksichtigt werden. Innenausbau ist deshalb oft stärker mit Technik verbunden, als es auf den ersten Blick wirkt.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex koordiniert Innenausbau-Teilsanierungen mit den passenden Fachpartnern. Elektroarbeiten werden durch qualifizierte Elektrofachpartner ausgeführt. SHK-Themen werden unter Meisterverantwortung betrachtet, wenn Heizung oder Sanitär betroffen sind. Trockenbau, Boden, Malerarbeiten und Oberflächen werden aufeinander abgestimmt.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Eine gute Teilsanierung im Innenausbau hat ein klares Ziel. Soll der Raum heller wirken? Soll ein Homeoffice entstehen? Soll eine Wohnung moderner und vermietbarer werden? Soll ein Haus für eine neue Lebensphase angepasst werden? Je klarer das Ziel, desto besser kann die Maßnahme geplant werden.</p>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Unverbindlich anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'schimmel-feuchtigkeit-und-schadstoffthemen-bei-teilsanierungen',
    title: "Schimmel, Feuchtigkeit und Schadstoffthemen bei Teilsanierungen",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Schimmel &amp; Schadstoffe</div>
  <h2>Schimmel, Feuchtigkeit und Schadstoffthemen bei Teilsanierungen</h2>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Teilsanierungen im Bestand können Feuchtigkeit, Schimmel oder Schadstoffverdacht sichtbar machen. Das betrifft besonders Bäder, Keller, alte Bodenbeläge, Wandflächen, Rohrisolierungen, abgehängte Decken oder Bereiche, die längere Zeit verdeckt waren.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex ist zertifiziert für Schimmel- und Asbestsanierung und verfügt über Sachkunde nach TRGS 519. Bei Verdacht auf Asbest, schadstoffhaltige Materialien oder <a href="/schimmelsanierung-rhein-main">Schimmel</a> sollte nicht einfach weitergearbeitet werden. Verdächtige Materialien sollten nicht eigenständig gebrochen, geschliffen, gebohrt oder entfernt werden. Erst prüfen, dann handeln.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:16px">Typische Situationen bei Teilsanierungen:</p>
    <ul class="bullet-list">
      <li>Schimmel im Bad</li>
      <li>Feuchtigkeit hinter Fliesen</li>
      <li>Kellerfeuchtigkeit</li>
      <li>alte PVC-Bodenplatten oder Kleber</li>
      <li>alte Rohrisolierungen</li>
      <li>verdächtige Deckenplatten</li>
      <li>dunkle Stellen an Außenwänden</li>
      <li>Feuchtigkeit nach Leitungsproblemen</li>
      <li>Schimmel nach falscher Lüftung oder Wärmebrücken</li>
      <li>Schadstoffverdacht vor Rückbauarbeiten</li>
    </ul>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine Teilsanierung kann der richtige Moment sein, solche Themen fachlich zu klären. Wenn ein Bad ohnehin geöffnet wird, können Feuchtigkeit, Abdichtung und Leitungen geprüft werden. Wenn alte Böden entfernt werden, können darunterliegende Materialien bewertet werden. Wenn Kellerbereiche modernisiert werden, sollte die Ursache von Feuchtigkeit verstanden werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Wichtig ist, die Immobilie nicht schlechtzureden. Schimmel oder Schadstoffverdacht bedeutet nicht, dass ein Haus grundsätzlich problematisch ist. Es bedeutet, dass bei bestimmten Bauteilen fachlich sauber gearbeitet werden muss. Radex integriert solche Punkte in den Sanierungsablauf, damit die Maßnahme sicher und nachvollziehbar weitergeführt werden kann.</p>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Beratungsgespräch vereinbaren</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'teilsanierung-im-gewerbe-buero-oder-objektbestand',
    title: "Teilsanierung im Gewerbe, Büro oder Objektbestand",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="section-label">Gewerbe &amp; Objektbestand</div>
  <h2>Teilsanierung im Gewerbe, Büro oder Objektbestand</h2>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Auch Gewerbeflächen werden häufig teilsaniert. Ein Büro braucht neue Raumaufteilung. Eine Praxisfläche soll modernisiert werden. Eine Ladenfläche wird für einen neuen Mieter vorbereitet. Ein Sanitärbereich ist veraltet. Bodenbeläge müssen erneuert werden. Wände, Decken und Elektrokoordination sollen an die neue Nutzung angepasst werden.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:16px">Typische gewerbliche Teilsanierungen:</p>
    <ul class="bullet-list">
      <li>Büroumbau einzelner Bereiche</li>
      <li>Mieterausbau vor Übergabe</li>
      <li>Sanitärbereich modernisieren</li>
      <li>Trockenbau für neue Raumaufteilung</li>
      <li>Bodenbeläge erneuern</li>
      <li>Malerarbeiten und Oberflächen</li>
      <li>Elektrokoordination für Licht, Steckdosen und Datentechnik</li>
      <li>Praxisumbau oder Ladenumbau</li>
      <li>Gewerbefläche nach Mieterwechsel vorbereiten</li>
      <li>Schadstoffverdacht vor Rückbau prüfen</li>
    </ul>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Bei Gewerbeprojekten ist der Zeitplan häufig besonders wichtig. Ein Mieter möchte einziehen, ein Betrieb soll weiterlaufen oder eine Fläche soll schnell wieder nutzbar sein. Eine Teilsanierung kann hier sinnvoll sein, wenn nicht die gesamte Fläche erneuert werden muss, sondern nur bestimmte Bereiche.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex koordiniert Gewerbe-Teilsanierungen als <a href="/generalunternehmer-rhein-main">Generalunternehmer</a>, wenn mehrere Gewerke beteiligt sind. Rückbau, Trockenbau, Boden, Malerarbeiten, Sanitärbereiche, Elektrokoordination und Übergabe werden abgestimmt. Dadurch reduziert sich der Organisationsaufwand für Eigentümer, Vermieter, Unternehmen und Hausverwaltungen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Gerade bei Gewerbeflächen ist es wichtig, die spätere Nutzung früh zu kennen. Ein Büro braucht andere Steckdosen, Datentechnik und Beleuchtung als eine Praxis. Eine Ladenfläche braucht andere Wege, Oberflächen und Sanitärbereiche als ein klassischer Büroraum. Radex plant die Teilsanierung so, dass die Fläche nach der Maßnahme nutzbar ist.</p>

  <div style="text-align:center;margin-top:40px;">
    <a href="https://wa.me/491744684189" class="btn-primary gold" target="_blank" rel="noopener">Angebot anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'ablauf-einer-teilsanierung-mit-radex',
    title: "Ablauf einer Teilsanierung mit Radex",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">So läuft es ab</div>
  <h2>Ablauf einer Teilsanierung mit Radex</h2>
  <p style="font-size:16px;color:var(--text-light);line-height:1.75;max-width:720px;margin-bottom:8px">Eine Teilsanierung wirkt kleiner als eine Komplettsanierung, braucht aber trotzdem eine klare Struktur. Besonders wenn mehrere Gewerke beteiligt sind, entscheidet die Reihenfolge über Qualität, Zeitplan und Kosten.</p>

  <ol class="phase-list" style="max-width:800px">
    <li>
      <div>
        <strong>Erstgespräch</strong>
        Am Anfang wird geklärt, welcher Bereich saniert werden soll. Geht es um Bad, Heizung, Sanitär, Wohnung, Haus, Innenausbau, Keller, Gewerbefläche oder Schadstoffthemen? Ist das Objekt bewohnt, leer, vermietet oder gewerblich genutzt?
      </div>
    </li>
    <li>
      <div>
        <strong>Bestandsaufnahme</strong>
        Radex prüft den betroffenen Bereich und die relevanten Schnittstellen. Bei einem Bad sind Leitungen, Abdichtung, Heizung, Lüftung und Elektrokoordination wichtig. Bei Innenausbau sind Wände, Böden, Leitungen, Licht und Nutzung entscheidend. Bei Heizung und Sanitär werden technische Grundlagen bewertet.
      </div>
    </li>
    <li>
      <div>
        <strong>Umfang festlegen</strong>
        Anschließend wird definiert, welche Arbeiten zur Teilsanierung gehören und welche nicht. Diese Grenze ist wichtig, damit der Kunde weiß, was umgesetzt wird und was später folgen kann.
      </div>
    </li>
    <li>
      <div>
        <strong>Reihenfolge planen</strong>
        Die Gewerke werden in eine sinnvolle Reihenfolge gebracht. Rückbau, Prüfung, Rohinstallation, Trockenbau, Abdichtung, Oberflächen, Boden, Malerarbeiten und Endmontage müssen zueinander passen.
      </div>
    </li>
    <li>
      <div>
        <strong>Angebot und Vorbereitung</strong>
        Radex erstellt ein nachvollziehbares Angebot. Materialien, Fachpartner, Zeitfenster, Schutzmaßnahmen, Hausordnung, Zugänge und offene Entscheidungen werden abgestimmt.
      </div>
    </li>
    <li>
      <div>
        <strong>Ausführung und Koordination</strong>
        Während der Umsetzung koordiniert Radex die beteiligten Fachgewerke. SHK-Leistungen werden unter Meisterverantwortung geführt. Weitere Gewerke werden über qualifizierte Fachpartner eingebunden.
      </div>
    </li>
    <li>
      <div>
        <strong>Übergabe</strong>
        Am Ende wird die Teilsanierung geprüft und übergeben. Ziel ist ein Ergebnis, das nicht nur sichtbar fertig ist, sondern technisch und praktisch funktioniert.
      </div>
    </li>
  </ol>

  <div style="text-align:center;margin-top:40px;">
    <a href="https://wa.me/491744684189" class="btn-primary gold" target="_blank" rel="noopener">Ablauf besprechen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'teilsanierung-im-rhein-main-gebiet-regional-gezielt-und-planbar',
    title: "Teilsanierung im Rhein-Main-Gebiet – regional, gezielt und planbar",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section" style="background:var(--off-white)">
  <div class="section-label">Einsatzgebiet</div>
  <h2>Teilsanierung im Rhein-Main-Gebiet – regional, gezielt und planbar</h2>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Radex sitzt in Rödermark und begleitet Teilsanierungen im Rhein-Main-Gebiet. Die Region ist vielfältig: Wohnungen in Frankfurt, Häuser in Rödermark, Reihenhäuser in Rodgau, Eigentumswohnungen in Offenbach, Familienhäuser in Langen, Bestandsimmobilien in Darmstadt, Gewerbeflächen in Eschborn, hochwertige Wohnlagen in Bad Homburg, Kronberg, Königstein oder Bad Soden und viele weitere Situationen.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75;margin-bottom:20px">Eine Teilsanierung kann in jeder dieser Immobilien anders aussehen. In einer Stadtwohnung geht es häufig um Bad, Böden, Wände, Türen und Hausverwaltung. In einem Einfamilienhaus stehen Bad, Heizung, Sanitär, Keller und Innenausbau im Vordergrund. In einer Gewerbefläche sind Raumaufteilung, Sanitärbereich, Elektrokoordination und Zeitplan entscheidend.</p>
    <p style="font-size:16px;color:var(--text-light);line-height:1.75">Radex plant Teilsanierungen nicht nach starren Paketen, sondern nach Objekt, Ziel und Zustand. Trotzdem bleibt die Grundlogik gleich: Bestand verstehen, Umfang abgrenzen, Schnittstellen prüfen, Gewerke koordinieren, sauber umsetzen.</p>
    <div class="link-list" style="margin-top:24px">
      <a href="/einsatzgebiete-rhein-main" class="link-pill">Alle Einsatzgebiete</a>
      <a href="/generalunternehmer-rhein-main" class="link-pill">Generalunternehmer</a>
      <a href="/komplettsanierung-rhein-main" class="link-pill">Komplettsanierung</a>
      <a href="/kernsanierung-rhein-main" class="link-pill">Kernsanierung</a>
      <a href="/kontakt" class="link-pill">Kontakt aufnehmen</a>
    </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Beratung anfragen</a>
  </div>
</div>` }}
      />
    ),
  },
  {
    id: 'warum-radex-fuer-ihre-teilsanierung',
    title: "Warum Radex für Ihre Teilsanierung?",
    content: (
      <div
        className="br-legacy-migrated-html"
        dangerouslySetInnerHTML={{ __html: `<div class="section">
  <div class="section-label">Warum Radex</div>
  <h2>Warum Radex für Ihre Teilsanierung?</h2>
  <p style="font-size:16px;color:var(--text-light);line-height:1.75;max-width:720px;margin-bottom:8px">Eine Teilsanierung braucht Augenmaß. Sie soll nicht zu klein geplant werden, wenn wichtige technische Punkte betroffen sind. Sie soll aber auch nicht unnötig zur Komplettsanierung aufgeblasen werden, wenn der Bestand gut ist. Radex verbindet Erfahrung im Bestand, SHK-Meisterkompetenz, koordinierte Fachpartner und regionale Nähe.</p>
  <ul class="trust-list">
    <li>
      <div class="tl-icon"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--gold)" stroke-width="2.5" aria-hidden="true"><polyline points="20 6 9 17 4 12"/></svg></div>
      <div><strong>Gezielte Sanierung</strong>Radex prüft, welche Bereiche wirklich saniert werden müssen – kein unnötiger Mehraufwand, keine übersehenen Schnittstellen.</div>
    </li>
    <li>
      <div class="tl-icon"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--gold)" stroke-width="2.5" aria-hidden="true"><polyline points="20 6 9 17 4 12"/></svg></div>
      <div><strong>Ein Ansprechpartner</strong>Wenn mehrere Gewerke beteiligt sind, koordiniert Radex den Ablauf. Keine wechselnden Kontakte, kein Koordinationschaos.</div>
    </li>
    <li>
      <div class="tl-icon"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--gold)" stroke-width="2.5" aria-hidden="true"><polyline points="20 6 9 17 4 12"/></svg></div>
      <div><strong>SHK-Meisterkompetenz</strong>Heizung, Sanitär und Gebäudetechnik werden unter Meisterverantwortung durch Bernd Knoop, SHK-Meister und Betriebsleiter, geführt.</div>
    </li>
    <li>
      <div class="tl-icon"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--gold)" stroke-width="2.5" aria-hidden="true"><polyline points="20 6 9 17 4 12"/></svg></div>
      <div><strong>Koordinierte Fachpartner</strong>Elektro, Trockenbau, Fliesen, Böden, Malerarbeiten und Innenausbau werden über qualifizierte Fachbetriebe umgesetzt und von Radex abgestimmt.</div>
    </li>
    <li>
      <div class="tl-icon"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--gold)" stroke-width="2.5" aria-hidden="true"><polyline points="20 6 9 17 4 12"/></svg></div>
      <div><strong>Schimmel- und Asbestkompetenz</strong>Radex ist zertifiziert für Schimmel- und Asbestsanierung und verfügt über Sachkunde nach TRGS 519.</div>
    </li>
    <li>
      <div class="tl-icon"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--gold)" stroke-width="2.5" aria-hidden="true"><polyline points="20 6 9 17 4 12"/></svg></div>
      <div><strong>Alltagstaugliche Planung</strong>Besonders bei bewohnten Immobilien ist eine Teilsanierung oft besser steuerbar – Radex plant entsprechend mit Staubschutz, Bauabschnitten und realistischen Zeitfenstern.</div>
    </li>
    <li>
      <div class="tl-icon"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--gold)" stroke-width="2.5" aria-hidden="true"><polyline points="20 6 9 17 4 12"/></svg></div>
      <div><strong>Regionale Nähe</strong>Als Unternehmen aus Rödermark ist Radex im Rhein-Main-Gebiet schnell erreichbar und kennt die typischen Immobilien und Anforderungen der Region.</div>
    </li>
  </ul>
  <div class="info-box">
    Wenn Sie eine gezielte Teilsanierung planen, sprechen Sie früh mit Radex. Unter <a href="tel:+496074960620">06074 960620</a> oder über den <a href="/kontakt">Kontaktbogen</a> können Sie Ihr Projekt unverbindlich anfragen.
  </div>

  <div style="text-align:center;margin-top:40px;">
    <a href="#kontakt-formular" class="btn-primary gold">Unverbindlich anfragen</a>
  </div>
</div>` }}
      />
    ),
  }
];

export const teilsanierungLegacyFaqs = [];
